### ISSUE TITLE
Mario Tennis broken on Android

### ISSUE THREAD

**Issue by drinfernoo** [libretro/mupen64plus-libretro-nx#101]
I'm not really sure what I can give as the best details for this issu, but I'm running into lots of issues with Mario Tennis on RetroArch 1.7.8 for Android.

Neither the GLES2 or GLES3 version of this core seems to handle it properly, and I'm thinking it *may* be a framebuffer issue, but it doesn't matter if I have "Framebuffer Emulation" turned on or off.

I have missing textures, black textures, lag, audio glitches, cinematics missing, etc... Pretty much everything is broken. This game used to play fine in "pre-Next" versions of the Mupen64 core, but it really isn't on these :(

Any ideas?

**Comment by m4xw** [comment]
@drinfernoo Try a lower Max texture cache size (4000 or lower)
Also it's irrelevant if the old core worked.
Next is so far ahead, u can consider it using "different" plugins by now.

**Comment by 5schatten** [comment]
`Android` is not really precise if it comes to the box hardware. So which TV box or whatever do you use?

**Comment by 5schatten** [comment]
Okay so a `Tegra X1` SoC - then it's probably not limited to Mali GPUs

**Comment by m4xw** [comment]
Works fine on Switch, but we use GL (Also on lakka-switch with nvidia blobs).
This seems to be limited to GLES variants.

**Comment by drinfernoo** [comment]
Unfortunately, neither turning off the texture cache, shader cache, or modifying the texture cache size (tried 4000 and 1500) remedied this issue :(

**Comment by m4xw** [comment]
Gave you a test build on discord.

**Comment by mudlord** [comment]
To some degree I found it broken on Win32 as well. 

Missing things like heat haze, some shadows broken, etc.

Would have to debug things under gDebugger or something.

**Comment by m4xw** [comment]
You know if that happens upstream too?

**Comment by mudlord** [comment]
Thats one thing I have to test. I would use upstream more often if it didnt have a audio implementation from Satan's anus.

**Comment by m4xw** [comment]
I think this should be fine now. reopen if issue persists

**Comment by CometHunter92** [comment]
On SD865, Android 13 (core GLES3 version, the GLES2 doesn't dosplay anything), with GlideN64, tried every settings, shadows of the players (only of the players) are broken; an additional glitch is some garbage displayed at the end of every match before the match stats screen (looks exactly like tha garbage on backgroud changes in RE2). It happens on Mupen64Plus FZ too, so I guess it's something upstream on the GlideN64 side.
