### ISSUE TITLE
No i386 Linux version?

### ISSUE THREAD

**Issue by requeijaum** [libretro/mupen64plus-libretro-nx#102]
Doesn't appear in RetroArch's v1.7.8 Core Downloader running from Lubuntu 18.04.3.

**Comment by m4xw** [comment]
No, feel free to compile yourself.
Bot builds on linux are kinda useless until https://github.com/libretro/mupen64plus-libretro-nx/issues/78

**Comment by requeijaum** [comment]
Oh, I see. Will do it!

**Comment by requeijaum** [comment]
Just built myself... doesn't work.
But ParaLLEl N64 runs like a charm.

What log do I have to paste here for you guys? 
Build log and RetroArch's verbose log will do the job?

**Comment by m4xw** [comment]
It does work.
verbose log + trace, probably some driver shenanigans on your system.
That parallel works is irrelevant.
