### ISSUE TITLE
I found Mupen64plus supports frameskip:Is it possible to add this option to the Core?

### ISSUE THREAD

**Issue by Renetrox** [libretro/mupen64plus-libretro-nx#103]
Mupen64Plus 2.5 credits April 26th, 2015
littleguy77
--
  | - android makefile and project history (for: audio, core, rsp-hle)
  | - core:
  | - fix config parameter name for savestate slot
  | - fixes to MD5 values in mupen64plus.ini
  | - ui-console:
  | - compile-time flag to support building ui-console as a library (used by Android frontend)
  | - video-glide64mk2:
  | - add config option to force polygon offset values (fixes artifacts on certains games / renderers)
Implement optional frameskip feature, which drops frames instead of rendering if game is going slow|

**Comment by m4xw** [comment]
I won't support frame skip.

**Comment by Renetrox** [comment]
I don't understand it, but I respect it, thanks anyway

**Comment by m4xw** [comment]
I think frameskip is a dirty feature, you should never have to use it.
Any specific game you want this for and on what platform?

**Comment by Renetrox** [comment]
No problem, maybe I don't know how to use the nintendo 64 emulator correctly. Previously I managed to run fluently (in my opinion) several games through frameskip. Example: he jumped 3 frames for k.I gold, 1 for fx zero, 3 for Conker's bad fur day. I'm also very grateful for the work you do.

**Comment by m4xw** [comment]
What platform?
PC, raspberry?

**Comment by Renetrox** [comment]
raspberry
