### ISSUE TITLE
Majora's Mask Bomber's Notebook Garbled Screen

### ISSUE THREAD

**Issue by CRefice** [libretro/mupen64plus-libretro-nx#108]
I recently started a playthrough of Majora's Mask using this core, and everything was working fine up to a couple weeks ago.

After updating the libretro core through the RetroArch core updater, I have encountered a bug: when opening the Bombers' Notebook screen, the menu is not shown at all; all that's shown is a black screen with some garbled flashing lines.

I haven't changed any configuration files in between tests, so I doubt it has anything to do with my configuration.

I am using the glcore video driver. Please let me know if and how I should provide more information. For the record, I checked the logs, but I couldn't find anything out of the ordinary.

**Comment by m4xw** [comment]
Well try GL driver first.
Also provide more spec's.
Works on my machine (TM)

**Comment by CRefice** [comment]
GL driver gives identical output.

Running on an i7-7500U CPU with a Geforce GTX 950M.
What other specs should I provide?

**Comment by m4xw** [comment]
Windows, Linux, driver versions?

**Comment by m4xw** [comment]
Post me your mupen core options

**Comment by CRefice** [comment]
Duh, how could I have forgotten that. I'm running on Windows with the NVIDIA Driver version 388.57.
Here's a paste of the relevant core-options:

```
mupen64plus-169screensize = "640x360"
mupen64plus-43screensize = "320x240"
mupen64plus-alt-map = "False"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "85"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "3point"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableNativeResTexrects = "False"
mupen64plus-EnableOverscan = "Disabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rspmode = "HLE"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"
```

**Comment by m4xw** [comment]
Provide a Screenshot of the corruptions please

**Comment by CRefice** [comment]
Before pressing A:
![Legend of Zelda, The - Majora's Mask (USA)-191007-223416](https://user-images.githubusercontent.com/9728191/66346568-b5e84900-e952-11e9-8775-072c8f29ac6d.png)

After pressing A:
![Legend of Zelda, The - Majora's Mask (USA)-191007-223427](https://user-images.githubusercontent.com/9728191/66346578-b8e33980-e952-11e9-85c3-7721e49e0854.png)

**Comment by m4xw** [comment]
If I can repro I will get it fixed.
Majoras is the only game that really matters here.

**Comment by m4xw** [comment]
Happens with this build?
[mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3706636/mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment]
(Win64)

**Comment by CRefice** [comment]
Nope! It now shows up as it should.

![Legend of Zelda, The - Majora's Mask (USA)-191009-232223](https://user-images.githubusercontent.com/9728191/66521545-aea87300-eaeb-11e9-9540-ae70fd023280.png)

**Comment by m4xw** [comment]
Yea ffs

**Comment by m4xw** [comment]
The issue u showed just happens for a splitsecond on switch, but I encountere a crash.
Should be able to figure this quickly when I find some more time, getting late here.

**Comment by m4xw** [comment]
Closed in favor of #117

**Comment by fzurita** [comment]
There is something really special about that screen. It actually renders at a higher resolution than the original game. I believe it switches the game to interlaced mode, so it's really rendering at twice the resolution as normal.

**Comment by m4xw** [comment]
@fzurita also weirdly enough it corrupts the menu bg afterwards, so probably some shenanigans with my fb management, also since I cache certain gl stuff and only re-execute it when some params changed, might cause these side effects too.

**Comment by m4xw** [comment]
(the bombers notebook worked for me but I had the resize artifact too)

**Comment by m4xw** [comment]
@CRefice try this https://m4xw.net/nextcloud/index.php/s/czR2Jk6zdsZC3aZ

**Comment by CRefice** [comment]
> @CRefice try this https://m4xw.net/nextcloud/index.php/s/czR2Jk6zdsZC3aZ

It works, but for one or two frames some garbage is shown on screen before the resolution resize happens. I assume that's the artifact you were talking about.

**Comment by m4xw** [comment]
Thanks!
