### ISSUE TITLE
1080 Snowboarding Screen Flashing on Odroid XU4 & N2

### ISSUE THREAD

**Issue by Cee123** [libretro/mupen64plus-libretro-nx#112]
Game doesnt run properly the screen just flashes with the sound playing. Good thing I don't have epilepsy.

Happens with European and US versions.

**Comment by m4xw** [comment]
Screenflashes are usually fbemu related. if you use GLES2 you are out of luck most likely.

**Comment by m4xw** [comment]
Try b785150465048fa88f812e23462f318e66af0be0

**Comment by m4xw** [comment]
I also pulled in some recent fixes for Mali GPU's from master, checkout the experimental branch.
I cant provide you builds for it :/

**Comment by Cee123** [comment]
Oh ok, interesting. That's alright then. Thank you for your help. Yeah I suspected it was maybe something to do with GLES2 instead of GLES3.

**Comment by Cee123** [comment]
Interestingly this game seems to work on Parallel, along with a couple of other games like Bomberman 64 which also will not work on the Arm version of NX.

**Comment by m4xw** [comment]
These are very different emu's.
Not much surprise they behave differeently.

**Comment by m4xw** [comment]
@Cee123 Please confirm both of your issues again with latest dev branch, might've been a regression at lowest resolution.

**Comment by Cee123** [comment]
Alright awesome. I'll try the latest dev branch. I'll see if that makes a difference.

**Comment by dewenhsu** [comment]
Just test in Odroid N2 TheRA, latest dev branch fix the issue.

**Comment by Cee123** [comment]
Seems to work with this latest branch.

**Comment by Cee123** [comment]
I'm a bit of a noob when it comes to github, still figuring things out with this. So I don't really know how to try the commit you posted. :(

**Comment by Cee123** [comment]
Well, I did update the mupen64plus-nx libretro core, but it seems to be exactly the same.

**Comment by m4xw** [comment]
Can you make me a video?

**Comment by Cee123** [comment]
Alright, sure thing, I will try to get a video of what it does.

**Comment by dewenhsu** [comment]
https://youtu.be/Uj0ZUTWOO38
Running Odroid N2 TheRA

**Comment by Cee123** [comment]
Thanks Dewen.

**Comment by m4xw** [comment]
@dewenhsu try fb emu off, color + depth buffer off, "Framerate: Normal", hw per pixel lightning off, less accurate blending mode on, shader depth write off.
Half of these don't work as expected on GLES2 anyway

**Comment by Cee123** [comment]
I'll try those settings too. I'll see if it makes a difference.

**Comment by Cee123** [comment]
Still the same thing. Lol

**Comment by dmrlawson** [comment]
Just to add - I'm seeing the same thing on Raspberry Pi 4

**Comment by Cee123** [comment]
Can confirm the issues ive posted for Odroid xu4 & N2 also apply to the Pi3b and the Pi4. Seems to be with the arm devices.

**Comment by m4xw** [comment]
I asked fzurita to take a look if he can reproduce it, if he doesn't, this is a issue in -nx (likely glsm), otherwise upstream issue.

**Comment by m4xw** [comment]
@Cee123 does it happen for the DK64 Dance intro?

**Comment by Cee123** [comment]
> @Cee123 does it happen for the DK64 Dance intro?

Not as far as i know. Last time i tested DK64 it ran fine. I can test it again, ill take another look.

**Comment by Cee123** [comment]
I just checked DK64 again and it's fine. No issues there.

**Comment by RitschiRitsch** [comment]
1080 screen flashing on NX with RA 1.8.2 and latest mupen64-plus next core as well.

**Comment by quicksilver7837** [comment]
Setting color buffer to rdram = async takes care of this issue on pi 4. Youll need to make sure that GLES3 is enabled otherwise I believe that setting is ignored.

**Comment by m4xw** [comment]
Yea i dont think thats function on gles2

**Comment by RitschiRitsch** [comment]
> @quicksilver7837 Setting color buffer to rdram = async takes care of this issue

Thanks a lot! That actually worked on NX. Don‘t know if in previous releases of mupen next it was enabled per default, since 1080 was working in mid 2019, and I didn‘t change these settings for sure. Or maybe some other improvement of the core has produced this issue as a negative side effect.

**Comment by m4xw** [comment]
So that confirms what i anticipated.
Closing this for now.
@RitschiRitsch just wait for threaded renderer ;)

**Comment by dankcushions** [comment]
worth adding such defaults to https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/GLideN64/ini/GLideN64.custom.ini upstream?
