### ISSUE TITLE
Pokemon Snap Unresponsive controls on Odroid XU4 & N2

### ISSUE THREAD

**Issue by Cee123** [libretro/mupen64plus-libretro-nx#113]
The game works without the annoying graphics issues in the original Mupen64plus BUT the controls are completely unresponsive. Cannot use the analog stick at all. This doesn't happen with the original Mupen64plus.

**Comment by m4xw** [comment]
Define >original Mupen64plus.

**Comment by m4xw** [comment]
I will need you to try this commit b785150465048fa88f812e23462f318e66af0be0

**Comment by m4xw** [comment]
Also keep in mind I don't officially support Odroid in *any* way, not even RPI3 (only RPI4, even tho its simliar to RPI3)
It's all contributed and I don't have hw to test, so I don't accept odroid specific Issues on this tracker.
However I will try to help whenever I can.
I will leave it open for now.

**Comment by Cee123** [comment]
Ahhh ok, damn. No worries then. Yeah I can understand that. Is there much of a difference between support for Pi4 and Odroid?

What I mean original Mupen64plus was just Mupen64plus without the NX. It seemed to be only a recently introduced issue within NX.

**Comment by Cee123** [comment]
Also, I'll try the PC mupen64plus-nx core with a controller on Pokemon Snap and see if the same issue exists there. But that should run fine.

**Comment by m4xw** [comment]
>  there much of a difference between support for Pi4 and Odroid?

Since I don't own one, I wouldn't know.
Kinda the reason its not supported :P

**Comment by Cee123** [comment]
Haha fair enough. :D

**Comment by m4xw** [comment]
Did you use analog to digital btw?

**Comment by Cee123** [comment]
I tried with and without the "analog to digital" setting and it was unresponsive with both which is weird. Not sure what could be happening there.

**Comment by Cee123** [comment]
I updated the mupen64plus-nx libretro core, but it seems to be exactly the same.

**Comment by m4xw** [comment]
@Cee123 Try removing 
```c
#ifdef HAVE_OPENGLES
	config.frameBufferEmulation.bufferSwapMode = Config::bsOnColorImageChange;
#endif
```
in `custom\GLideN64\mupenplus\Config_mupenplus.cpp`

**Comment by Cee123** [comment]
@m4xw Awesome. Alright no problem, I'll try that and let you know how it goes.

**Comment by m4xw** [comment]
Should be on develop now
