### ISSUE TITLE
various core resources (saves, states, logs etc) end up with different names

### ISSUE THREAD

**Issue by klepp0906** [libretro/mupen64plus-libretro-nx#118]
So this has caused me quite a bit of confusion, it was brief - as the same thing had happened to bsnes(HD) when the name was changed so i imagine its a simple tangle like the aforementioned.

If you try to associate a core with your n64 playlist, you see 2 options.  mupen64plus-next and mupen64plus openGL.

I chose mupen64plus-next.   The first indicator something was wonky, is my association in the ui under sublabels was mupen64plus-next openGL.   (I was like huh?).   

so i re created the playlist, and the proper name is now shown. Mupen64plus-next in the sublabel information.

However the cores config files are saved as "Mupen64Plus-Next OpenGL" still.   As are the saves and states.   Meanwhile, the logs are saved under the proper name "Mupen64Plus-Next"

Looking in the core info files the mupen64plus_next core should be called Mupen64Plus-Next and the mupen64plus core should be called Mupen64Plus OpenGL.  

The "Next-OpenGL" and asymmetry among save locations naming is obviously not keeping with the overwhelming majority of other cores and as you can imagine a potential point of confusion.

I would like to think its a simple fix but that would be entirely ignorant assumption.

**Comment by m4xw** [comment]
Mupen64Plus (the old core), does no longer exist and is archived.
You should delete it.
We dekpt the core options prefix for compat reasons.

**Comment by klepp0906** [comment]
ah, good to know on the old core as i definitely like to keep that stuff filtered out.  that would be a nice addition to RA, a means to delete cores no longer built by buildbot so people know without digging :P

as for keeping the prefix, thats perfectly fine.  I personally could care less what its called, just that all entries are named the same.

but, im just a user /shrug

**Comment by m4xw** [comment]
Well, I did it for the users^^, on retropie they use a different core prefix tho, its a Makefile flag.

**Comment by klepp0906** [comment]
lol, yea i just meant - im not trying to be overbearing, its just easier to know that for xx file you look in xx name, and have it be the same in all places.

So in keeping with your earlier bit of information,  I can delete mupen64plus_libretro.info and mupen64plus_gles3_libretro.info and mupen64plus_libretro.dll then and be all set as far as that goes?

thanks for your work on the project btw, words dont do you guys justice.
