### ISSUE TITLE
NBA HangTime slow performance sound stutter

### ISSUE THREAD

**Issue by dewenhsu** [libretro/mupen64plus-libretro-nx#119]
for the game NAB Hang Time, 
use lr-parallel64 with angrylion GFX Plugin and multi-threading ON, 
it can run smoothly. ( also lr-parallel-nx )
with mupen64plus-nx, it has slow performance and sound stutter,
is it possible to fix ? 
will lr-parallel-nx function be merged to mupen64plus-nx ?
Thank you for your greatest work.

**Comment by m4xw** [comment]
Check out the LLE branch, I will close the issue for now as you didnt provide much informations.

**Comment by m4xw** [comment]
@dewenhsu Did you try it?

**Comment by dewenhsu** [comment]
Yes, I try install the LLE branch from source ( I use Odroid N2 with TheRA system ( RetroArena ), unfortunately the compile failed at the last step, I check the log it shows something about angrylion GFX...

**Comment by dewenhsu** [comment]
there is log file error :
error: conflicting declaration ‘typedef GLfloat GLdouble’

complete log file link
https://www.dropbox.com/s/asx3qcjyjlx4rka/rps_2019-10-21_055411.log?dl=0

**Comment by m4xw** [comment]
@dewenhsu  Yea thats probably because some outdated gliden changes.
Its not needed on the LLE branch but I still include it...
Just open `/libretro-common/include/glsm/glsm.h:35` and rip it out for testing

**Comment by m4xw** [comment]
@dewenhsu btw u also might wanna try latest dev branch, it might've spammed some gl errors if you were using lowest resolution, aka default :P

**Comment by dewenhsu** [comment]
I have tried latest dev branch ( GLES2 1.0 9627dcd ) but the NBA Hangtime still run like "slow motion" during the game play, but it is off and on, sometime it will back to normal speed for a short time, then become slwo motion again.

Also tried LLE branch and rip out the glsm.h
but when build I got another error
plugin.c:378:11: error: ‘gfx_angrylion’ undeclared (first use in this function)
https://www.dropbox.com/s/e0fnox8o32pfwfs/snap1818.jpg?dl=0
https://www.dropbox.com/s/9p9v9vtmrazw2fp/rps_2019-10-25_083754.log?dl=0
How can I fix it ? thank you !

**Comment by m4xw** [comment]
LLE = 1 or something like that in the makefile

**Comment by dewenhsu** [comment]
@m4xw Thank you for your help. I tried LLE =1 in the makefile. 
The "plugin.c:382:11: error: ‘rsp_cxd4’ undeclared" error was gone,
but  "plugin.c:378:11: error: ‘gfx_angrylion’ undeclared" still exist.
https://www.dropbox.com/s/6u7rh694b3byimg/snap250.png?dl=0
https://www.dropbox.com/s/30v9oflkf105sj4/rps_2019-10-30_022733.log?dl=0
It seems very close to success, please help me, thank you !

**Comment by m4xw** [comment]
@dewenhsu 
```
   LLE = 1
   HAVE_ANGRYLION_THR = 1
```
