### ISSUE TITLE
Intro issues in Aero Fighters and F-Zero X

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#124]
In Aero Fighter Assault, the core skips the logos and goes straight to the attract mode.

In F-Zero X, you see the N64 logo but the guitar solo isn't playing as it should. Instead it plays when the comix intro screen shows up.

**Comment by m4xw** [comment]
How is standalone behaviour?

**Comment by Tasosgemah** [comment]
> 
> 
> How is standalone behaviour?

Aero Fighters Assault has a "Video System" logo and other text before the attract/demo mode.

F-Zero X has a guitar solo during the N64 logo screen.

**Comment by m4xw** [comment]
What about Interpreter?

**Comment by Tasosgemah** [comment]
Interpreter fixes F-Zero's case but not Aero Fighter's Assault.

**Comment by m4xw** [comment]
@Tasosgemah https://github.com/gonetz/GLideN64/issues/2069
https://github.com/mupen64plus/mupen64plus-core/issues/689
Is this the same issue and can I close it?

**Comment by m4xw** [comment]
I should just read..
![image](https://user-images.githubusercontent.com/13141469/69886223-325b3080-12e1-11ea-9c60-c05cf126ed35.png)

**Comment by m4xw** [comment]
I might make a seperate issue for the f-zero issue after some more testing

**Comment by Tasosgemah** [comment]
It's the same issue with the one you linked, yes

**Comment by DaveGravel** [comment]
<In F-Zero X, you see the N64 logo but the guitar solo isn't playing>
Here in my personal build if I use the new dynarec I get the same problem me too.
If I don't use the new dynarec it look to work normally.
https://www.youtube.com/watch?v=ZY2ycv1cZb8
