### ISSUE TITLE
[Libretro-specific] MAME layout flipped when running games on this core

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mupen64plus-libretro-nx#125]
![Magical Tetris Challenge (USA)-191028-094842](https://user-images.githubusercontent.com/41223243/67646269-415c6500-f968-11e9-9134-28c3ab838cca.png)

Seems like the core can't remember which settings to follow on the default.lay file.

**Comment by m4xw** [comment]
Not a core issue.

**Comment by m4xw** [comment]
Probably a frontend issue with bottom left origin
