### ISSUE TITLE
iOS branch: compilation errors

### ISSUE THREAD

**Issue by xdccrlz** [libretro/mupen64plus-libretro-nx#126]
./custom/dependencies/libpng/pngstruct.h:30:10: fatal error: '../zlib/zlib.h' file not found
#include "../zlib/zlib.h"

string #include "../zlib/zlib.h" must be changed to 
          #include "../libzlib/zlib.h"

**Comment by m4xw** [comment]
Dont report issues on experimental branches.
Will fix it later tho.
