### ISSUE TITLE
iOS branch: hires_textures support

### ISSUE THREAD

**Issue by xdccrlz** [libretro/mupen64plus-libretro-nx#127]
New version of mupen64plus_next non-correctly work with textures: hires textures seems very bad and add artifacts (see at the tree top):
![Super Mario 64 (U)](https://user-images.githubusercontent.com/29511577/67935406-cc449600-fbda-11e9-8af1-53afbcfcadfc.png)

for example old version working good with the same settings at 640x480:
![Super Mario 64 (U)3](https://user-images.githubusercontent.com/29511577/67935564-2cd3d300-fbdb-11e9-8c80-cb4e13e80c6b.png)

**Comment by xdccrlz** [comment]
Another comparison: original textures at 640x360 16:9 adjusted
![IMG_3087](https://user-images.githubusercontent.com/29511577/67936468-e5e6dd00-fbdc-11e9-832e-5e5dc2cd7c21.PNG)

hires textures
![IMG_3088](https://user-images.githubusercontent.com/29511577/67936493-f13a0880-fbdc-11e9-8ff4-148f1b9414b0.PNG)

**Comment by m4xw** [comment]
Dont report issues on experimental branches.
