### ISSUE TITLE
HTS support for cache compression

### ISSUE THREAD

**Issue by treymerkley** [libretro/mupen64plus-libretro-nx#129]
~~I know that upstream GlideN64 offers the HTS format for textures, but it's never mentioned in the documentation here if it's usable on this fork. Is it usable, and if not, how much work would it be to add it in?~~

It looks like the issue isn't HTS support, but that it doesn't support HTS cache compression toggling. This reduces compatibility with some packs (namely Nerrel's Majora's Mask pack).

**Comment by m4xw** [comment]
Already works.
https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/libretro/libretro.c#L272-L275
You will have to turn on the normal highres texture coreoption too.
Highres texture generation on windows has some troubles tho that recently got fixed afaik, you could try the experimental branch in that case.

**Comment by treymerkley** [comment]
Oh, I'm on Linux anyway, perfect. Thanks!

**Comment by treymerkley** [comment]
Just tested it, and it's not working for me. I just updated the core too. What information do you need?

**Comment by m4xw** [comment]
Where did u place the png's or the hts?
And show me all your core options.

**Comment by treymerkley** [comment]
Never mind, it's a different issue. I got a different build of a pack that did work, and what I got back when I asked why it didn't work was: 

> You have the option (mupen-nx does not have that option currently, one would need to request it) to turn off cache compression.
> 
> It reduces stuttering (unzipping eats CPU power, a lot when considering Nerrel's texture sizes) and makes the cache much bigger, since the images aren't compressed anymore (plus duplicate textures for the Japanese version, which adds another 2GB uncompressed for the MLE build).
> 
> RetroArch/mupen-nx/GLideN64 might have issues with compressed HTS cache on Linux.

So the issue here is a request to support cache compression.

**Comment by m4xw** [comment]
Sure.

**Comment by treymerkley** [comment]
You want I should update the title post?

**Comment by m4xw** [comment]
Go ahead

**Comment by m4xw** [comment]
@treymerkley Just to get it right, you want the option to not compress the cache, aja, txCacheCompression?

**Comment by m4xw** [comment]
Fixed in d0314b549653e0f115c47028d4eb9e6bbbd93b99

**Comment by treymerkley** [comment]
Exactly. As far as I know, that would fix the issue. I'll test it wherever I need to go to do so.

**Comment by treymerkley** [comment]
Thanks for getting this put together, but it didn't fix my issue. Should I open a new issue focused on the specific texture pack?

**Comment by m4xw** [comment]
Show me your core options

**Comment by treymerkley** [comment]
Sure:

```
mupen64plus-169screensize = "1920x1080"
mupen64plus-43screensize = "1280x960"
mupen64plus-alt-map = "False"
mupen64plus-aspect = "16:9 adjusted"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "3point"
mupen64plus-CorrectTexrectCoords = "Force"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "True"
mupen64plus-EnableEnhancedTextureStorage = "True"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "True"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "True"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "False"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "True"
mupen64plus-Framerate = "Fullspeed"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rspmode = "HLE"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "False"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "True"
mupen64plus-txHiresFullAlphaChannel = "True"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "2200"
```
and of course toggling cache compression doesn't help, either.

**Comment by treymerkley** [comment]
Does anything look out of the ordinary here? Thanks again.

**Comment by m4xw** [comment]
EnableTextureCache must be on @treymerkley

**Comment by treymerkley** [comment]
Yeah, so turning it on has no change.

**Comment by m4xw** [comment]
Then you have a missmatch with the options the pack was generated with or wrong paths.
