### ISSUE TITLE
support original byteswapped saves

### ISSUE THREAD

**Issue by eadmaster** [libretro/mupen64plus-libretro-nx#130]
so we do not need to use [converters for saves coming from the original hardware or emulators](https://github.com/bkacjios/OOT-Save-Converter/issues/1).

**Comment by m4xw** [comment]
This is a wontfix right now, it would literally break everything from a libretro perspective.
Maybe in half a year.

**Comment by m4xw** [comment]
The frontend has no concept of different types of saves so here its either let the core handle it and break the spec or other dirty stuff.
I will consider integration for this when we will discuss new libretro api enhancements.

**Comment by eadmaster** [comment]
i've seen the [nestopia core](https://github.com/libretro/nestopia) supports both `.srm` and `.sav` files for FDS games, not sure how they have implemented this tough.

**Comment by m4xw** [comment]
I will go ask the lr ppl about this too, maybe someone knows a not-so-hacky way for this.
I'd def. implement this if its feasible.

**Comment by Svadkos** [comment]
Beetle-psx has this too https://docs.libretro.com/library/beetle_psx/#saves

**Comment by m4xw** [comment]
@Svadkos yea the way it does it, is exactly what i want to avoid.
@eadmaster I will implement it, after some discussions with Autechre.
However I cant do it anytime soon, can you add a proper issue description, exactly how split / endianess or simliar must be provided for accessible dumping tools for n64 saves? (not familiar with it).
I will re-open the issue afterwards

**Comment by eadmaster** [comment]
> how split / endianess or simliar must be provided for accessible dumping tools for n64 saves? (not familiar with it).

check the source code of [pj64tosrm](https://github.com/heuripedes/pj64tosrm/). Currently i am using this to convert my saves to srm.

**Comment by estefan3112** [comment]
Does pj64tosrm work for anybody with OOT? I have a 13 heart save state from mupen64, and it won't convert with pj64tosrm. Many thanks for your advice!

**Comment by ElektroStudios** [comment]
More than a year has been past since this thread. Any news?. Any solution to use PJ64, EEP, SRA, FLA or MPK savegames for Nintendo 64 cores?.

**Comment by m4xw** [comment]
#248 
> PS: why this has been closed if clearly there was not any conclusion about and there was open questions by other users?.

Reminder that you are entitled to nothing. If i don't want a feature you wont get it, as simple as that

**Comment by ElektroStudios** [comment]
> 
> 
> #248
> 
> > PS: why this has been closed if clearly there was not any conclusion about and there was open questions by other users?.
> 
> Reminder that you are entitled to nothing. If i don't want a feature you wont get it, as simple as that

And if I want a little respect and education, is it necessary for you to speak in such a rude and narcissistic way?

Your words leave a lot to be desired from a developer, honestly. I am simply a beginner RetroArch user who asked a question looking for some kind of help / guidance / answers, and to that I do have the right, no matter how much you say I have no right to anything.

Anyway I will say that in the end I found a solution, and I will explain it below. For those who may be interested, on this page you can download a PJ64toSrm binary for Windows: https://emulation.gametechwiki.com/index.php/Save_Converters#Nintendo_64

I can absolutely confirm that all kinds of savegames (PJ64, EEP, SRA, FLA and MPK) work by converting them to the accepted format (srm) with this program. You just have to give the same name to the rom / zip and the save file.

Greetings to all.

**Comment by m4xw** [comment]
Then stop being noise and actually look around on the issue tracker.

**Comment by eadmaster** [comment]
can this be reopened until it's fixed?

**Comment by m4xw** [comment]
> 
> 
> can this be reopened until it's fixed?

As the tag suggests, this Issue has been superseded.
It's included in https://github.com/libretro/mupen64plus-libretro-nx/issues/248
