### ISSUE TITLE
Not switching to native resolutions with CRT SwitchRes

### ISSUE THREAD

**Issue by naytai** [libretro/mupen64plus-libretro-nx#131]
Hello,
When using CRT SwitchRes (native mode), the core is not switching the output resolution to match the native/internal resolution of the game.
For instance, Star Wars - Roque Squadron uses several internal resolutions (640x480, 640x338, 512x446, 512x338, 640x296), but the core keeps it at 240p all the time.
Thanks.

**Comment by m4xw** [comment]
> but the core keeps it at 240p all the time.

That's why there is a option to set resolution, make sure its using core provided aspect ratio.
And no, I won't implement that, also in 240p mode it will use nativeResFactor to scale it down, this is a gliden regression mitigation, you shouldnt even use 240p to begin with, as most of the games use bigger resolutions ( i should change the default... )
Also there is this Issue open for a simliar feature (but will differ in impl): https://github.com/libretro/mupen64plus-libretro-nx/issues/37

**Comment by m4xw** [comment]
@naytai Feel free to checkout the build i posted in #37 , it might be what u wanted anyway?
If you can give me some close up shots how it looks on a CRT.

**Comment by naytai** [comment]
Hello @m4xw 
Thanks for your attention.
I tested the build you posted in https://github.com/libretro/mupen64plus-libretro-nx/issues/37.
It now outputs dynamically between 240p/480i according to the game internal resolution, which is really nice.

Here are some some shots using the regular core, which keeps a static resolution (240p):

![PD - title 240p](https://user-images.githubusercontent.com/42573484/70044560-5c427a80-15a1-11ea-819f-3d6097908fe7.jpg)
![PD - logo 240p](https://user-images.githubusercontent.com/42573484/70044577-64021f00-15a1-11ea-9bf9-2c4f0fe281ea.jpg)
![PD - ingame 240p](https://user-images.githubusercontent.com/42573484/70044594-6a909680-15a1-11ea-9a9d-57783ff0933e.jpg)

And here with your latest build. The title and logo screens are output at 480i, then it changes automatically to 240p ingame:

![PD - title 480i](https://user-images.githubusercontent.com/42573484/70044900-f276a080-15a1-11ea-8a9f-b05527be8d95.jpg)
![PD - logo 480i](https://user-images.githubusercontent.com/42573484/70044912-f86c8180-15a1-11ea-8dfc-09a936305518.jpg)
![PD - ingame 240p 2](https://user-images.githubusercontent.com/42573484/70044922-fc989f00-15a1-11ea-95c0-2f9e10520fe2.jpg)

However, I'm not sure if the internal resolution is scaling correctly. In Star Wars Rogue Squadron it seems to be a little squashed.

All these screens were outputted at 480i by the core:

![SWRS - title squashed - 480i](https://user-images.githubusercontent.com/42573484/70045325-ac6e0c80-15a2-11ea-99bf-43e7ef1aee6c.jpg)
![SWRS - menu squashed - 480i](https://user-images.githubusercontent.com/42573484/70045469-eccd8a80-15a2-11ea-856f-b622a4ead306.jpg)
![SWRS - ingame squashed 2 - 480i](https://user-images.githubusercontent.com/42573484/70045478-f0611180-15a2-11ea-9fe3-78f7232b9bb1.jpg)
![SWRS - ingame squashed - 480i](https://user-images.githubusercontent.com/42573484/70045486-f35c0200-15a2-11ea-8701-c3ad6a6463fa.jpg)

So, what do you think?
Again, thanks for your attention.
You are doing a great job here. Keep it up!

**Comment by m4xw** [comment]
Rogue looks indeed a bit odd.
Can you give me a "retroarch --verbose" log of game start -> start of gameplay (your last screenshot)

**Comment by naytai** [comment]
Here is the log
Let me know if you need something else.
Thanks.
[rogue-log.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/3917223/rogue-log.txt)
