### ISSUE TITLE
Crash on Amazon Fire HD 10 Tablet (2017)

### ISSUE THREAD

**Issue by gonzalo-hvega** [libretro/mupen64plus-libretro-nx#133]
I update RetroArch to 1.8.1 on my Amazon Fire HD 10 Tablet (2017), and updated Mupen64Plus-Next via core updater.

Sadly after updating the core and RetroArch, it immediately crashes upon loading any rom I used to be able to play. (example Golden Eye 007). Nothing in my config changed, mainly I checked my video driver was gl.

Hopefully this issue is resolved soon, loved gaming N64 on my work trips...

EDIT:

Just restored 10/1 core and it worked, so something must have changed since then.

**Comment by m4xw** [comment]
Probably a Issue with N64 Depth compare and your hw (should be off by default these days). anyway I can't offer support for random devices as I dont own them.
