### ISSUE TITLE
Overscan and MSAA 16x broken

### ISSUE THREAD

**Issue by strawbrains** [libretro/mupen64plus-libretro-nx#135]
Chaning the overscan settings to on/off do nothing, a black border is still around some of the video.  The offset settings show no apparent change either.  MSAA 8x works fine, but when pushed up to 16x just a black screen is displayed.  Audio and inputs seem to function fine though.  I've tested with glcore and any drivers that let me run the core and have the same results.  I'm running an 144hz 1440p LG display on an MSI Radeon RX 580 ARMOR 8GB with an AMD Ryzen 5 2600.

I've attached the logs, let me know if more info is needed.  
[retroarch__2020_01_03__09_03_30.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4019370/retroarch__2020_01_03__09_03_30.log)

**Comment by m4xw** [comment]
Probably the limitation for your hardware's internal rendering size.

**Comment by strawbrains** [comment]
Is there any recourse?  How would I determine hardware limitations when using this core?  I'd rather be able to use it without problems x16 msaa and overscan borders being cropped.  Why would having an amd radeon rx 580 change that?  Should I post my entire system specs?

**Comment by m4xw** [comment]
> Max texture size: 16384 px, renderbuffer size: 16384 px.

As per your log.
