### ISSUE TITLE
[Legend of Zelda - Majora's Mask (E) v 1.0 and v 1.1] Emulator is freezing at specific and partly random spots

### ISSUE THREAD

**Issue by fpi1337** [libretro/mupen64plus-libretro-nx#137]
Hi,

since a few days and after a long history of Mupen64Plus under Linux I tried to play Majora's Mask on my MX Linux 19 distro. Before choosing Retroarch and the Mupen64Plus-Next Core I first installed the "old" and "normal" (v. 2.5) Mupen64Plus on my computer. I thought Mupen64Plus 2.5 emulator would be stable enough but unfortunately this was not the case. However, the issue I ran into is always the same. Here's ONE specific situation where I can trigger this freeze:

- After getting back my Ocarina against the Horror Kid, I go inside the Clock Tower to learn the Song of Healing. During this whole cutscene where I learn the song and learn about the Mask of Majora I am running into a freeze. This can happen at random points during the conversation. 
- I tested this about 10 times with different settings and I could recognize a pattern: in 4 of 10 cases I get a freeze when using the **Dynamic Recompiler**
- However when I switched the CPU core to **Cached Interpreter** there was no freeze at all! 

Another issue which I ran to 2 days ago was some kind of "soft lock" when using the dynarec and entering the door leading to Odalwa. There I was stuck inside the door so I had to reset the emulator and start from day 1 again.

I can provide you with my md5sum of the 2 different PAL ROMS (and yes, they are "trusted") if needed and also with a save state. It's pretty clear to me that there are issues when it comes to the PAL version of MM and the dynamic recompiler. But it goes back to old Mupen64Plus. 

When I switch to my Windows 10 OS and use PJ64 2.3 with dynamic recompiling there's no issue at all.

I would like to provide you with a Log but since I use Retroarch via Flatpak I'm not really sure how to create a log. Your Youtube channel offers a tutorial for a package installation on linux which I could not apply to this flatpak-retroarch environment.

However I can say that I have changed literally nothing of the default values of the Mupen64Plus-Next core besides

- noise emulation -> false
- framebuffer emulation -> true
- lod-emulation -> false
- max texture cache size 4000 (I tried it previously with 8000)

However it seems that these changes don't affect the emulator at all when it comes to the freezes since I already found out that there's a relationship between the cpu core (dynarec) and the freeze - at least in my case.

Greetings

**Comment by m4xw** [comment]
#49

**Comment by m4xw** [comment]
Just so u know, I played through majoras like 4 times on this emu and I didnt encounter the Issues you specifically mentioned.
I will need some more infos on your hw, use the #49 issue for further discussion please.
