### ISSUE TITLE
Quake 64 sound crackling

### ISSUE THREAD

**Issue by Xenphor** [libretro/mupen64plus-libretro-nx#138]
There is persistent crackling regardless of what is happening on an 8700k + 1050 ti with Windows 10/7. Retroarch reports constant 60fps. Using the Parallel core with Angrylion results in no crackling. No features such as rewind or input lag reduction are in use.

**Comment by ToniBC** [comment]
I think it is the same problem discussed here #72 and for now there is no solution.

**Comment by m4xw** [comment]
Dupe issue, might need to increase audio latency.

**Comment by m4xw** [comment]
Hey @Xenphor, may I ask what your monitor's refresh rate is?

**Comment by Xenphor** [comment]
> 
> 
> Hey @Xenphor, may I ask what your monitor's refresh rate is?

60Hz

**Comment by m4xw** [comment]
Do you have exact sync on?

**Comment by Xenphor** [comment]
No I don't

**Comment by m4xw** [comment]
https://cdn.discordapp.com/attachments/555706037412560909/675381796266836038/audio2_mupen64plus_next_libretro.7z
https://cdn.discordapp.com/attachments/555706037412560909/675389121421639710/b_mupen64plus_next_libretro.7z
Tell me if either build helps, (its angrylion + parallel rsp, so most core options are ignored)

**Comment by m4xw** [comment]
(issue seems to be mupen core tho)

**Comment by Xenphor** [comment]
Yes the Parallel core is fine.

**Comment by Xenphor** [comment]
Just tried it again but now the graphics are totally messed up from the title screen onward. Don't think I changed anything except maybe updating the core so I have no idea what that's about. I updated the core just now and same thing happens. I'm still on 1.8.2 of retroarch.
![Quake 64 (USA)-200207-133814](https://user-images.githubusercontent.com/929400/74064158-52793100-49af-11ea-96c9-ec7324a46db0.png)

**Comment by m4xw** [comment]
set 4:3 aspect ratio in the core options
dunno what the pak stuff is about

**Comment by Xenphor** [comment]
These are my options:
mupen64plus-169screensize = "640x360"
mupen64plus-43screensize = "320x240"
mupen64plus-alt-map = "True"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "Stripped"
mupen64plus-BilinearMode = "3point"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-CropMode = "Off"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Sync"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "True"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rspmode = "HLE"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

**Comment by Xenphor** [comment]
> 
> 
> set 4:3 aspect ratio in the core options
> dunno what the pak stuff is about

That's still on the screen from the loading screen. It's in game because the in game UI is also present at the bottom.

**Comment by m4xw** [comment]
>mupen64plus-pak1 = "memory"

**Comment by Xenphor** [comment]
> 
> 
> > mupen64plus-pak1 = "memory"

Yes because I was using hard saves. That's just from the loading screen.

**Comment by m4xw** [comment]
it certainly went ingame fine for me on boot builds and its all sw rendered... 
what exact version + md5 are u using?
I will look at it next week.

**Comment by Xenphor** [comment]
> 
> 
> it certainly went ingame fine for me on boot builds and its all sw rendered... so no clue whats going on rn.
> what exact version + md5 are u using?
> I will look at it next week.

Ok I deleted the shaders in the mupen64 folder in the system directory and that got rid of the graphics corruption, but the crackling remains.

**Comment by Xenphor** [comment]
SHA256: 85D887A24E497E310443E4BF57B0625E0529EAB5742BF0472561E7AC11EE1D9A

1.0 761dde7

**Comment by m4xw** [comment]
Well you arent supposed to use that core, but the one i linked for testing.
But thanks.

**Comment by Xenphor** [comment]
But the problem isn't with angrylion and parallel

**Comment by m4xw** [comment]
its mupen64plus-next with the angrylion plugin and the dynarec parallel rsp.
its not parallel-64 ;)
I suspect the issue to be in mupen64plus-core, so the issue should affect all plugins.

**Comment by m4xw** [comment]
(just tell me if one of those builds work for you)

**Comment by Xenphor** [comment]
Tried them and they each have crackling.

**Comment by m4xw** [comment]
Thanks

**Comment by m4xw** [comment]
Just so u know, some people dont, but there is also some funky stuff in mupen-core going on.
Not really sure what causes this.
Could be a bunch of things.

**Comment by Xenphor** [comment]
Ok

**Comment by m4xw** [comment]
I am looking into it tho ;)

**Comment by m4xw** [comment]
@Xenphor thats a build with gliden, worked for doom, if that works here i have a simple solution https://cdn.discordapp.com/attachments/555706037412560909/675457193226534953/mupen64plus_next_libretro.7z

**Comment by Xenphor** [comment]
That seems to have fixed it after playing the first level.

**Comment by m4xw** [comment]
What a drag
