### ISSUE TITLE
Cannot use Hi-res textures

### ISSUE THREAD

**Issue by TheDarkKnightRise** [libretro/mupen64plus-libretro-nx#140]
I wanted to use hires textures for super mario 64, but even if i put it in the cache folder of Mupen64plus and turn on use hi-res textures and full alpha channel, the textures do not load. I have the htc file from Project 64 in the correct place. What should I do?

**Comment by m4xw** [comment]
Generate them with the same GLN64 version (https://ci.appveyor.com/project/gonetz/gliden64/branch/master) or generate them using Mupen64Plus-Next.
The Hi-Res GLN64 options must match as it was generated,

**Comment by estefan3112** [comment]
Hi, try these options, they work in my case with the htc textures you find in the Internet, e.g. Emulation King:
mupen64plus-EnableTextureCache = "True"
mupen64plus-txHiresEnable = "True"
mupen64plus-txCacheCompression = "True"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableEnhancedHighResStorage = "False"
