### ISSUE TITLE
Yoshi Story - Missing Graphic Objects

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#141]
With the latest release some graphics are missing in yoshis story:

![Yoshi's Story-200122-134833](https://user-images.githubusercontent.com/10263536/72895771-7c2f2880-3d1e-11ea-966e-d8425494ce61.png)

As you can see in the screenshot the bubbles from the fruits are missing, plus the green line from the flower is also not displayed. Rocks are missing as well.

Savestate (no-intro verfied PAL version) can be provided.

System: 
Retroarch Win10 Versions 1.8.2
Nvidia Graphic Card 770GTX

**Comment by m4xw** [comment]
Use bgmode striped, so far all yoshi issues have been upstream bugs otherwise.
I have yet to pull the latest updates in (its on the rebase branch), so if that wont fix it, please create a issue on the gliden repo.
Closing this for now, will re-open if confirmed NX issue.

**Comment by m4xw** [comment]
Also make sure u dont have n64depthcompare on

**Comment by Papermanzero** [comment]
I did change the bg mode. Upstream works correctly.
Will try deaphtcompare.

**Comment by m4xw** [comment]
You use the latest from https://ci.appveyor.com/project/gonetz/gliden64 ?

**Comment by Papermanzero** [comment]
Issue is still reproducible with depthcompare on and bgmode stripped.
for youre I use the latest builds from gonetz.

**Comment by m4xw** [comment]
Lemme cook up a build.

**Comment by m4xw** [comment]
Try this [mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4097410/mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment]
You use 16:9 adjusted?

**Comment by Papermanzero** [comment]
Hmm. It seems Gonetz introduced the bug recently. I used the build before the last.
I updated now m64p with the plugin and with the default settings the same issue occurs.

**Comment by m4xw** [comment]
Thanks!

**Comment by Papermanzero** [comment]
I have to thank you! Great job. Highly appreciate your efforts. :)
Did you know the root cause?
