### ISSUE TITLE
Crash - HD Graphics 2000

### ISSUE THREAD

**Issue by Cereal-Killa** [libretro/mupen64plus-libretro-nx#144]
I haven't been able to run it, it crashes straight away.
I can run other console cores using OpenGL no problem.

Windows 8.1 x64.

[retroarch-log.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/4175316/retroarch-log.txt)

**Comment by m4xw** [comment]
You can't use the gl version with gles.
Your best bet with that is the angle build.

**Comment by Cereal-Killa** [comment]
Tks, where can I find that "angle build"?

**Comment by m4xw** [comment]
Uhm, good question.
@twinaphex how are the ANGLE builds currently distributed?

**Comment by m4xw** [comment]
@Cereal-Killa I guess I must've missread the log on mobile, the issue is your drivers have a gl 3.1 context and mupen requires at least GL Core 3.3
So using a GLES3 build using ANGLE would be the best case if you have to stick with Intel HD, I will need to discuss some things first.

**Comment by m4xw** [comment]
Can u use https://docs.microsoft.com/en-us/sysinternals/downloads/procdump `procdump64 -ma -e retroarch.exe` and zip up the file it creates?

**Comment by Cereal-Killa** [comment]
Thank you, I will replace the i3/HD 2000 with an i7/HD4000 this week, it's really not that great for N64, after much fiddling with it couldn't get Paralell n64 to run smoothly.

**Comment by Cereal-Killa** [comment]
> e

will do that.

**Comment by m4xw** [comment]
I curse on intel hd, but procdump will tell me whats going on.
We can look from there.

**Comment by Cereal-Killa** [comment]
Absolutely, will run it, wish I could install a dedicated gfx card but it's a custom build cabinet and can't fit anything on it 😂

**Comment by m4xw** [comment]
@Cereal-Killa I still found this build, its a bit out of date but with ANGLE, its a UWP build tho, would be great if u can still test it.
https://m4xw.net/nextcloud/index.php/s/ejS7NoxJ3KYGHeR

**Comment by Cereal-Killa** [comment]
A few issues:

1. The dump never finishes, retroarch will hang and procdump will keep looping and looping, after more than 10 minutes I cancelled it using ctrl + c and it said it didn't capture enough....
2. For the life of me could not run the appx on windows 8.1...

**Comment by m4xw** [comment]
Oh then it freezes?
You said crash

**Comment by m4xw** [comment]
in which case use `procdump64 -ma pid` when it freezes

**Comment by Cereal-Killa** [comment]
It crashes without procdump running.
While procdump is running it freezes until procdump is terminated.
