### ISSUE TITLE
Hires Textures: completing libretro documentation with recommended settings (plus MacOS question)

### ISSUE THREAD

**Issue by estefan3112** [libretro/mupen64plus-libretro-nx#145]
Hello @m4xw , as per our previous discussion in the iOS thread, I did **a first documentation of the hires function** in the libretro documentation, which is already online:
https://docs.libretro.com/library/mupen64plus/

**1. Recommended Core Settings for .htc files**
I did some further testing, and I **finally managed to configure the Core Settings correctly for usage of pre-fabricated .htc packs, both in Linux and Windows**. In my case, any deviation from the **settings highlighted in bold** result in pre-fabricated .htc packs not working. 
**Would you be able to confirm that these settings are recommended for .htc files? Am I missing further settings?** I would put them into the documentation for further guidance (of course only the bold ones):
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-rspmode = "HLE"
mupen64plus-43screensize = "1280x960"
mupen64plus-169screensize = "640x360"
mupen64plus-aspect = "4:3"
mupen64plus-BilinearMode = "standard"
mupen64plus-MultiSampling = "0"
mupen64plus-FXAA = "0"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-virefresh = "Auto"
mupen64plus-NoiseEmulation = "True"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-EnableHWLighting = "False"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableShadersStorage = "True"
**mupen64plus-EnableTextureCache = "True"**
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-txFilterMode = "Sharp filtering 1"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
**mupen64plus-txHiresEnable = "True"
mupen64plus-txCacheCompression = "True"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableEnhancedHighResStorage = "False"**
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-r-cbutton = "C1"
mupen64plus-l-cbutton = "C2"
mupen64plus-d-cbutton = "C3"
mupen64plus-u-cbutton = "C4"
mupen64plus-alt-map = "False"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-pak1 = "rumble"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-CountPerOp = "0"

**2. Compiling own .htc files in Windows does not work**
Exactly as you mentioned, compiling of own .htc packs from Rice bundles does not work under Windows. My own workaround was to compile them under Linux (also running on my iMac besides Windows and MacOS), and these .htc files then run nicely under Windows. 
So I should probably add in the documentation that compilation of .htc files from Rice packages currently does not work under Windows. Anything more to state here?

**3. Missing MacOS core**
And finally, I am apparently desparately missing this wonderful core under MacOS. I am no programmer, but I at least managed to adapt the mupen64 makefile in a way that mupen64 plain now compiles under MacoS Mojave. Do you think that I could somehow help out to get this core up and running for MacOS as well?

Many thanks for looking into this.

**Comment by m4xw** [comment]
The mentioned settings are expected.
HD textures base on the texture cache feature, the enhanced options generate hts when enabled instead of HTC (still needs all the other HD options tho).
alpha stuff depends on your actual texture pack, older packs want it off.
these core options need to match with how the cache was generated too or it won't load.
Cache compression should work tho, but needs to regenerate the cache. 

2. Yes I got told it works with 32bit png files if u convert them, apparently simliar behavior on project64. 

3. I would be glad if you can draft pr the changes that are required and we can discuss how we implement it as desired. 
Will start getting my branches wrapped up soon too... I hope. 

Good first issue btw, appreciated

**Comment by m4xw** [comment]
Also regarding 2.,never got around investigating myself.

**Comment by estefan3112** [comment]
Oh, now I get it why my own settings compile .hts under Linux - it is the enhanced settings. I will work on that further and will comment into here again . Many thanks for the fast heads up!

**Comment by m4xw** [comment]
Np I will leave the issue open for now

**Comment by estefan3112** [comment]
I think that the documentation is now as far as it can get. Windows remains a bit of a riddle. I close this now and open a dedicated MacOS compilation topic. this is a tough one...
