### ISSUE TITLE
MacOS Compilation Hurdles

### ISSUE THREAD

**Issue by estefan3112** [libretro/mupen64plus-libretro-nx#146]
Before I start with Pull Requests, here are the first issues when trying to compile the master branch under MacOS Mojave. In the sequence of the three errors - two of them I think I could resolve by help of Google.

./GLideN64/src/PaletteTexture.h:3:10: fatal error: **'malloc.h' file not found**
**suggested change for MacOS:** #include <stdlib.h>

GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:28:10: fatal error: **'X11/Xutil.h' file not found**
**suggested addition for MacOS:** CPPFLAGS=-I/opt/X11/include
(I was unsure where to put that, the general makefile? If I executed it in the Terminal before compile, it was just fine9

Finally, that one I could not resolve by myself:
GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:326:2: error: assigning to 'PFNGLTEXIMAGE2DMULTISAMPLEPROC' (aka 'void (*)(unsigned int, int, int, int, int, unsigned char)') from incompatible type
      'void (GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLboolean)' (aka 'void (unsigned int, int, unsigned int, int, int, unsigned char)'): type mismatch at 3rd parameter
      ('GLint' (aka 'int') vs 'GLenum' (aka 'unsigned int'))
        ASSIGN_PROC_ADR(PFNGLTEXIMAGE2DMULTISAMPLEPROC, TexImage2DMultisample);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:8:64: note: expanded from macro 'ASSIGN_PROC_ADR'
#define ASSIGN_PROC_ADR(proc_type, proc_name) ptr##proc_name = gl##proc_name
                                                               ^~~~~~~~~~~~~
<scratch space>:33:1: note: expanded from here
glTexImage2DMultisample
^~~~~~~~~~~~~~~~~~~~~~~
./libretro-common/include/glsm/glsmsym.h:165:37: note: expanded from macro 'glTexImage2DMultisample'
#define glTexImage2DMultisample     rglTexImage2DMultisample
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
8 warnings and 1 error generated.
make: *** [GLideN64/src/Graphics/OpenGLContext/GLFunctions.o] Error 1

Suggestion: If you see a potential for success, why not open a MacOS Branch and we try our best to bring that to compilation?

Many thanks for looking into this!

**Comment by m4xw** [comment]
Sorry that I didn't respond yet (also about to go to bed), all theese are trivial to fix on my end.
Do you just want to PR a fixed up version that at least compiles and i change it then as I like it (and properly) or do u want me to provide a branch?
The latter will take longer :P

**Comment by m4xw** [comment]
3rd error is a prototype missmatch, i will look into that one.

**Comment by estefan3112** [comment]
> Sorry that I didn't respond yet (also about to go to bed), all these are trivial to fix on my end.
> Do you just want to PR a fixed up version that at least compiles and i change it then as I like it (and properly) or do u want me to provide a branch?
> The latter will take longer :P

If you do not mind if I provide you with changes that you have to put into shape, I gladly send you a PR. As I said I have no talent for coding. You have so many branches open - PRs go into the master, right?

Also respect for all the work you are into right now! My son has a Switch and all your work for this platform is quite tempting 😃

**Comment by m4xw** [comment]
> If you do not mind if I provide you with changes that you have to put into shape, I gladly send you a PR. As I said I have no talent for coding. You have so many branches open - PRs go into the master, right?

Please do and no, all PR's go to `develop`.
However I have a huge release coming up, you might want to wait for tomorrow/monday and then u can also help me find the things I broke :P

**Comment by estefan3112** [comment]
All fine and understood!

**Comment by yzzyzz** [comment]
the problem stiil exist on devlope branch when i build the core  on mac os .

so how to fix it ??
