### ISSUE TITLE
Core options prefix

### ISSUE THREAD

**Issue by hhromic** [libretro/mupen64plus-libretro-nx#15]
I noticed that this core is using the same core options prefix than the older/regular `mupen64plus-libretro` core. I know this core is supposed to eventually replace the older one, but it is possible that in the meantime you differentiate the options? for example by appending `nx` to the prefix.

This is important to ensure this core plays nicely alongside the older core when both are installed at the same time, a very likely situation given the status of this core as for testing. This is specially important to make sure users don't get confused and are not facing errors because of this core taking options set for the older core.

**Comment by m4xw** [comment]
I actually left it to make transfering the options easier.
People use it already so I kinda don't want to force them to reconfigure everything.
The "damage" is already done in that sense :P 
Fwiw Game specific options already go in their own folder, I will def. consider this tho.

**Comment by hhromic** [comment]
Fair enough. Yes, indeed game-specific options are not a problem, just the global ones.
I was mostly thinking defensively for when I post the experimental scriptmodule in the RetroPie forums.

So far this core is at least equal or better than the old one, so I will instead encourage users to backup their config options and recommend to switch over this core for testing instead of installing alongside. Thanks for your feedback, it is very good to have an active developer here!

Looking very forward to the updated GlideN64 plugin, exciting times!

**Comment by m4xw** [comment]
I will see what I can come up with ;)

**Comment by hhromic** [comment]
I was thinking, how about using a define like this?
```c
#ifndef CORE_OPTIONS_PREFIX
#define CORE_OPTIONS_PREFIX "mupen64plus"
#endif

(...)

struct retro_variable variables[] = {
    { CORE_OPTIONS_PREFIX "-NoiseEmulation", "Noise Emulation; True|False" },
    { CORE_OPTIONS_PREFIX "-CountPerOp", "Count Per Op; 0|1|2|3" },
    (...),
    { NULL, NULL },
};

(...)

var.key = CORE_OPTIONS_PREFIX "-NoiseEmulation";
var.value = NULL;
environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var)
```

Then in RetroPie (or anywhere else) we can simply compile like this:

    CLAFGS="$CFLAGS -DCORE_OPTIONS_PREFIX=mupen64plus-next" make platform=rpi3

**Comment by m4xw** [comment]
I thought about reading "mupen64plus" and then overriding stuff with "mupen64plus-next" if set (for the transition period)

**Comment by m4xw** [comment]
I consider your approach a acceptable solution too, for the time being.

**Comment by hhromic** [comment]
Actually, mame2003-plus does the same thing :)
https://github.com/libretro/mame2003-plus-libretro/blob/663615ae1a4bd7e2977a46c3c0fd388caa478316/src/mame2003/mame2003.c#L183

**Comment by m4xw** [comment]
Yea I'd like both ways in combo
