### ISSUE TITLE
LLE RSP + GlideN64 artifacts

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#151]
According to the new update, you can use the Parallel RSP with GlideN64 but i noticed some artifacts with this combination in Mario 64

![Super Mario 64 (USA)-200219-103153](https://user-images.githubusercontent.com/12124465/74816466-e3cb9a00-5303-11ea-8fd9-0f06861be258.png)

You can see some red lines at the stair wall here. These don't exist when using HLE+GlideN64.

Not sure if other games have similar issues but i wanted to point this out since Mario 64 is usually the 1st game i test after a major update.

**Comment by m4xw** [comment]
This would be a gln issue, there are a few of this kind AFAIK.
behaviour should be identical with cxd4

**Comment by m4xw** [comment]
@Tasosgemah try a clear shadercache, just curious.
Tbf I can't remember seeing these when testing.

**Comment by m4xw** [comment]
Actually I will leave this open for now, until I verified it myself on the latest commit too.

**Comment by Tasosgemah** [comment]
Yeah, it's the same with both cache and shaders folders emptied.

**Comment by m4xw** [comment]
Post your core options

**Comment by Tasosgemah** [comment]
mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-angrylion-multithread = "all threads"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "Medium"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "16:9"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "Stripped"
mupen64plus-BilinearMode = "3point"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Optimized"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "memory"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-rsp-plugin = "parallel"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

**Comment by m4xw** [comment]
mupen64plus-EnableNativeResTexrects = "Optimized"
What if you reset this?

**Comment by Tasosgemah** [comment]
Same thing.

Can't seem to avoid this with parallel RSP and GlideN64 combination.

**Comment by Testsr** [comment]
Can reproduce.

**Comment by Pixelnarium** [comment]
Can reproduce too (ArchLinux with Haswell iGPU). Fresh core installation, was never installed before. The red lines are not permanently visible. It depends on the camera angle.

**Comment by m4xw** [comment]
@Tasosgemah Likely a upstream issue with gliden64 i guess, can you bother to confirm this?
https://cdn.discordapp.com/attachments/623627665340891186/679801508178690054/libparallel-rsp.dll
Thats a 32bit dll that should work with any standalone mupen build.

**Comment by Testsr** [comment]
Does it work on mupen64plus?

**Comment by Testsr** [comment]
Try to test the provided dill in mupen64plus, but it does not even boot.

      https://mupen64plus.org/
Mupen64Plus Console User-Interface Version 2.5.9

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.9
UI-Console:             Includes support for Dynamic Recompiler.
Core: Using full mem base
Core: Goodname: Super Mario 64 (U) [!]
Core: Name: SUPER MARIO 64
Core: MD5: 20B854B239203BAF6C961B850A4A51A2
Core: CRC: 635A2BFF 8B022326
Core: Imagetype: .z64 (native)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'GLideN64' v2.0.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.9
Input: Using auto-config file at: '.\InputAutoCfg.ini'
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.9
UI-Console Error: LoadLibrary('.\mupen64plus-rsp-parallel.dll') error: (null)
UI-Console Error: Specified RSP plugin not found: .\mupen64plus-rsp-parallel.dll
Core Status: Rom closed.

**Comment by m4xw** [comment]
This should be reproduceable with cxd4 too, just saying.
Upstream issue most likely, wonder if the new_lle branch improves it, i didnt check that yet.

**Comment by m4xw** [comment]
@Tasosgemah I got told this is a known GLideN issue, its supposedly fixed on the new_lle branch, trey https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/jobs/7094/artifacts/browse
Its my thr branch + new_lle (2.1 rc1, don't mind a crash if u change some RA options, it currently has issues with context_reset), https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/jobs/7094/artifacts/browse

**Comment by m4xw** [comment]
In case the first build doesnt work try https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/jobs/7098 , its 2am and i am just shifting branches around

**Comment by Tasosgemah** [comment]
Sorry for the late reply. I don't have time to play these days.

I tested the core in the last link you posted with Parallel RSP and GlideN64 and i don't see those red lines anymore.

**Comment by Testsr** [comment]
Same result.
