### ISSUE TITLE
(Linux) 64DD PARALLEL/LLE build flags unset?

### ISSUE THREAD

**Issue by 7oxicshadow** [libretro/mupen64plus-libretro-nx#153]
I have just tried the latest core on Linux and noticed that F-Zero X Expansion is freezing again. The makefile only forces the following flags for a Windows environment:

HAVE_PARALLEL_RSP = 1
LLE = 1

Is that intended?

**Comment by m4xw** [comment]
It is, you have set them via command line.
unix target is just far too broad IMO

**Comment by m4xw** [comment]
Dont forget HAVE_THR_AL too :P

**Comment by m4xw** [comment]
@7oxicshadow did u actually mean the buildbot ver?

**Comment by 7oxicshadow** [comment]
I have tested the build bot version and f-zero halts at the black screen where it says 64dd. I am just checking it again now to make sure my settings are correct

**Comment by m4xw** [comment]
Well u have to enable LLE rsp first

**Comment by m4xw** [comment]
If the buildbot doesnt include it (assuming it built yet), thats a issue.

**Comment by 7oxicshadow** [comment]
Yup you were right. RSP was set to HLE.

Thanks
