### ISSUE TITLE
DD support per youtube announcement?

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/mupen64plus-libretro-nx#156]
NDD ROMs and 64DD_IPL BIOS aren't mentioned in the core information, and I can't force them to work via command line.   Just noticed the blog update about it.  Tried renaming the 66DD_IPL.bin to IPL.n64 and placing it in /system/mupen64plus/, still no luck.

**Comment by m4xw** [comment]
Instructions: https://twitter.com/m4xwdev/status/1229867617491521539
