### ISSUE TITLE
Zelda Ocarina of Time menu crash

### ISSUE THREAD

**Issue by HelicopterP** [libretro/mupen64plus-libretro-nx#159]
Start the game, leave Link's house and press Start button - emulator will hang. Interestingly the menu works fine inside Link's house.
I've tried different setting (Glide, angrylion, HLE, parallel, interpriter and dynared) and all of them crash.

**Comment by m4xw** [comment]
Broken rom

**Comment by HelicopterP** [comment]
Sigh, this respone is a perfect example of a sad state of N64 emulation. Guess, some things never change...
Did you really try it, or just dismissed the issue out of hand?

CRC32 of my rom is CD16C529. According to no-into.com it's perfectly fine: https://datomatic.no-intro.org/?page=show_record&s=24&n=0376
My rom also works fine on latest stable stand alone release of muppen 64 plus and on Parallel retroarch core.

It doesn't work on mupen64 plus-nx.

**Comment by Testsr** [comment]
Testing the byte swapped version, with the latest core update, I can not reproduce the crash. 
What does the crash look like?

**Comment by Testsr** [comment]
Tested on a Windows 10 laptop, running Retroarch Version 1.8.4, with GlideN64 and HLE RDP.

**Comment by Testsr** [comment]
I can now reproduce the crash,and the crash comes from setting the framerate to Fullspeed, not a bad rom.

**Comment by Testsr** [comment]
BTW, when you do this fix, the screen will turn white.

**Comment by Testsr** [comment]
He actually tried to make it work. #49

**Comment by HelicopterP** [comment]
Ok, setting the framerate to original fixes it. I apologize.
It's weird though that rainbow colored background is visible an angrylion

**Comment by m4xw** [comment]
> 
> 
> I can now reproduce the crash,and the crash comes from setting the framerate to Fullspeed.

That is expected to break stuff, it's only supposed for a few selected games, this also forces count per op to 1.

> CRC32 of my rom is CD16C529. According to no-into.com 

No intro, kek.
Probably not listed in mupen db, too lazy to check right now.
Give me your Md5

**Comment by m4xw** [comment]
And yea given by the observations you stated and all the missing basic informations (also I know it was working just fine, I spent weeks before fixing such shenanigans).
That's a invalid issue if i ever saw one.
