### ISSUE TITLE
[GlideN64][Linux] Cannot Navigate Start Menu Majora's Mask

### ISSUE THREAD

**Issue by gilmorem560** [libretro/mupen64plus-libretro-nx#161]
Good evening all, just reporting in with a bug I've encountered. In short, when opening the start menu in Majora's Mask, the cursor appears to be stuck to the Z/R page flip buttons but I cannot navigate into the actual pages to select items, map markers, etc. This does not appear to happen in the equivalent menus in Ocarina of Time so appears to be isolated to some difference between the two titles.

Let me know if you need any more information, system info as follows, all packages are upstream/non-distro:

OS Info:
Linux Kernel 5.5.6 amd64 w/ radeon driver
Glibc 2.31
Xorg Server 1.20.4
Mesa 20.0.0
RetroArch 1.8.4
Core: Commit 81a58df

Build Info:
GCC 9.2.0
Binutils 2.34
Make 4.3
Standard Makefile used with no modifications

RetroArch Settings:
Video Driver: gl
Audio Driver: pulse
Input/Joypad Driver: linuxraw
Input Device: USB Joypad
Threated Video: False

Core Settings:
CPU - Dynarec
RDP - GlideN64
RSP - HLE

RDP 4:3 Res - 320x240
RDP 16:9 Res - 640x360
RDP Aspect - 4:3
RDP Filter - 3 point
RDP MSAA - 0
RDP FXAA - 0
RDP Noise - True
RDP Framebuffer - True
RDP LOD - True
RDP Color to RDRAM - Sync
RDP Depth to RDRAM - FromMem
RDP Background - OnePiece
RDP Hardware Per-Pixel Lighting - False
RDP Continuous Texrect - Auto
RDP Native 2D Texrects - Disabled
RDP Less Accurate Blend - False
RDP CPU Shader Depth Write - True
RDP Depth Compare - False
RDP Cache Shaders - True
RDP Cache Textures - True
RDP Overscan - Enabled
RDP Overscan Offsets - 0
RDP Tex Filter - None
RDP Tex Enhance - None
RDP Filter Bkgrnd - False
RDP High-Res Texture Features - False
RDP Enhanced Texture Features - False

Frame Dup - False
Framerate - Original
VI Refresh - Auto

**Comment by gilmorem560** [comment]
I don't know nearly enough about the code in this core to make heads or tails of this, but here is some GDB tracing of the series of calls involved between OoT or MM from button press to control going back to RetroArch if it means anything to anyone: https://pastebin.com/zhDmGvXQ

As you can see, there are quite a few more lines in the routine for OoT. To get this I just, without full debugging symbols in the core, tossed a SIGINT in process_controller_command() that fires when I get a read on pressing right. I just stepped through until RetroArch took back control.

**Comment by m4xw** [comment]
Digital to Analog.

**Comment by gilmorem560** [comment]
Sorry, I know you've closed this but...what precisely does that mean? It's a bit...vague...

**Comment by m4xw** [comment]
Set it from "none" to "Left Analog", its in your Input settings.
![2020031816583200-443D61A38DD2F1ECB0CA62CFC34C9C71](https://user-images.githubusercontent.com/13141469/76980585-a6c1ea00-6939-11ea-8a2e-82f9cc5c0d8c.jpg)

**Comment by m4xw** [comment]
Also it was Analog to Digital... always mix that up

**Comment by gilmorem560** [comment]
Ah I've never had that setting impact anything before, I'll give that a spin this evening.

**Comment by gilmorem560** [comment]
Just following up that this didn't seem to make a difference. I don't currently have a Windows setup to cross-reference and see if this is system-specific or across OSs, but in any case, still can't get it to work, and it's odd to me that it works on OoT and not MM. Can't get much more in the way of errors or tracing info though, happy to keep trying things but also not horribly invested in this, just wanted to make sure you got word that it wasn't working.

**Comment by m4xw** [comment]
Maybe you saved it as a override?
Anyway not a core issue

**Comment by m4xw** [comment]
@gilmorem560 This resolved itself i guess?

**Comment by Testsr** [comment]
When in the game is this bug report? And it does seem to work on Windows 10.

**Comment by microbrewer** [comment]
I recently experienced the same issue running Retroarch and Mupen64Plus-Next 2.1 on the Nintendo Switch. Curiously, setting the `Analog to Digital Type` to **anything but** `Left Analog` (i.e. to None or Right Analog) appears to have solved the issue.
