### ISSUE TITLE
Negative Deadzone

### ISSUE THREAD

**Issue by Insayne84** [libretro/mupen64plus-libretro-nx#163]
Hello,

Most games on the N64 have their deadzone set to higher than 0%. 
Currently it is possible to simulate the exact same deadzone by setting the Deadzone to 0, however, it would be nice if the value could be decreased below 0%, so we can compensate for it.

As example:

A game uses a 10% Deadzone. 
Setting the Deadzone below 0, let´s say -5, would compensate for this.
Now the Range will be from 5% to 100% rather than 0% to 100%.

I am sorry if this is the wrong place to post this.

**Comment by m4xw** [comment]
What option are u changing precisely?

**Comment by m4xw** [comment]
Closed due to inactivity.
