### ISSUE TITLE
[Feature Request] PAL Refresh Rate to NTSC Refresh Rate 

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#164]
Is it possible to speed up games to 60FPS although the remaining PAL mode stays intact.
There are manual romhacks for each rom:
http://www.romhacking.net/hacks/4606/

The question is if it is possible to integrate that into the emulator.

**Comment by m4xw** [comment]
You are already patching the ROM's, so patch the region too?

**Comment by Papermanzero** [comment]
A patch is not the solution...
I am asking to implement the feature without a patch

**Comment by m4xw** [comment]
I have no interest allowing that.
It would break a lot of shit.
