### ISSUE TITLE
Heavy artifacts in all games (blending mode related)

### ISSUE THREAD

**Issue by Gildum** [libretro/mupen64plus-libretro-nx#165]
With Mupen64Plus-Next 2.0 I get these weird artifacts in all games. The issue is only present when "Less accurate blending mode" is set to "false" (default). 

Example of 1080° Snowboarding:
![M64PN2 - blend OFF](https://user-images.githubusercontent.com/62594289/77736543-b06be180-700c-11ea-96bd-3162d36f3afd.png)

----------------------------
RetroArch version: 1.8.5
Video Driver: gl
Core Version: 2.0 81a58df
Core Setting: default, apart from 4:3 Resolution = 320x240

OS: Windows 7 - 64-bit
CPU: Intel Core i5-3230M
IGP: Intel HD Graphics 4000
RAM: Micron 4GB, DDR3-1600 

With the older core version Mupen64Plus-Next 1.0 (b2eb80e) there are no graphic issues at all.

---------
Small addition that is likely not related: There is now a difference in the rendered graphics between v1.0 and v2.0 (less acurate blending mode = true), where v2.0 has some slight blur in some parts of the image. Here is an example, especially visible on the "4 COURSES" font:
![m64plus1](https://user-images.githubusercontent.com/62594289/77736647-dc876280-700c-11ea-83fd-7ba6bca2d383.png)
![m64plus2](https://user-images.githubusercontent.com/62594289/77736662-e01ae980-700c-11ea-8ddd-2a889dc89f86.png)

Which one renders the graphics more accurate, I assume it's v1.0?

**Comment by m4xw** [comment]
You shouldn't use such a low resolution (lower than native), it will scale down.
You have N64 Depth compare on?
Show me your full core options, this is probably a Issue with your graphics card, or rather the lack thereof, Intel cards are problematic, best way would be using ANGLE for these.
In any way, this is very likely a upstream issue or a issue with hybrid filtering.

**Comment by m4xw** [comment]
Ah btw, earlier versions actually rendered at lower than native, now it forces nativeResFactors and renders at native res and scales it, thats probably where the slight blur comes from.
In that sense, v1 is more inaccurate but will give u more crisp. It's broken upstream these days so I can't support it rn, anyway you should be using at least  640x480 (4:3) or 960x540 (16:9)
You will also find some more Infos in #37

**Comment by Gildum** [comment]
Yeah I assumed it's very likely due to my older Intel IGP. even though it supports OpenGL 4.0. I will now test it with ANGLE.

With upstream you mean the original Mupen64Plus standalone? If so, I can test v2.5.9 to see if the issue occurs here too.

I think 1080 Snowboarding's original resolution is 320x240, since there are minor 2D sprite glitches when using 640x480. The artifact issues are still present, it's unrelated to the resolution.

N64DepthCompare is set to False (default). I turned it ON now, no difference. Core Options (default):

> mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-angrylion-multithread = "all threads"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "Low"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-rsp-plugin = "hle"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

**Comment by m4xw** [comment]
@Gildum You cant test angle, you need to build mupen and RA with it.
> . I think 1080 Snowboarding's original resolution is 320x240, since there are minor 2D sprite glitches when using 640x480:

This is irrelevant because this impacts framebuffer size, anyway this is a upstream Issue, not a mupen next issue.
If it is fixed upstream you can try my rebase-core-gliden branch

**Comment by m4xw** [comment]
> Yeah I assumed it's very likely due to my older Intel IGP. even though it supports OpenGL 4.0. I will now test it with ANGLE.

Btw, 4.2 min requirement for non-GLES.

**Comment by m4xw** [comment]
Btw I wouldn't use anything other than legacy blending for your "GPU".
In fact I use it for everything on Switch.

**Comment by Gildum** [comment]
Angle:
When I try the angle method (via retroarch_angle with Mupen64plus-Next GLES3) it crashes after launching a game.

Mupen64Plus v2.5.9:
The artifacts are not present here (though other graphic issues appear).
Though when using the m64p frontend, the same artifacts are there.

Okay since OpenGL 4.2 is the minimum anyways, I will just stick with legacy blending as you suggested and also keep a backup of Mupen64Plus-Next 1.0, in case things get worse for my poor IGP with newer updates.

**Comment by m4xw** [comment]
m64p has the latest GLN ver shipped too, so yea its a upstream issue!
As for ANGLE -> thats a old version, we dont build it daily.

**Comment by Gildum** [comment]
I just checked out the recent version Mupen64Plus-Next 2.2 with 1080° and the artifacts are gone! So that's pretty cool :)

**Comment by m4xw** [comment]
nice

**Comment by Gildum** [comment]
Just a quick update, in case someone with similar issues should stumble onto this thread:

- it seems like on my system only some games work without problems with default blending mode, e.g. 1080 Snowboarding
- Mario Kart 64 has severe issues: besides some graphic glichtes at the main screen, selecting a race results in retroarch crashing + big memory leak, locking my system for ~2min 
- so for users with a gpu that doesn't support openGL 4.2, it's best to keep "less accurate blending mode" on
