### ISSUE TITLE
segmentation fault on odroid

### ISSUE THREAD

**Issue by jit06** [libretro/mupen64plus-libretro-nx#166]
compiled from the latest source either with gcc-7 or gcc-8, this core makes retroarch crash with segmentation fault when loading roms. Same for old mupen64-libretro since a few days (it used to work before... let say 2 or 3 weeks ago)

Tested on Odroid C1, with latest retroarch from retropie scripts on official ubuntu 18.04.
I tried with z64 and v64 rom format (MarioKart, Aerogauge, Extrem-G), with different sound resampler (sinc, cc and null), with alsa, alsathead and sdl2.

I can help debuging if needed

**Comment by m4xw** [comment]
Sounds like a frontend issue to me.

**Comment by m4xw** [comment]
For reference, use this repo https://github.com/libretro/RetroArch
