### ISSUE TITLE
issue compiling for odroid xu4

### ISSUE THREAD

**Issue by Wheaties466** [libretro/mupen64plus-libretro-nx#167]
Here is the log. I can't see to figure out what is going wrong. I am installing it via the setup within retropie and I setup the whole system according to this. I cannot seem to get mupen64plus to compile either. I am attaching my logs. Let me know if there is anything else relevant to grab,

https://retropie.org.uk/docs/Odroid-XU3-XU4/

[rps_2020-03-30_203459.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4406000/rps_2020-03-30_203459.log)

after some research it appears as thought the correct flags are not getting set.

      # ODROID-XU3 & -XU3 Lite and -XU4
      ifeq "$(shell expr `gcc -dumpversion` \>= 4.9)" "1"
         CPUFLAGS += -mcpu=cortex-a15 -mtune=cortex-a15.cortex-a7 -mfpu=neon-vfpv4 -mvectorize-with-neon-quad

`g++   -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -O2 -pipe -fvisibility-inlines-hidden -std=gnu++11 -D_CRT_SECURE_NO_WARNINGS -O3 -DNDEBUG -fsigned-char -ffast-math -fno-strict-aliasing -fomit-frame-pointer -fvisibility=hidden  -DGIT_VERSION=\"" 81a58df"\" -DCORE_NAME=\""mupen64plus-next"\" -DOS_LINUX -I./mupen64plus-core/subprojects/md5 -I./mupen64plus-core/subprojects/minizip -I./mupen64plus-core/subprojects/xxhash -DHAVE_NEON -D__ARM_NEON__ -D__NEON_OPT -ftree-vectorize -mvectorize-with-neon-quad -ftree-vectorizer-verbose=2 -funsafe-math-optimizations -fno-finite-math-only -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -D__LIBRETRO__ -DUSE_FILE32API -DM64P_PLUGIN_API -DM64P_CORE_PROTOTYPES -D_ENDUSER_RELEASE -DSINC_LOWER_QUALITY -DTXFILTER_LIB -D__VEC4_OPT -DMUPENPLUSAPI  -I./custom -I./custom/mupen64plus-core -I./custom/android/include -I./custom/GLideN64 -I./GLideN64/src -I./GLideN64/src/osal -I./mupen64plus-core/src -I./mupen64plus-core/src/api -I./custom/mupen64plus-core/plugin/audio_libretro -I./libretro-common/include -I./libretro -I./GLideN64/src/inc -I./xxHash -I./custom/dependencies/libpng -I./custom/dependencies/libzlib  -fPIC  -marm -mfloat-abi=hard -mcpu=cortex-a15 -mtune=cortex-a15.cortex-a7 -mfpu=neon-vfpv4 -mvectorize-with-neon-quad  -DEGL -DHAVE_OPENGLES -DHAVE_OPENGLES2 -DGLES2  -DNEW_DYNAREC=3 -DDYNAREC -I./mupen64plus-core/src/asm_defines/ -c GLideN64/src/Combiner.cpp -o GLideN64/src/Combiner.o`

this looks appears as though it is not detecting the proper flags.

**Comment by m4xw** [comment]
It sets the flag, but appends them at the end.
So seems like smth sets ` -mcpu=cortex-a7 -mfpu=neon-vfpv4` there.
*However*, you run out of memory compiling it, maybe add some swap?

**Comment by m4xw** [comment]
I will check the double set of mcpu tho, but that would be a different issue.

**Comment by Wheaties466** [comment]
@m4xw Thank you for the response. I am fairly new to debugging this type of issue. What lead you to knowing that I ran out of memory? I have 0 swap configured so i'll do that and try to recompile.
