### ISSUE TITLE
[Audio Sync] Super Smash Bros. Intro

### ISSUE THREAD

**Issue by Testsr** [libretro/mupen64plus-libretro-nx#175]
The intro of the game is not synced well, with the visuals coming
before the audio. Changing RDP and RSP doesn't work.
I am Using Smash Bro(Europe).

**Comment by Testsr** [comment]
This is what it suppose to look like. https://www.youtube.com/watch?v=rIwWCioBpEM

**Comment by m4xw** [comment]
Cant Reproduce on my Part, not enough infos supplied either.
Your Settings are probably too intense for your setup.
Changing RDP/RSP needs to close and start the game again.

**Comment by Testsr** [comment]
I noticed that in the hand countdown, the beeps occurred after the hand gestures.  I am using latest RetroArch,  Intel HD Graphics , xaudio  and the following configuration:
mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-angrylion-multithread = "all threads"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "Low"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Auto"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "cached_interpreter"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-rsp-plugin = "parallel"
mupen64plus-ThreadedRenderer = "True"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"
This is a zipped video of when this happens.
[RetroArch Mupen64Plus-Next OpenGL 2.0.5 0832354 2020-04-17 19-56-12.mp4.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4492220/RetroArch.Mupen64Plus-Next.OpenGL.2.0.5.0832354.2020-04-17.19-56-12.mp4.zip)

**Comment by Testsr** [comment]
BTW Parallel n64 does not exhibit this.

**Comment by m4xw** [comment]
Yea cursed Intel HD graphics..
What is your audio latency set to in RA settings?

**Comment by Testsr** [comment]
47 ms.

**Comment by Testsr** [comment]
Also of note, Parallel N64 does not exhibit this issue.

**Comment by Testsr** [comment]
I think I have found a solution to the problem. Setting the VI refresh to 1500 instead of auto fixes the audio sync issue.

**Comment by m4xw** [comment]
You didn't have to create that Issue but thanks for posting the find.

**Comment by m4xw** [comment]
Also then the Issue shouldn't be iGPU related

**Comment by Testsr** [comment]
I checked the other two versions of the rom, and they played back fine. If you tested my bug with the American Version, test it with the European version. This is probable a clock speed issue from European 50 hz.

**Comment by Testsr** [comment]
More precisely, the video and audio speeds are different, causing audio desync.
