### ISSUE TITLE
msaa on ios result in a black screen

### ISSUE THREAD

**Issue by QcSamuel** [libretro/mupen64plus-libretro-nx#176]
any msaa value will result in a black screen 
on ios devices and only the video output is affected while the emu will still run the game 

video of the issue here: https://m.imgur.com/a/bSx6G95

mupen64Plus-Next 1.0 370efb1
iphone 7 ios 13.4.1
jailbroken

**Comment by estefan3112** [comment]
Same here on non-jailbroken iPad with any mupen64-next version.

**Comment by m4xw** [comment]
It's a GLES3 feature iirc

**Comment by QcSamuel** [comment]
tried the gles3 core same thing

**Comment by m4xw** [comment]
How did you build it?
Also use the latest ver.

**Comment by QcSamuel** [comment]
i don't have a mac i use this ipa https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503

**Comment by m4xw** [comment]
Does it show "GLES3" in the bottom left?
I need to have the Issue confirmed on develop branch tho, so long I won't investigate.

**Comment by QcSamuel** [comment]
![45C97AB6-B867-48DB-A200-35E8381217C4](https://user-images.githubusercontent.com/41095253/79870625-40553f00-83b1-11ea-946a-cf90c6e6ce1a.jpeg)

**Comment by QcSamuel** [comment]
> Does it show "GLES3" in the bottom left?
> I need to have the Issue confirmed on develop branch tho, so long I won't investigate.

core is now gles3 2.1 e0f7f09 and the same black screen with msaa is there
