### ISSUE TITLE
Virtual Pro Wrestling 2 (Japan) Freezes on launch 

### ISSUE THREAD

**Issue by drwafflesphd** [libretro/mupen64plus-libretro-nx#181]
It was playing smoothly and without issues in March, but recently since I've updated around two weeks ago the game will not launch.

Hardware is the Pi4 2gb model.

**Comment by m4xw** [comment]
Upstream issue if any, will need to wait for the next updates.

**Comment by m4xw** [comment]
@hhromic small chance this might be related to GL shenanigans?
