### ISSUE TITLE
how to get compiled binary for rpi?

### ISSUE THREAD

**Issue by k0st1x** [libretro/mupen64plus-libretro-nx#183]
currently the retropie has mupen64plus_libretro.so with readme.md
> This core is deprecated and will no longer be maintained.
Please use https://github.com/libretro/mupen64plus-libretro-nx

but i cannot find how to get compilted core mupen64plus-libretro-nx. compile from the sources is a hard way for me.

is there any compilation/tests artifact so i can get the compiled binary?

**Comment by dankcushions** [comment]
current retropie comes with nx. it's called 'lr-mupen64plus-next' in the package manager, where you can download the binary.

**Comment by k0st1x** [comment]
@dankcushions thank you. currently i'm using the kodi retroarch addon on rpi3 and my way is odd (it uses the https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/ url as repository which is not contains the mupen64 core ). i've downloaded the original retropie img file, and it is contains the "mupen64plus_libretro.so" in the cores directory.

can you suggest me, how to find, where retropie cores repository located?

@m4xw thank you for suggested solution, but im not the linux guy. currently my wsl ubuntu (on windows) tells me the while making the sources from current repo
>g++: error: unrecognized command line option ‘-mvectorize-with-neon-quad’
g++: error: unrecognized command line option ‘-mfpu=neon-fp-armv8’
g++: error: unrecognized command line option ‘-mfloat-abi=hard’

or should i compile sources on the rpi3 self?

**Comment by m4xw** [comment]
You have to compile it on your rpi3 or cross compile (but i wont get into how u do it)

**Comment by k0st1x** [comment]
@m4xw this is a hard way )
can somebody share the mupen64plus-libretro-nx.so file with me?

**Comment by hhromic** [comment]
@k0st1x the official RetroPie images for RPI2/3 do not come with `lr-mupen64plus-next` pre-installed so you won't find the binary in these images (as you found out). The RPI4 image does come with this core pre-installed but that binary will not work on RPI3.

However you can directly download the RetroPie RPI3 binaries for `lr-mupen64plus-next` here:

* [Debian Stretch OS](https://files.retropie.org.uk/binaries/stretch/rpi3/libretrocores/lr-mupen64plus-next.tar.gz)
* [Debian Buster OS](https://files.retropie.org.uk/binaries/buster/rpi3/libretrocores/lr-mupen64plus-next.tar.gz)

Good luck!

**Comment by k0st1x** [comment]
thanks @hhromic, I'm very appreciate your detailed answer!

**Comment by k0st1x** [comment]
@hhromic, thank you, the 'stretch' package works fine.
but how libreelec related to debian?
plz, give me advice, and how i must select stretch or buster repo for libreelec9.3.1?
and how i can list the https://files.retropie.org.uk/binaries/buster/rpi3/libretrocores url for cores/files?
