### ISSUE TITLE
Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (Japan) soft locks within the first few minutes

### ISSUE THREAD

**Issue by meunierd** [libretro/mupen64plus-libretro-nx#186]
Both with the stock rom, and the recent translation patch, Shiren 2 freezes sometime during the intro. If you're quick you can name your character and choose your initials and it will soft lock some time after that.

**Comment by SharkSnack** [comment]
I can reproduce this issue running the game on a Nintendo Switch. (RetroArch 1.8.5, Mupen64Plus-Next OpenGL 2.0 81a58df).

**Comment by loganmc10** [comment]
I don't think this happens with upstream, at least not with the interpreter, I got to this point:

![F3_ï¾Œï½³ï¾—ï½²ï¾‰ï½¼ï¾šï¾2-000](https://user-images.githubusercontent.com/848146/81017961-b2ea0400-8e20-11ea-9760-60e4d07a0784.png)

It doesn't seem to freeze or anything as I walk around

**Comment by meunierd** [comment]
I should specify this was on Switch with the dynarec

**Comment by m4xw** [comment]
Thanks for checking Logan, would've been my next question.
So can be a aarch64 dynarec issue or smth that got fixed upstream between the interrupt scheduling rework and now

**Comment by SharkSnack** [comment]
It's been a while, so I tried testing it again and the game is still unplayable.

1.9.0 - Mupen64Plus-Next (2.1-OpenGL ea1c677)
- Game audio cuts out at the main menu
- Menu borders have visual glitches
- Black screen during the intro after "それは　シレンが　まだ　こどもだったころの　おはなし"

I also tried a nightly version (2.1-OpenGL 96d2a99) and had the same result.

Please let me know if there's any way I can assist, I'm really looking forward to the day this game becomes playable on a Nintendo Switch :)

**Comment by m4xw** [comment]
> 
> 
> It's been a while, so I tried testing it again and the game is still unplayable.
> 
> 1.9.0 - Mupen64Plus-Next (2.1-OpenGL [ea1c677](https://github.com/libretro/mupen64plus-libretro-nx/commit/ea1c677c1e61ce1d95809c09cf26ffa75cd7e9dc))
> 
>     * Game audio cuts out at the main menu
> 
>     * Menu borders have visual glitches
> 
>     * Black screen during the intro after "それは　シレンが　まだ　こどもだったころの　おはなし"
> 
> 
> I also tried a nightly version (2.1-OpenGL [96d2a99](https://github.com/libretro/mupen64plus-libretro-nx/commit/96d2a99f36f300170ecdde75e7dfd58d18720011)) and had the same result.
> 
> Please let me know if there's any way I can assist, I'm really looking forward to the day this game becomes playable on a Nintendo Switch :)

But... no softlock?

**Comment by SharkSnack** [comment]
It still soft-locks when it's about to transition to drawing the characters/environment on-screen, after the white text on black background intro (after creating a new journal and starting the game).

But it seems it doesn't soft-lock at the main menu anymore, at least.

**Comment by m4xw** [comment]
Please check again on latest version. Should be on the bot in max 3h

**Comment by m4xw** [comment]
Please open again if its still a thing

**Comment by meunierd** [comment]
Just tried on fb0b9c5 and now it hard crashes the emulator at the title screen.

**Comment by meunierd** [comment]
Though I don't believe I have the permission to reopen this issue.

**Comment by m4xw** [comment]
Interesting!

**Comment by m4xw** [comment]
> 
> 
> Though I don't believe I have the permission to reopen this issue.

was that with translation patch or without?

**Comment by meunierd** [comment]
This was with the patch. I'll test without and report back.

**Comment by meunierd** [comment]
The same behaviour is also present in a clean No-Intro dump.

**Comment by m4xw** [comment]
What platform are you testing on?
Gillou wasnt able to reproduce on standalone without the translation patch. I do nothing special here.
Is it possible for you to get me a gdb trace?

**Comment by meunierd** [comment]
This only manifests on switch. It runs totally fine against my mac. Are
there instructions for getting this trace on switch?

**Comment by meunierd** [comment]
It's also worth noting this is with the dynarec enabled.

**Comment by m4xw** [comment]
clear all files from /atmosphere/crash_reports
execute, do crash.
upload the created files in crash_reports (only the txt/log is needed)

**Comment by m4xw** [comment]
uhm, its probably fixed already with 633f3788360d6e7cbc51f6a9507cf922c1e33205
Now that i think about it... try the very last commit

**Comment by meunierd** [comment]
It works on the latest commit for both No-Intro and the patch. Thank you 🙌

**Comment by SharkSnack** [comment]
A little late on my part, but I confirmed that it works as well. Thank you so much for your work! It's really a dream come true to play this game on Switch.
