### ISSUE TITLE
Fix scissoring

### ISSUE THREAD

**Issue by natinusala** [libretro/mupen64plus-libretro-nx#19]
The current core does `glScissor` once and then does `glEnable(GL_SCISSOR_TEST)` and `glDisable(GL_SCISSOR_TEST)` when needed, without resetting the scissor rectangle with `glScissor`.

This results in issues if the frontend uses scissoring (which is the case) - when opening and closing the frontend menu (which resets `glScissor`), the core will enable the scissoring test with a leftover rectangle from the frontend, creating black bars hiding the game viewport.

I found a workaround in the frontend : if I set the scissoring rectangle to the whole viewport when disabling the test, it doesn't hide the game anymore when going back to the core. However, it's still wrong, as the rectangle is still different from the one mupen set in the first place (it's too large). It may result in artifacts if the core draws things in an area expected to be scissored out, or if it doesn't clear those areas properly between frames.

**Comment by m4xw** [comment]
Note: This might be related to glsym

**Comment by bparker06** [comment]
surround the frontend draw functions with glPushAttrib/PopAttrib with GL_SCISSOR_BIT, or use glGet to get the current box and then set it back when done.

**Comment by mudlord** [comment]
^
