### ISSUE TITLE
N64 Depth Compare causes black dots on Nvidia turing/rtx cards.

### ISSUE THREAD

**Issue by BParks21** [libretro/mupen64plus-libretro-nx#193]
With depth compare enabled on the latest builds black dots appear on 3D textures in all games I've tested. I can't reproduce this on Pascal cards, only Turing.  
![Super_Mario_64_USA-200509-214817](https://user-images.githubusercontent.com/12180630/81489251-4f593f80-9241-11ea-978b-406fb5f27500.png)
![Banjo-Kazooie_USA_Rev_A-200509-215002](https://user-images.githubusercontent.com/12180630/81489252-4ff1d600-9241-11ea-900b-5208ea2800d2.png)

**Comment by m4xw** [comment]
Iirc there were some related changes upstream, if it persists next rebase I guess ask gonetz

**Comment by BParks21** [comment]
@m4xw In upstream there are other options for depth compare that are missing in libretro. They are fast and compatible, compatible fixes it i believe.

**Comment by m4xw** [comment]
Guess why I said to wait till next rebase

**Comment by m4xw** [comment]
This build has some other testing changes, but should implement compat mode: [mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4609187/mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment]
In case you get "failed to open libretro core": https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/jobs/7728/artifacts/browse
