### ISSUE TITLE
Textures being replaced with solid black / black boxes on iOS 

### ISSUE THREAD

**Issue by HappehLemons** [libretro/mupen64plus-libretro-nx#196]
Having lots of issues on IOS. Lots of games I've been testing have black textures, sometimes making games unplayable

IOS Version 13.4
Retroarch version 1.8.6

Gauntlet Legends (Bottom HUD Completely missing - unplayable without it):
https://i.imgur.com/JIIvOL3.png

Conkers Bad Fur Day (Some character models have black textures):
https://i.imgur.com/kxk2ydh.png

007 Goldeneye (In Game Text and other textures covered by black boxes): 
https://i.imgur.com/mJI9Okp.png

Smash 64 (In Game Text and other textures covered by black boxes)::
https://i.imgur.com/I0nAlaZ.png

**Comment by m4xw** [comment]
How do you build the binaries?

**Comment by HappehLemons** [comment]
I didn't build them myself - this was using the latest stable build directly from the Retroarch website.

I've seen several other reports of this as well for iOS users.

**Comment by m4xw** [comment]
That build isn't actually supported.

**Comment by HappehLemons** [comment]
Oh, is there a supported build I should be using in order to perhaps resolve this issue? 

Is there a way I can check to see what's supported?

**Comment by m4xw** [comment]
You need to compile yourself. The buildbot builds so far never officially "succeeded", so can you link it to me?
I dont see mupen here http://buildbot.libretro.com/nightly/apple/ios-arm64/latest/

**Comment by HappehLemons** [comment]
For some reason it's only included in the .ipa and not listed there.

Here's the file:
https://www.mediafire.com/file/t2r3ouu5arv0yd1/mupen64plus_next_libretro_ios.dylib/file

**Comment by m4xw** [comment]
hah, u see why its not supported if the author isnt even aware where it ended up, even tho it failed build...

**Comment by HappehLemons** [comment]
Thanks for helping me understand. This is all new to me. Ill try to figure out how to build and report back.

**Comment by estefan3112** [comment]
Hi, I can confirm all issues reported above with the Core delivered in Retroarch 1.8.6 stable, which is Mupen64Plus-Next GLEW3 (1.0 a7adaf2).

You can build the Core by yourself with Libretro-super as follows:
1. Download the Libretro-super repo
2. From inside of the directory:
./libretro-fetch.sh mupen64plus_next
./libretro-build-ios-arm64.sh mupen64plus_next
It builds Mupen64Plus-Next GLES3 (2.0.5 f68044f) as of today.

All the black boxes also show up there, unfortunately.

**Comment by estefan3112** [comment]
I also built Mupen64Plus-Next GLES3 (2.1 3360cff8) from the Rebase branch with the above mentioned script, and this results in a complete mess of all gfx in all games, unfortunately. Just a few screenshots of Super Smash 64 and Super Mario 64. Gauntlet, for example, full black screen.

![Super Smash Bros  (U)  ! -200512-094828](https://user-images.githubusercontent.com/24915559/81655308-6f9e1f80-9436-11ea-948f-f39bfb6b4a5b.png)
![Super Mario 64 (USA)-200512-094918](https://user-images.githubusercontent.com/24915559/81655341-7462d380-9436-11ea-841f-587e4aa16e31.png)
![Super Mario 64 (USA)-200512-094946](https://user-images.githubusercontent.com/24915559/81655393-7e84d200-9436-11ea-9338-b73cf316a6ae.png)

**Comment by oddMLan** [comment]
try enableHybridFilter = 0
does it work now?

**Comment by HappehLemons** [comment]
Was that in reference to the rebase branch?


For Mupen64Plus-Next GLES3 (1.0 a7adaf2) and Mupen64Plus-Next GLES3 (2.0.5 f68044f)  enableHybridFilter = 0 that did not fix the black boxes, or seem to make any changes in the listed games. 

Is this issue worth reopening now that the builds are being created properly and this issue still seems to persist?

**Comment by estefan3112** [comment]
> try enableHybridFilter = 0
> does it work now?
No, all GFX screwed up entirely in 2.1.

> Was that in reference to the rebase branch?
Yes, the Rebase Branch screwed it up with me. Reconfirming now in a completely fresh install (in progress).

**Comment by HappehLemons** [comment]
> > Yes, the Rebase Branch screwed it up with me. Reconfirming now in a completely fresh install (in progress).

Any luck with this, or still running into the same issues with the Rebase Branch?

**Comment by m4xw** [comment]
I pushed another update to the rebase branch earlier that pulls in a bunch of shader fixes from upstream.
If you can build it yourself, give it a shot.
Waiting for estefan to give me feedback, I dont have Mac stuff so I cant provide builds :/

**Comment by HappehLemons** [comment]
I can build the rebase branch and test it tomorrow - but I'm just learning about this. 

What different files do I download off the repos in order to build that branch? 

I searched and I don't see anything directly called "rebase" if far as I could see.

**Comment by HappehLemons** [comment]
![Super Smash Bros (U) ! -200512-094850](https://i.imgur.com/VRMa7yU.png)

Was able to figure it out, but it seems like the rebase branch still is having the same issues as previously mentioned with the build I did today (f68044f).

**Comment by m4xw** [comment]
Part 1 https://github.com/gonetz/GLideN64/pull/2272

**Comment by HappehLemons** [comment]
Thanks a lot for looking into this. This is such a great core and I want to fully utilize it on iOS if possible. Happy to continue to help where possible.

**Comment by HappehLemons** [comment]
Has this been possibly fixed on any branch? I saw pull request was complete but wasn't sure if that means this issues may be resolved.

**Comment by HappehLemons** [comment]
Can confirm this is still happening in #f68044f

**Comment by m4xw** [comment]
The rebase branch doesn't pull in the very last gliden commit (the fix I made).
Will do that after parallel rdp is wrapped up & integrated on develop.
As for using_tlb not being defined, that very weird, did you forget a make clean?
If its not found for IOS its a easy fix tho, let me know how a clean build goes (but well it would still be broken).
Apparently theres some builds already for IOS with mupen 2.1, might need to ask @estefan3112

**Comment by HappehLemons** [comment]
I see, thanks for letting me know. Ill hold off on the rebuild until the fix is included in the pull.

**Comment by estefan3112** [comment]
Hi, there is a 2.1 iOS build here:

http://johan.margueritte.free.fr/iosemu

However, your black pixels problem is still there, and hires textures do not work properly, so be warned ;-). Cheers!

**Comment by Flytheo** [comment]
Thing is this is still happening in 2024

**Comment by m4xw** [comment]
> Thing is this is still happening in 2024

This issue was fixed long ago, it was a issue with non power of two textures.

Otherwise provide screenshot, core options and create a new issue
