### ISSUE TITLE
Rayman 2 with Mupen 64 Next Plus random freezing

### ISSUE THREAD

**Issue by abusuzuki** [libretro/mupen64plus-libretro-nx#197]
I’m playing this game on Retroarch the latest version 1.8.6 on windows 10 with Mupen 64 Next Plus with default settings, 
The problem is that the game freezes randomly on a world map ( When I keep moving Rayman to move between stages The picture freezes completely while the music remains ) and this happens with the US and European version of the game. I also tried it in 2 different PC and the same problem is happening, I uploaded this video to prove this problem:
https://www.youtube.com/watch?v=7H0t8DmjQlg

**Comment by m4xw** [comment]
Does it happen with interpreter?

**Comment by abusuzuki** [comment]
> Does it happen with interpreter?

Yes I tried the interpreter option, I have never encountered freezing with this option, but with this option Rayman will never be able to enter the Spiral Door, the spiral Door  which is like a circular vortex found at the beginning and end of each stage and players can't finish stages without entering it,  the interpreter option will cause the hole to be without small shining things that appear when Rayman approaches around this hole.

and here is a picture showing the original shape of the spiral door with the default Dynamic option:
https://imgur.com/izgdLNz
This is an image that shows its shape with the interpreter option :
https://imgur.com/8jj9v1Q

**Comment by m4xw** [comment]
Uhoh, need to talk with some folks over this

**Comment by m4xw** [comment]
https://github.com/mupen64plus/mupen64plus-core/pull/731
This PR apparently deals with interpreter issues.
As for dynarec, seems like a upstream Issue too, so if there isn't a issue yet, feel free to create one in the mupen core repo.
