### ISSUE TITLE
[RetroArch 32bit] Core fails to open after loading and unloading a couple of times

### ISSUE THREAD

**Issue by ds22x** [libretro/mupen64plus-libretro-nx#198]
On 32bit RetroArch, Mupen64Plus-Next fails to open after loading and unloading the core a couple of times, spitting out the following error:
`Failed to open libretro core: 
"/data/data/com.retroarch.ra32/cores/mupen64plus_next_libretro_android.so"
Error(s): dlopen failed: couldn't reserve 162271232 bytes of address space for "/data/data/com.retroarch.ra32/cores/mupen64plus_next_libretro_android.so"`

I can confirm it at least happens on Android, and that it doesn't happen on 64bit.

**Comment by m4xw** [comment]
I don't really support aarch32-adrnoid, you should be using aarch64.
seems it fails to address 32bit addrspace, probably a frontend issue?
Could happen if it doesnt properly unload it.

**Comment by ds22x** [comment]
Makes me wonder why it's even listed for 32bit to begin with.

**Comment by m4xw** [comment]
Because it works, i dont offer support for it tho.
This isn't a core issue.

**Comment by ds22x** [comment]
Okay.
Seeing as it isn't a core issue, it be best I open an issue at the Retroarch repository instead?
