### ISSUE TITLE
Legend of zelda Majora's mask crush

### ISSUE THREAD

**Issue by ioncretu123** [libretro/mupen64plus-libretro-nx#199]
I have played majoras mask with another phone and i have changed my phone and started playing again and i came to the part where i have to use my lens of truth(this issue wasnt on my other phone which is a worse phon by the way) and it appears that specifically when i use my lens of truth on the goron(the hero goron) the game starts losing frames and in a few seconds it crahes it appears that when i use my lens of truth on the ice steps where the owl first shows you the path it is worse, almost instan crush pls help

**Comment by m4xw** [comment]
Probably running out of vram, you can decrease Max texture cache size.
