### ISSUE TITLE
[Feature Request] Add Copy Aux Buffers to RDRAM

### ISSUE THREAD

**Issue by OtavioRaposo** [libretro/mupen64plus-libretro-nx#201]
Where's "Copy auxiliary color buffers to RDRAM" option for the GlideN64 plguin? I can't find it. It's necessary to avoid some graphical glitches in some games. Isn't it implemented to the core yet?

**Comment by m4xw** [comment]
Correct, can you name a few examples that aren't covered by the gliden ini?
If it's stated there it should apply.

**Comment by m4xw** [comment]
I can expose the option next release If you want (rebase branch)

**Comment by OtavioRaposo** [comment]
Paper Mario title and menu screen, for example, show garbage pixels and black lines without this option turned true.

Yes, please, expose the option.

**Comment by m4xw** [comment]
Good case, will do.

**Comment by m4xw** [comment]
Zelda dynarec issue and other projects take prio but I promise you this will be in the upcoming release.
will probably add it just before merge.

**Comment by OtavioRaposo** [comment]
I don't understand much how github works. Where can I check when the next release is available on Retroarch?

**Comment by m4xw** [comment]
d957ea7d248c720839f7adaf8c739eed3e0e6764
Rebase branch.

**Comment by m4xw** [comment]
[mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4745877/mupen64plus_next_libretro.zip)
Heres a Windows64 Build, give it a shot when u can.
