### ISSUE TITLE
Body Harvest stuttering / sync issue

### ISSUE THREAD

**Issue by daninthemix** [libretro/mupen64plus-libretro-nx#202]
Just started playing this, and it runs fine for about 10 minutes or so, then appears to lose 'sync' with constant stutter and frame-drops - and even if I save state and then load state, restarting Retroarch, the stutter remains. If I restart the game (but don't load state), it will run absolutely perfect for 5-10 minutes.

**Comment by daninthemix** [comment]
Where is this documented as an upstream issue? Is it a problem with mupen64plus or GlideN64?

**Comment by loganmc10** [comment]
You can try this build: https://m64p.github.io to confirm if it's an upstream issue. That build includes the latest mupen64plus-core and GLideN64
