### ISSUE TITLE
Star Fox 64 menus have no text

### ISSUE THREAD

**Issue by az0** [libretro/mupen64plus-libretro-nx#207]
The initial Star Fox 64 menu has no text.

On Ubuntu 20.04 with an Intel i5 CPU, I installed Retroarch 1.8.8 and mupen64plus-next 2.0.5 from a Ubuntu PPA.

Screenshot
![Screenshot from 2020-06-03 20-15-51 Starfox64 menu missing text](https://user-images.githubusercontent.com/933680/83708327-473eb680-a5d9-11ea-854f-fa5be4a3990d.png)

`retroarch --verbose` log 
[starfox64.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4727129/starfox64.log)

I am new to emulators, so please forgive me if I didn't file this issue correctly.

**Comment by m4xw** [comment]
Cursed iGPU `Intel(R) UHD Graphics 620`

**Comment by urmum-69** [comment]
How is this a valid response? 
What makes this specific gpu cursed?
I don't get it.

**Comment by m4xw** [comment]
I simply don't support iGPU, if he wants it fixed, he should tell that upstream.

**Comment by m4xw** [comment]
Also iGPU's have the worst drivers ever, hence the curse tag.

**Comment by az0** [comment]
Do you expect I would have better success with a Raspberry Pi 4, which has  a Broadcom VideoCore IV?

**Comment by m4xw** [comment]
Probably, yes.

**Comment by m4xw** [comment]
Tho for Rpi4 you should use mesa with GLES3

**Comment by otonoton** [comment]
This is an unacceptable response. Mupen must support iGPU properly. @twinaphex

**Comment by m4xw** [comment]
@otonoton I don't care, it's a case of not my beer.

**Comment by m4xw** [comment]
This tracker is only for issues I actually plan to work on, if you want it fixed, ask upstream to fix it or fix it yourself.
So stop spamming and get coding already.
There's a small chance that this is fixed on the rebase branch tho.

**Comment by otonoton** [comment]
Please stop harrassing your users. There is no need to act so high and mighty. It only makes yourself look worse.

**Comment by m4xw** [comment]
Then stop being a little entitled ass.

**Comment by m4xw** [comment]
@az0 If you still have questions feel free to contact me on Discord.

**Comment by m4xw** [comment]
@az0 Can you compile the rebase branch and see if the issue persists?
Another tester tried with uhd 620 and no issue there.

**Comment by az0** [comment]
Yes, the menu looks good with commit 328c430 from the rebase branch.
