### ISSUE TITLE
(Switch Version) Gauntlet Legends HUD elements blacked out

### ISSUE THREAD

**Issue by HappehLemons** [libretro/mupen64plus-libretro-nx#209]
Having an issue in the switch version that doesn't allow you to see your power bar, always causing it to be black. It should show a color depending on how much charge you have so you are able to use ultimate attacks.

On the hub screen you can almost see the color thru it because there's holes in that flicker it, but once you enter a level it turns completely black.  

Build f68044f

Doesn't happen on Windows 

![Inkedimage0 (1)_LI](https://user-images.githubusercontent.com/9768479/84440523-247b5600-ac08-11ea-9973-3129e2a5aae0.jpg)
![Inkedimage0 (2)_LI](https://user-images.githubusercontent.com/9768479/84440862-bc793f80-ac08-11ea-9371-2cfe0cc1bf68.jpg)

**Comment by m4xw** [comment]
Settings?

**Comment by HappehLemons** [comment]
Nothing changed - everything is on default from install. I did try changing many settings, but nothing effected this.

**Comment by m4xw** [comment]
I asked you to post them, so please do so.

**Comment by HappehLemons** [comment]
No problem, here's my most recent settings. 
mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "320x240"
mupen64plus-alt-map = "False"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "15"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Disabled"
mupen64plus-EnableShadersStorage = "False"
mupen64plus-EnableTextureCache = "False"
mupen64plus-ForceDisableExtraMem = "True"
mupen64plus-FrameDuping = "True"
mupen64plus-Framerate = "Fullspeed"
mupen64plus-FXAA = "0"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "4000"
mupen64plus-MultiSampling = "0"
mupen64plus-NoiseEmulation = "True"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-rsp-plugin = "hle"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

**Comment by m4xw** [comment]
`mupen64plus-EnableCopyColorToRDRAM = "Async"` try Sync
`mupen64plus-Framerate = "Fullspeed"` known to cause issues, it WILL break stuff in random games since it changes count per op
`mupen64plus-ForceDisableExtraMem = "True"` can break stuff depending on if the game uses expansion pak for some stuff
Also you really shouldnt use 320x240, its essentially not supported and forces nativeResFactor.
Use at least 640x420

`everything is on default from install`
Evidently wrong :P

**Comment by HappehLemons** [comment]
Sorry, maybe I should of clarified that everything WAS on default until I started changing settings reflected by that more recent config, but always seemed to give the same exact result.

This game chugs on switch even at full overclock, so bringing the res down and disabling the expansion pack (I believe this even causes lag on the N64) seemed to help performance. 

Sadly with all the reverts + changes I seem to be getting the exact same results. Here's a screenshot:
![image0 (3)](https://user-images.githubusercontent.com/9768479/84765043-a23eb900-af9c-11ea-97e4-f8e5a31aeed1.jpg)

**Comment by m4xw** [comment]
What about this build https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/jobs/8064/artifacts/raw/mupen64plus_next_libretro_libnx.nro

**Comment by HappehLemons** [comment]
Same result with that

**Comment by m4xw** [comment]
Weird af, makes no sense

**Comment by HappehLemons** [comment]
Yeh... Happen the same in Lakka too - not sure what the differences are in the way the cores are built but I can't seem to figure out how to get around this one.

**Comment by Papermanzero** [comment]
It is a known gliden64 issue
https://github.com/gonetz/GLideN64/issues/1647

**Comment by HappehLemons** [comment]
Weird. This doesn't happen on Gliden64 on PC, only on Mobile / Switch. I think this happens on Android as well, iOS has other issues making it impossible to see if this actually happens.

**Comment by HappehLemons** [comment]
https://www.youtube.com/watch?v=VhYfgTKubnc

Can confirm this happens on Android as well.

**Comment by m4xw** [comment]
Thanks for investigating, I might take a look but no promise.
As for now, I close it in favor of the upstream issue

**Comment by HappehLemons** [comment]
This was fixed with the newest update on switch and other devices as well.
