### ISSUE TITLE
Crashing Kodi everytime Libretro / Mupen64plus / Internet Game Archive Launcher IGAL

### ISSUE THREAD

**Issue by BullShark** [libretro/mupen64plus-libretro-nx#210]
### Describe the bug

Trying to launch any Nintendo 64 game from IAGL add-on in Kodi results in Kodi crashing.

## Expected Behavior

Launch the game in mupen64 emulator after downloading the game.

## Actual Behavior

Crashes Kodi with a seg fault

## Possible Fix

I suspect that the addons work without crashing Kodi in older versions of Kodi.

### To Reproduce
Here's the steps I took.

Install all of these using yay.

Install kodi-x11
Install kodi-addon-game-libretro
Install kodi-addon-game-libretro-mupen64plus

Download the IAGL zipfile

In Kodi:

Add the zipfile to get the repo.
Install IAGL from the new repo.
Install Nintendo 64 Controller
Nintendo - Nintendo 64 (Muphen64Plus)
Install IAGL - Internet Archive Game Launcher

In Kodi:

IAGL -> Browse All Lists -> Internet Archives Best Of N64 -> The Legend of Zelda - Ocarina of Time or 007

It seems to happen with every Nintendo 64 game.

Results:
Crashes Kodi every time.

```
$ kodi --debug
/usr/bin/kodi: line 219: 349385 Segmentation fault      (core dumped) ${KODI_BINARY} $SAVED_ARGS
Crash report available at /home/bullshark/kodi_crashlog-20200615_004443.log
```

Is the save file being opened before checking if it exists? And a save file is expected the first time a game is ran when there has been no saves.

> 2020-06-15 00:44:38.748 T:140704015163264   ERROR: Failed to open savestate file /home/bullshark/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/Legend of Zelda, The - Ocarina of Time (USA) (Rev B).sav
> kodi_crashlog-20200615_004443.log

Edit:

Here's another crash log after I installed gdb.
kodi_crashlog-20200615_005007.log

http://odin.root.sx/kodi_crashlog-20200615_005007.log

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Just before the crash:

![Screenshot_20200615_072724](https://user-images.githubusercontent.com/1526595/84657534-09476980-aeda-11ea-8d63-356ae3cb6bb2.png)

The crash happens immediately after the download for any N64 game.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment

Used Operating system:
Manjaro Linux with KDE latest.

```
$ uname -a
Linux plasma 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64 GNU/Linux
```

 - Operating system version/name:
 - Kodi version:

```
$ kodi --version
18.7 Git:20200603-nogitfound Media Center Kodi
Copyright (C) 2005-2020 Team Kodi - http://kodi.tv
$ pacman -Q | grep kodi
kodi 18.7.1-3
kodi-addon-game-libretro 1.1.1-5
kodi-addon-game-libretro-mupen64plus 2.5.0.6-14
kodi-addon-visualization-projectm 1:2.2.0-15
kodi-platform 20190726.809c5e9-10
kodi-x11 18.7.1-3
$ 
```

**Comment by m4xw** [comment]
No clue what Kodi is, but this isnt "libretro-mupen64plus".
Said core is dead and no longer supported.

**Comment by m4xw** [comment]
![image](https://user-images.githubusercontent.com/13141469/84659280-7af1d880-af17-11ea-91f7-ed930e075c55.png)
Also this looks like piracy, which i do not support in any capacity.

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/84715029-00d04c80-af35-11ea-8ff8-a5e890bf6402.png)
