### ISSUE TITLE
Banjo kazooi stutter

### ISSUE THREAD

**Issue by budtz** [libretro/mupen64plus-libretro-nx#214]
I have with every version getting strange stuttering in banjo. Its not there all the time and pc is running the emulator 100 percent at all times. 

Works fine in project 64 with gliden64

**Comment by m4xw** [comment]
Please provide more informations about your hardware, core options and attach a retroarch --verbose log

**Comment by budtz** [comment]
Hardware is Windows 10 pc 6 core CPU with rtx2070 gTX. Core options dont affekt it. Except the new threaded renderer option. With that on stutter goes away. GTX is set to Max power. Running the game almost uses no system resourses.
