### ISSUE TITLE
Build issues w/ gcc 10.1.0 & solution

### ISSUE THREAD

**Issue by gilmorem560** [libretro/mupen64plus-libretro-nx#220]
Seemed kinda trivial to go through the commit-pull-etc process but:

mupen64plus-core/src/device/r4300/idec.h:85: const char* g_r4300_opcodes[R4300_OPCODES_COUNT];
mupen64plus-core/src/main/workqueue.h:47: struct work_struct *work;

required extern via gcc 10.1.0. Compiles and runs fine now, just needed the push.

**Comment by m4xw** [comment]
Already fixed on `rebase` branch
