### ISSUE TITLE
All Mupen64Plus cores completely broken on Android

### ISSUE THREAD

**Issue by turboboy215** [libretro/mupen64plus-libretro-nx#223]
I went to try out the new ParaLLEl renderer for Mupen64Plus-Next on my Android phone, but now neither Mupen64Plus-Next or Mupen64Plus-Next GLES3 work at all, instead they all crash RetroArch when any content is loaded. They used to back when I had an earlier version of the core. Only the ParaLLEl core is functional now.

**Comment by m4xw** [comment]
Not enough Informations supplied.

**Comment by turboboy215** [comment]
What information do I need?

**Comment by m4xw** [comment]
Retroarch version, your phone name, os version, driver version, retroarch cfg, core options, last working version, everything you can name.
Crash report and verbose log are essential too.
it works on my S6 and we tested s10 and shield, that's about all I really support, I don't have access to other devices either

**Comment by turboboy215** [comment]
I am using RetroArch on a Pixel 3 on Android 10. I have tried with both OpenGLES and Vulkan, but neither work. I don't know the last working version, but it worked around February's version.
[retroarch__2020_06_27__12_52_15.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4841158/retroarch__2020_06_27__12_52_15.log)

**Comment by m4xw** [comment]
Your phone is missing required extensions as per log, manually edit the cfg and switch your plugin to GLideN64

**Comment by turboboy215** [comment]
I guess I'll have to just use the ParaLLEl core, then. It's weird, because I have a fairly high-end phone and that core works fine with the renderer, just not Mupen.

**Comment by m4xw** [comment]
It's probably not using parallel rdp then and falling back or smth.
it's only known to work on recent Mali and shield, not adreno
