### ISSUE TITLE
Parallel RDP plugin is not an option

### ISSUE THREAD

**Issue by Shoegzer** [libretro/mupen64plus-libretro-nx#224]
Using self-compiled project against commit 882719706aee4c8e470af90abd950b1c2420c8d6, parallel does not appear as an option under RDP plugins (only angrylion and gliden64).

One more reason to hate plugins!

Using linux mint 19.3, kernel 5.3 and gcc 9.3.0

**Comment by twinaphex** [comment]
Define HAVE_PARALLEL_RDP=1 HAVE_PARALLEL_RSP=1 HAVE_PARALLEL=1.

So,

make HAVE_PARALLEL_RDP=1 HAVE_PARALLEL_RSP=1 HAVE_PARALLEL=1

**Comment by Shoegzer** [comment]
Got it, makes sense @twinaphex.  I'm using the buildbot script with cores-linux-x64-generic which does not have these arguments, but adding them should fix it.  This file and corresponding files for other platforms will need to be modified for buildbot builds to automatically include the new plugin as well.
