### ISSUE TITLE
PAL games running at 60fps

### ISSUE THREAD

**Issue by 88hcsif** [libretro/mupen64plus-libretro-nx#225]
Premise: this might be a frontend issue.

I am running mupen64plus next with the [cloud-game](https://github.com/giongto35/cloud-game) frontend.
I am monitoring how often retro_video_refresh and retro_audio_sample_batch are being called.
I am playing a PAL version of Mario Kart 64 that reports to run at 50fps and a 44.1KHz sample rate.
On a macbook pro, retro_video_refresh is called around 60 times per second and the frontend receives around 53K samples per second through retro_audio_sample_batch.
On a raspberry pi instead, retro_video_refresh is called around 30 times per second and the frontend still receives around 53K samples per second through retro_audio_sample_batch.

If I play a Japanese version of Mario Kart 64 on the macbook pro, retro_video_refresh is still called around 60 times per second and the frontend receives the expected 44.1K samples per second through retro_audio_sample_batch.

Is there something that needs to be set on the frontend to run at 50fps?

**Comment by m4xw** [comment]
>I am playing a PAL version of Mario Kart 64 that reports to run at 50fps and a 44.1KHz sample rate.

That would be correct

>On a macbook pro, retro_video_refresh is called around 60 times per second and the frontend receives around 53K samples per second through retro_audio_sample_batch.

Means 60 VI/s means you grabbed a NTSC or MPAL ROM

>On a raspberry pi instead, retro_video_refresh is called around 30 times per second and the frontend still receives around 53K samples per second through retro_audio_sample_batch.

On raspberry we used to have onColorImageChange bufferswap which would be correct then, should be 60 on recent vers (assuming fbemu is on)

**Comment by 88hcsif** [comment]
Thanks for the reply.
I cannot reopen the issue but I am still having some problems.

I was finally able to run the game on Retroarch on the Pi.
And the same core with the same ROM runs at 25fps.
So I am pretty sure the ROM truly is PAL.
But I do not understand why I get 30VI/s when running with the other frontend on the Pi.

Do you roughly which part of the code takes care of limiting the framerate so that I can add some debug?

**Comment by m4xw** [comment]
>Do you know roughly which part of the code takes care of limiting the framerate so that I can add some debug?

None, by design of libretro this is done by the frontend.
Before the last release tho, like i said, it would correctly use a different buffer swap mode and report different values compared to now.

**Comment by 88hcsif** [comment]
Thanks!
All my assumptions were that the core is responsible for frame limiting and I wrongly thought that the Pi running at half speed corroborated this theory (I guess for the Pi retro_run is called twice as many times as retro_video_refresh because of the different buffer swap mode).
I then found the setting in the frontend that had been hardcoded to 60fps...

**Comment by m4xw** [comment]
Hah, a dead bug is a good bug
