### ISSUE TITLE
Upstream noPerspective Issue leads to black screen on the GLES2 variant on Android when a GLES3 context is supplied

### ISSUE THREAD

**Issue by Swordfish90** [libretro/mupen64plus-libretro-nx#227]
Hi,

let me start by thanking you for the time and effort you put into this libretro port. I've been using it perfectly for months, but since yesterday, I'm experiencing some issues with the GLES2 variant on Android.

I'm testing it on a Xiaomi 9t Pro (Snapdragon 855, Android 10) and GLES2 variant displays a mostly black screen with some weirdly colored boxes on every game (the GLES3 variant looks perfect). Audio and emulation are working fine. I'm able to reproduce the same issue both with Lemuroid and Retroarch.

Here you can find some logs: https://gist.github.com/Swordfish90/37d4c0b76e84320c9292984a39414d88

The Retroarch log doesn't seem very helpful, but on the Lemuroid logcat you can see many shader related errors which look like a very probable cause for the issue. The same error messages appeared on Logcat while running the core in Retroarch.

Let me know if I'm missing any info or you require some testing.

**Comment by m4xw** [comment]
Upstream issue but I will look into it

**Comment by m4xw** [comment]
m_part = "#version 100			\n";
			m_part +=
				"#if (__VERSION__ > 120)	\n"
				"# define IN in				\n"
				"# define OUT out			\n"
				"#else						\n"
				"# define IN attribute		\n"
				"# define OUT varying		\n"
				"#endif // __VERSION		\n"
				;
		}
Your device isn't providing a GLES2 context, so GLES2 won't work for you.

**Comment by m4xw** [comment]
I will try to figure something out to not make it crash tho

**Comment by m4xw** [comment]
I just tried and it Def. Works on my phone, the error you posted sounds reasonable tho and others say it worked before.
I will investigate more but if I can't repro then I can't do much.
I will reopen the issue as requires, your logs have been helpful to say the least

**Comment by Swordfish90** [comment]
Thank you for taking a look into it. It's good news that it looks device specific, I'll update Lemuroid to use the GLES3 variant on supported devices (something that probably makes sense anyway). And just for the sake of investigating it a bit, I'll try to dive into the code in the next days and I'll let you know if I come up with something.

> I will try to figure something out to not make it crash tho
That's not needed, the application doesn't crash, it just displays mostly black textures (sound and emulation are working fine).

Thanks again for your investigation!

**Comment by m4xw** [comment]
Somewhere down the line I will unify the builds, it's currently not possible tho because glsm.c needs compile-time configuration currently.

**Comment by Swordfish90** [comment]
So, I did a bit of digging and the issue is definitely in GLideN64/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp

```
if (!_glinfo.isGLESX || _glinfo.noPerspective)
    m_part += "noperspective OUT lowp vec4 vShadeColorNoperspective;\n";
else
    m_part += "OUT lowp vec4 vShadeColorNoperspective;                              \n";

```

Forcing it to take the second branch (in every place in that file) seems to fix the broken shaders. My guess is that the extension doesn't work on OpenGLES2 ([NV_shader_noperspective_interpolation](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_noperspective_interpolation.txt)), but probably some drivers are a bit more forgiving than mine.

**Comment by m4xw** [comment]
I get flashbacks https://github.com/gonetz/GLideN64/issues/2181

**Comment by m4xw** [comment]
super helpful btw, thanks

**Comment by m4xw** [comment]
Tho I guess upstream issue is a bit missleading since under their circumstances it would just use GLES3, hence I added a mitigate tag since it should be easy for now, wonder if that causes some shenanigans on ios too @weedyweedsmoker
Try setting it to `False` in glinfo cpp?

**Comment by m4xw** [comment]
[arm64-v8a.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4917776/arm64-v8a.zip) Potential fix, untested

**Comment by WeedyWeedSmoker** [comment]
@m4xw Can I get the source code (or the required modifications and branch infos) for this build?

_It's compiled for Android right now, iOS uses .dylib, not .so file format for cores…_

**Comment by m4xw** [comment]
Oh would be nice if u can test it on IOS, I asked my other tester for that but he isnt around.
Generally you can find every experimental change, if not here, on my gitlab https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/-/commit/4c4551448d43ec73988a5b9127dc3ed35655e1cb

**Comment by m4xw** [comment]
Dont forget u probably want to nuke your shaders folder ;)

**Comment by WeedyWeedSmoker** [comment]
@m4xw Ok, I tried compiling straight from the "Behaviour test 4c4551448d43ec73988a5b9127dc3ed35655e1cb" commit, and compiling with GLES2, but in both cases the black textures issue is still present…

**Comment by m4xw** [comment]
@WeedyWeedSmoker what is your max texture cache size set to?
Try 4000 if u havent already

**Comment by m4xw** [comment]
@WeedyWeedSmoker 
![image](https://user-images.githubusercontent.com/13141469/87417660-d07ddb80-c5d0-11ea-958f-5b104f0624c5.png)
Try changing retro_run in libretro.c like this and give it a shot.
If that "fixes" it, it would be a GL state issue.

**Comment by WeedyWeedSmoker** [comment]
Is it `video_cb(RETRO_HW_FRAME_BUFFER_VALID, retro_screen_width, retro_screen_height)`? (your image is cut…)

**Comment by m4xw** [comment]
Just check the gliden codepath right there

```c

    if (libretro_swap_buffer)
    {
       if(current_rdp_type == RDP_PLUGIN_GLIDEN64)
       {
          video_cb(RETRO_HW_FRAME_BUFFER_VALID, retro_screen_width, retro_screen_height, 0);
       }
```

**Comment by WeedyWeedSmoker** [comment]
@m4xw This change made the whole screen black (even the overlayed contols)…

**Comment by m4xw** [comment]
Show me the change u made

**Comment by WeedyWeedSmoker** [comment]
<img width="714" alt="Capture d’écran 2020-07-14 à 18 10 31" src="https://user-images.githubusercontent.com/26014958/87419236-59ab0780-c5fd-11ea-90bf-7f22c9ea49ea.png">

**Comment by m4xw** [comment]
oh try libretro_swap_buffer = false before co_switch(game_thread)

**Comment by m4xw** [comment]
If that doesnt work either, try commenting glsm_ctl bind out

**Comment by WeedyWeedSmoker** [comment]
@m4xw 
```
    libretro_swap_buffer = false;
    co_switch(game_thread);
```
Glitches the screen to flicker black like before, but this time only in a rectangular shape at the bottom left, not on the whole screen…

Then eventually the whole screen turns black and I can only hear sound, press the invisible overlayed buttons, then get a crash…

**Comment by m4xw** [comment]
So what if you kill the context binds?

**Comment by WeedyWeedSmoker** [comment]
@m4xw 

```
       //glsm_ctl(GLSM_CTL_STATE_BIND, NULL);
    }

while(true)
{
    co_switch(game_thread);
    
    if (libretro_swap_buffer)
    {
        if(current_rdp_type == RDP_PLUGIN_GLIDEN64)
        {
           video_cb(RETRO_HW_FRAME_BUFFER_VALID, retro_screen_width, retro_screen_height, 0);
        }
    }
    poll_cb();
}
```

With this instead, black screen, can't press the invisible overlay buttons anymore…

**Comment by m4xw** [comment]
Is that with thr renderer on or off?

**Comment by WeedyWeedSmoker** [comment]
@m4xw Threaded renderer off…

**Comment by m4xw** [comment]
@WeedyWeedSmoker I went through some of the changes compared to jet's fork, try adding -DGL_USE_DLSYM to cflags and do a clean build.
If that doesnt help i have another change to try.
Make sure u revert the stuff from earlier.

**Comment by m4xw** [comment]
U might need to add `#include <dlfcn.h>` at the top of glfunctions.cpp tho

**Comment by WeedyWeedSmoker** [comment]
Adding `-DGL_USE_DLSYM` there in Makefile:
```
ifeq ($(platform),ios-arm64)
		WITH_DYNAREC=
		GLES=1
		GLES3=1
		FORCE_GLES3=1
		EGL := 0
		PLATCFLAGS += -DHAVE_POSIX_MEMALIGN -DNO_ASM -DGL_USE_DLSYM
```
and `#include <dlfcn.h>` at the top of glfunctions.cpp

still have the black textures issue…

Do I need to add `-DGL_USE_DLSYM` somewhere else?

**Comment by m4xw** [comment]
Ok try changing in GLFunctions.cpp:
```c
	ASSIGN_PROC_ADR(PFNGLDISABLEPROC, Disable);
	ASSIGN_PROC_ADR(PFNGLENABLEPROC, Enable);
```
to
```c
	GL_GET_PROC_ADR(PFNGLDISABLEPROC, Disable);
	GL_GET_PROC_ADR(PFNGLENABLEPROC, Enable);
```
and in GLFunctions.h:
```c
#define glDisable(T) opengl::FunctionWrapper::wrDisable(S##T)
#define glEnable(T) opengl::FunctionWrapper::wrEnable(S##T)
```
to
```c
#define glDisable(...) opengl::FunctionWrapper::wrDisable(__VA_ARGS__)
#define glEnable(...) opengl::FunctionWrapper::wrEnable(__VA_ARGS__)
```
Clean build, keep the dlfcn changes

**Comment by WeedyWeedSmoker** [comment]
@m4xw Still has the black textures issue, but now the image (and overlay) is cropped to a small rectangle at the bottom left of the screen…

**Comment by m4xw** [comment]
Yea makes sense that it breaks something else, but that ruled out a bunch of things

**Comment by m4xw** [comment]
@WeedyWeedSmoker can u get me a full compilation log, i want to look for warnings

**Comment by m4xw** [comment]
Also, what happens with LOD Emu off?

**Comment by WeedyWeedSmoker** [comment]
@m4xw Sorry I wasn't home… LOD emu was off the whole time!

Here is the full compilation log straight off the "Behaviour test 4c4551448d43ec73988a5b9127dc3ed35655e1cb" commit: https://pastebin.com/20uvb4SM

**Comment by m4xw** [comment]
What if you turn lod emu on?

**Comment by WeedyWeedSmoker** [comment]
@m4xw I originally turned off LOD emu for another black textures issue with Conker's Bad Fur Day, but I just tried turning it on again, and it still has the black textures issue _(that seem unrelated to the Conker's one)_…

**Comment by m4xw** [comment]
If you mean the black rectangle in cbfd, thats one of the fbemu options

**Comment by WeedyWeedSmoker** [comment]
@m4xw I mean in CBFD, Conker has a black patch on his head with @jet082's fork with LOD on, and some other textures have black issues too… Solved by turning LOD emu off for this game…

**Comment by m4xw** [comment]
Thats the first time i hear of smth like that, so sounds like other ios specific shenangians.

**Comment by WeedyWeedSmoker** [comment]
LOD on:
![IMG_0503](https://user-images.githubusercontent.com/26014958/87448186-aefb0f00-c625-11ea-8acf-d5dcfef1c128.jpg)

LOD off:
![IMG_0502](https://user-images.githubusercontent.com/26014958/87448205-b6bab380-c625-11ea-817d-a5064ffb1a71.jpg)

**Comment by WeedyWeedSmoker** [comment]
@m4xw BTW, CBFD is completely f'd up on the "Behaviour test 4c4551448d43ec73988a5b9127dc3ed35655e1cb" commit (now that I tried it)…

All 3D is offset to the left:
![1](https://user-images.githubusercontent.com/26014958/87451307-e8357e00-c629-11ea-95ba-bd152edef2ca.jpg)
![2](https://user-images.githubusercontent.com/26014958/87451325-ee2b5f00-c629-11ea-97af-ce8b42a48803.jpg)
![3](https://user-images.githubusercontent.com/26014958/87451336-f1bee600-c629-11ea-8db3-5c0a122355d8.jpg)
![4](https://user-images.githubusercontent.com/26014958/87451349-f5526d00-c629-11ea-9237-9e44eb9a7731.jpg)

Other games I've tested do not exhibit this behavior…

**Comment by Swordfish90** [comment]
Hi @m4xw . Thank you very much!

I just tried your so file and it works perfectly. Just to make sure I also tried to build my local copy with your changes and it works too, so I guess the fix is the right one!

I guess we can close at least the Android issue.

**Comment by m4xw** [comment]
> 
> 
> @m4xw BTW, CBFD is completely f'd up on the "Behaviour test 4c4551448d43ec73988a5b9127dc3ed35655e1cb" commit (now that I tried it)…
> 
> All 3D is offset to the left:
> ![1](https://user-images.githubusercontent.com/26014958/87451307-e8357e00-c629-11ea-95ba-bd152edef2ca.jpg)
> ![2](https://user-images.githubusercontent.com/26014958/87451325-ee2b5f00-c629-11ea-97af-ce8b42a48803.jpg)
> ![3](https://user-images.githubusercontent.com/26014958/87451336-f1bee600-c629-11ea-8db3-5c0a122355d8.jpg)
> ![4](https://user-images.githubusercontent.com/26014958/87451349-f5526d00-c629-11ea-9237-9e44eb9a7731.jpg)
> 
> Other games I've tested do not exhibit this behavior…

The change shouldn't impact this. GLES2 or 3?




> 
> 
> Hi @m4xw . Thank you very much!
> 
> I just tried your so file and it works perfectly. Just to make sure I also tried to build my local copy with your changes and it works too, so I guess the fix is the right one!
> 
> I guess we can close at least the Android issue.

Another tester: ```
. LoZ OoT looks okay, Mario64 looks a little fucky with a bunch of weird repeated graphics, but it's better than a black screen!
also, mario's head looks super specular
```

**Comment by WeedyWeedSmoker** [comment]
@m4xw GLES3…

**Comment by m4xw** [comment]
@Swordfish90 btw i still have a few things to check before i push this to develop, sorry that this takes so long, have been pretty busy and burned out.

**Comment by Swordfish90** [comment]
@m4xw Take all the time you need and don't sweat it. These are open source contributions done in your spare time, so feel free to work at your pace and if you need help on anything just let me know.

**Comment by m4xw** [comment]
622568ee6dc2967fff8107858f0c9a7f2a30c411

**Comment by m4xw** [comment]
I might re-open if any issue arises tho.
