### ISSUE TITLE
Killer Instinct Gold Framerate/Graphical glitches.

### ISSUE THREAD

**Issue by cobhc2019** [libretro/mupen64plus-libretro-nx#228]
Hi,

Using parallel causes the framerate during actual gameplay to drop to what seems like 30fps even though the v/i still shows 60fps. Switching to Glide fixes it.

I've also realised that the character portraits (even using Parallel) have visible lines between the tiles, the same as Mario Kart 64 does with Glide.

**Comment by m4xw** [comment]
Wrong core wrong repo.
There is no Glide in next

**Comment by cobhc2019** [comment]
Can you point me in the right direction to report this for Mupen64Plus-Next then please?

**Comment by m4xw** [comment]
This is -next but you said it works with Glide, I don't have glide in mupen64plus-next.
Thus you probably search for https://github.com/libretro/parallel-n64/

**Comment by cobhc2019** [comment]
I'm confused, the default option for the libretro core Mupen64Plus-Next for the the RDP plugin is GlideN64 and you mention GlideN64 in your blog post regarding version 2.1 of Mupen64Plus-Next.

**Comment by m4xw** [comment]
You said glide tho (yes glide is a thing and different from GLideN64)

**Comment by m4xw** [comment]
So: You can try changing vsync in RA, also make sure you don't have rewind or runahead enabled.

**Comment by m4xw** [comment]
Let me know if that worked

**Comment by cobhc2019** [comment]
Apologies for not making that distinction. I'll give that a go and let you know, thank you.

**Comment by m4xw** [comment]
You may report parallel rdp specific rendering issues here https://github.com/Themaister/parallel-rdp/issues

**Comment by cobhc2019** [comment]
Okay, V-Sync on or off makes no difference and I don't have either runahead nor rewind enabled. Standalone ParaLLEl N64 doesn't have the framerate issue as I've just tried them both back to back.

Regarding the character glitches, please see attached screenshot. This also happens on the character select screen.

**Comment by m4xw** [comment]
>I've also realised that the character portraits (even using Parallel) have visible lines between the tiles, the same as Mario Kart 64 does with Glide.
>Regarding the character glitches, please see attached screenshot. This also happens on the character select screen. You can see horizontal lines through the character.

This is **not** a -next issue, it's up to the corresponding plugins.
Sometimes its not avoidable when upscaling.

>Okay, V-Sync on or off makes no difference and I don't have either runahead nor rewind enabled. Standalone ParaLLEl N64 doesn't have the framerate issue as I've just tried them both back to back.

If it reports 60 vi/s then it sends 60 vi/s, so its a frontend issue of some kind, usually happens with runahead or rewind, but also not a -next issue.

**Comment by cobhc2019** [comment]
Okay, please leave this issue closed then.

**Comment by m4xw** [comment]
When using parallel, did you manually switch the driver to vulkan?

**Comment by m4xw** [comment]
Ah, also make sure you dont use GPU Hard sync or stuff like gsync or the likes.
