### ISSUE TITLE
F1 Pole Position 64 Graphic problems.

### ISSUE THREAD

**Issue by ToniBC** [libretro/mupen64plus-libretro-nx#229]
Hello, using the GlineN64 Plugin and RSP in HLE, even changing options, I cannot get the game to play correctly in the clouds, seeing some effects as seen in the capture. The updated core and retroarch, all at nightly. Default or modified values.

![F1 Pole Position 64 (USA) (En,Fr,De)-200630-213306](https://user-images.githubusercontent.com/45365478/86169622-36bb2680-bb1a-11ea-8ad4-4d250517081f.png)

With the same graphic plugin, in Project64 this effect does not occur.
And I've tried several combinations, but I can't fix this error.

Thank you.

**Comment by m4xw** [comment]
Can you show me with parallel rdp?

**Comment by ToniBC** [comment]
With Parallel (Vulkan) and RDP (Parallel) and resolution x4.

![F1 Pole Position 64 (USA) (En,Fr,De)-200630-231238](https://user-images.githubusercontent.com/45365478/86177714-66246000-bb27-11ea-87ee-418fd60f56e7.png)

**Comment by m4xw** [comment]
Can you try with a build from his CI? https://ci.appveyor.com/project/gonetz/gliden64/builds/33782646/artifacts
On any standalone

**Comment by ToniBC** [comment]
It does not fail as I mentioned.

![F1 Pole Position Test 1](https://user-images.githubusercontent.com/45365478/86187583-6844e980-bb3c-11ea-8336-ab6d9857ef78.png)
![F1 Pole Position Test 2](https://user-images.githubusercontent.com/45365478/86187589-6c710700-bb3c-11ea-8aa0-eca8ef13ed48.png)

**Comment by m4xw** [comment]
Interesting, does it happen with LLE RSP too + GLideN64?

**Comment by ToniBC** [comment]
Solved, after trying multiple settings and trying to fix other problems of other games, I found the solution.

Activating Native res. 2D texrects in Optimized (I think it's the best) or in non-optimized, that error and some others are fixed.

So I close the error for not being an error as such.

**Comment by m4xw** [comment]
Still weird, is this a case of different defaults?
Or did you change it as some point?

**Comment by ToniBC** [comment]
With the default values it fails, you have to modify that option to make it work in the game.
