### ISSUE TITLE
GCC 10 build failure

### ISSUE THREAD

**Issue by alucryd** [libretro/mupen64plus-libretro-nx#230]
Hi there, the latest commit fails to build with GCC 10: https://buildbot.alucryd.xyz/#/builders/265/builds/8

GCC 10 is known to cause issues about everywhere, hopefully this is easy to fix.

**Comment by m4xw** [comment]
You are building f68044fe275ef49ea142a304af873aa08aca78a3 which is last develop/current master.
Keep in mind `master` is last-stable-ver and you should be shipping the develop branch here.

**Comment by m4xw** [comment]
Happened to bump master just now, in case you want to use it from now on.

**Comment by alucryd** [comment]
Thanks! master is built automatically on my buildbot, I'll be able to push the package to the arch repositories then.

**Comment by m4xw** [comment]
Sure, I just assumed you switched to develop, since thats my equivalent of other people's master, while my master is rather "stable" and thus often lags behind :P
