### ISSUE TITLE
mupen64plus-next 2.1: screen not fully filled on pi 4.

### ISSUE THREAD

**Issue by akamming** [libretro/mupen64plus-libretro-nx#231]
Hi,

I am quite new here. so if I step  on any toes by reporting this issue here, just let me know. I already posted on the retropie forum, but did not get respons. I also think this is a better place to report, cause it seems to be an issue in this core as far as I can see..

First of all my compliments for the great work and the time you developers put into this core! 

My situation:
I made a self built arcade cabinet running retropie latest version (currently 4.6.4) on a raspberry pi 4. All OS components are also updated to latest versions.  i was using the "normal" mupen64plus because the libretro cause was not fast enough on 640x480 on most games, but i really want to switch to a libretro version because of the ability to use overlays.

I was very happy to see the 2.1 update (compiled using the retropie setup script: Install from source) of this core and i am also very happy to see the speed has increased and almost all games are very well playable now on 640x480 on my pi4. big improvement. Good work developers!

Unfortunately there still is an issue with the image on a lot of games: 

The screen is not fully filled  and there is garbage on the lower part of the screen, see screenshot. a lot of games (like 1080 snowboarding, mario kart, cruis'n world) have this issue.  but some games (like Ridge Racer 64) are fine

![probleemnintendo-klein](https://user-images.githubusercontent.com/30364409/86720019-e87bbb00-c024-11ea-9208-0ce842bc309a.jpg)

i checked: on 2.0 (checked on another pi4 with the same setup), the "normal" mupen64plus and on 2.1 on a x64 debian laptop i don't have this issue, so it seems to specific for the combi  of the libretro 2.1 version on a pi 4.

hope you can fix this!  I would really like to use this emulator core.  Let me know if i can do anything to help solve this issue!

Kind Regards
Arnold

**Comment by dankcushions** [comment]
can you provide the configs you are using to achieve overlays? and the .cfg settings for aspect ratio, viewport, etc. what is the interger_scaling setting?

**Comment by akamming** [comment]
> can you provide the configs you are using to achieve overlays? and the .cfg settings for aspect ratio, viewport, etc. what is the interger_scaling setting?

Tx for having a look!

see attached .zip

[configs.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/4883672/configs.zip)


- I have the  issue  with and without overlays.  to make sure the overlay's arent the problems i also ran with retroarch.cfg.rp-dist. Same issue (without overlays).
- in the zip is my current config.  (retroarch.cfg, but also the retroarch.cfg.rp-dist which i also tested)
- I tried several aspect ratio's (4:3, custom, 16:9, etc...) 
- i tried several resolutions (640x480,320x240,960x720)
- i tried gl and glcore video driver 
(and to be sure restarted after every changed setting to make sure it's effective)
 
Where can i find the integer_scaling setting?

**Comment by dankcushions** [comment]
thank you. if this is a retropie setup, as it appears from the reference to rp-dist, i think you need to start from a vanilla setup. there are lots of things weird about your configs. eg:

```
custom_viewport_height = "240"
custom_viewport_width = "320"
custom_viewport_x = "200"
custom_viewport_y = "80"
```
why have you done this?

i would start from vanilla. ie, the default retroarch.cfg.rp-dist (or other /configs/all/retroarch.cfg and /configs/n64/retroarch.cfg), no overlay, no core overrides, no overlays, custom display resolution removed in runcommand (leave at default).

once you have done that, please provide all .cfgs, and where they are located, a verbose log, and a screenshot of the issue on a well-tested game like mario 64.

this probably should be solved on the retropie forums, also. it's a configuration issue - no bug.

**Comment by m4xw** [comment]
No bug is what I wanna hear, gonna trust you on that.
feel free to reopen if issues persist, I thought by the pic this was maybe overscan not cleared right or simliar

**Comment by akamming** [comment]
> thank you. if this is a retropie setup, as it appears from the reference to rp-dist, i think you need to start from a vanilla setup. there are lots of things weird about your configs. eg:
> custom_viewport_height = "240"
> custom_viewport_width = "320"
> custom_viewport_x = "200"
> custom_viewport_y = "80"
> 
> why have you done this?


--> I did not configure this myself, the only reason this could have happend i think is that this was done by the bezelproject scripts. in the previous version i ran at 320x200 because of speed. and that was when i ran the setup script for the bezelproject. i did not configure this manually.  

> i would start from vanilla. ie, the default retroarch.cfg.rp-dist (for both /configs/all/retroarch.cfg and /configs/n64/retroarch.cfg), no overlay, no core overrides, no overlays, custom display resolution removed in runcommand (leave at default).

--> bringing back all config files to .rp-dist is what  i already tested (that's why I also provided the .cfg. rp-dist file with that file the same issue) still had that issue.
--> Based on your remark several weird things in my config (and the fact that i have a spare sd card) i will do a some more testing and revert all kinds of stuff on the system to see if it has effect.  If i find the config setting which causes this effect. Would you be interested to know which setting it is?

> once you have done that, please provide all .cfgs, and where they are located, a verbose log, and a screenshot of the issue on a well-tested game like mario 64.

--> Yep will do that if the problem persists.

> this probably should be solved on the retropie forums, also. it's a configuration issue - no bug.
--> Ok clear message. Is this also the case if i can reproduce on a vanilla retropie install? 

tx for taking the time to look at my issue!

**Comment by dankcushions** [comment]
i think all issues with retropie should be addressed in their forum in the first instance. if an issue is discovered with vanilla retropie (No bezel project, no changed resolution settings, etc), we can consider raising it here, but anything that appears after several stages of configuration (bezel project, custom settings, etc) should not be considered a bug with this core - it could possibly be a retroarch bug, but i don't really have enough info to guess.

**Comment by akamming** [comment]
ok clear…  i was really under the impression that this was a bug and wanted to give the info directly to the developers. so that's why i mentioned it here.  but you were right. It was a config issue. Uninstalling the bezelproject did the trick.  

I will only report issues here if i can reproduce vanilla….

tx for the help! and keep up the good work! 2.1 is a big step forward. I very much appreciate all the work the developers put into this!!

**Comment by akamming** [comment]
i found the responsible setting: Somehow framebuffer emulation was disabled in the settings, which causes this issue.  reproduced on a vanilla retropie on another rpi4.

**Comment by m4xw** [comment]
Yea that's expected to break things, but it has huge performance issues on platforms like rpi.

**Comment by dankcushions** [comment]
nonetheless, we default it on for retropie on mupen64plus standalone, since the compatibility issues are too great without: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/mupen64plus.sh#L268

i've noticed that there is some logic in nx that defaults FBE off for VC (retropie 0-3, when not running the mesa driver): https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/libretro/libretro_core_options.h#L277 - i guess i would disagree with this for the same reason. it's been default on for ages in retropie for standalone.

**Comment by m4xw** [comment]
@akamming 1. Did the garbage in the background move? 2. Is it GLES2 or GLES3
I fixed a simliar issue just recently for GLES3 android and wonder if thats actually the same cause.
Also can you show me how its supposed to look like with fbemu on your device?

**Comment by m4xw** [comment]
That fbemu off breaks in this specific way has been bugging me for a while

**Comment by akamming** [comment]
> 1. Did the garbage in the background move? 

No, it not moving. To me it looks like that FBemu is off, there is an alignment problem. Some things are drawn too far up the screen and other to far down. Cause games start with start screen not aligned in the center anymore. Then some things are drawn too low (mostly 2d) and then they are never removed anymore, leaving parts of these objects as "garbage" on the lower field. In some cases when the screen switches frm 2d to 3d this is corrected again, but then also the 3d part is drawn on the overscan parts of lower part of the screen. See screenshots below.

> 2. Is it GLES2 or GLES3. I fixed a simliar issue just recently for GLES3 android and wonder if thats actually the same cause.

How can i find out? 

> Also can you show me how its supposed to look like with fbemu on your device?
Here are a few screenshots from 2 games with and without FB. Every time you see with FB Emu off things are vertically aligned misaligned. (and sorry it's not vanilla. I just reused that SD card for something else. I already noticed the same behaviour on a vanilla  retropie image, so it should not make a difference)

Cruis'n world startscreen, with FB Emu off
![Cruis'n world startscreen FB Emu on](https://user-images.githubusercontent.com/30364409/86947284-dc3e4d80-c14b-11ea-999e-facd9980b739.jpg)
Same screen with FB Emu on:
![Cruis'n world startscreen FB Emu off](https://user-images.githubusercontent.com/30364409/86947282-dba5b700-c14b-11ea-8fb0-06950f82a6ac.jpg)
(Screen too much to the top)

Cruis'n World Track select screen with FB Emu on:
![CW-trackselect-CWon](https://user-images.githubusercontent.com/30364409/86947287-dd6f7a80-c14b-11ea-8c1f-1a4de7cf70af.jpg)
Same screen with FB Emu on:
![CW-trackselect-CWoff](https://user-images.githubusercontent.com/30364409/86947285-dd6f7a80-c14b-11ea-89af-faf038d12ef9.jpg)
(Screen too much too the top with the remains of objects drawn to far down, as garbage in the lower part)

Mario Kart In game screen FB Emu on:
![mk-ingame-FBon](https://user-images.githubusercontent.com/30364409/86947293-dea0a780-c14b-11ea-96f3-f1b56c12f5c3.jpg)
Same screen with FB Emu off:
![MK-Ingame-FBOFF](https://user-images.githubusercontent.com/30364409/86947291-dea0a780-c14b-11ea-9f22-6abe7384b4c3.jpg)
(black bar drawn too far up, text drawn too far down)

Mario Kart start screen with FB Emu on:
![MK-start-FBon](https://user-images.githubusercontent.com/30364409/86947297-dfd1d480-c14b-11ea-8a0e-5a4de52a161b.jpg)
Same screen with FB Emu off
![MK-start-FBoff](https://user-images.githubusercontent.com/30364409/86947295-df393e00-c14b-11ea-9902-35c3359d16ce.jpg)
(screen drawn too far up)

Cruis'n World in game with FB Emu on:
![CW-ingame-FBon](https://user-images.githubusercontent.com/30364409/86947300-e06a6b00-c14b-11ea-85ea-26ad5c05c88d.jpg)
Same screen with FB Emu off:
![CW-ingame-FBoff](https://user-images.githubusercontent.com/30364409/86947299-dfd1d480-c14b-11ea-8dc9-7ef06e250024.jpg)
(black bars below "MPH" and "AUTO", in window on the right where you can see the turns in 2d. The rectangle is drawn too high and or the road too low)

**Comment by m4xw** [comment]
OK so when fbemu is off overscan won't work and it will just align it at the top while also not clearing the background.

There's never artifacts on the sides?
If so it's probably some oversight.

**Comment by m4xw** [comment]
Same thing with overscan explicitly disabled btw?

**Comment by akamming** [comment]
> OK so when fbemu is off overscan won't work and it will just align it at the top while also not clearing the background.

This is ofcourse your area of expertise. But i personally think is both alignment at the top AND the bottom. Cause some objects are aligned from the top, which are then too far up the screen, other too low and are drawn too far down the screen, also on overwriting the lower overscan area.

>There's never artifacts on the sides?

haven't seen them 

>Same thing with overscan explicitly disabled btw?

These are the vanilla overscan settings (and which were used to create the screenshots:)
mupen64plus-next-EnableOverscan = "Enabled"
mupen64plus-next-OverscanBottom = "0"
mupen64plus-next-OverscanLeft = "0"
mupen64plus-next-OverscanRight = "0"
mupen64plus-next-OverscanTop = "0"

I just tested with, and had the exact same results with these settings:
mupen64plus-next-EnableOverscan = "Disabled"
mupen64plus-next-OverscanBottom = "0"
mupen64plus-next-OverscanLeft = "0"
mupen64plus-next-OverscanRight = "0"
mupen64plus-next-OverscanTop = "0"

based on your GLES3 remark and i just found out how to compile the core myself, i just compiled with GLES2. It has the same issue, but just a bit more, see this example:
![MK-startscreen-FBoff-GLES2](https://user-images.githubusercontent.com/30364409/86956915-2f1f0180-c15a-11ea-84ab-b98ece453ece.jpg)

**Comment by akamming** [comment]
Sorry to bother again. I know this is not considered as an issue, but an expected incompatibility when this is switched off.

However if we could "fix" it, we would make a lot of RPI users happy because of the big performance hit on RPI for FBEMU. So i'm willing to spend some time on it to try to fix it myself. I used to be a C programmer several years ago, and therefor my programming skills are a bit rusty, so hopefully you can give me some startup help

I compared the FB Emu on with FB Emu off in a lot of games and always notice the same pattern :

In the normal (FBEMU on situation). The screen is built up like this:
![image](https://user-images.githubusercontent.com/30364409/87128327-b8842000-c28f-11ea-9b8a-62e392a6f258.png)

however when fbemu is switched off i notice this:
1. There are no objects correctly vertically aligned. They are drawn either too far up or down 
2. Horizontal alignment is always correct.
3.  When objects are drawn too high up the screen, the shift up is always the same distance: The delta between Top and Virtual Top. So probably aligned to top instead of virtual top.
4. When objects are drawn too far down the screen ,the shift is also always the same distance: The delta between Bottom and Virtual bottom. So probably aligned to bottom instead of virtual bottom
5. There is one exception: If a screen in a game has no overscan (e.g. a lot of screens in Ridge Racer 64). The alignment issue is gone. This is expected if my assumptions for point 3 and 4 up above are correct: Top and virtual top (and bottom and virtual bottom) are the same, do it does not matter  if Y is derived from Top or virtual top (or bottom or virtual bottom), 

So based on this my working assumption is that somewhere a bug in the code causing the when FB is off, the absolute Y for start drawing of objects is calculated from the top or bottom, where it should use the virtual top or bottom. 

as stated i'm willing to dive into the code myself to see where it goes wrong, but it would save me a lot of time if someone can point me in the direction where i have to look (it is a lot of code ;-)), so hope you can help me with this… I'm looking for
- the places in the code where screenheight is calculated
- the places in the code where overscan Y and X are calculated
- the places in the code where actual Y and X are calculated
- the places in the code where the actual drawing of the objects screen takes place
- Where the code splits in to FB Emu on and FB Emu off 
etc...

can you give me some help here?

**Comment by dankcushions** [comment]
Does the same issue manifest on standalone mupen64plus-GLideN64?

**Comment by akamming** [comment]
Good question. Just checked, the anwser is yes:

![image](https://user-images.githubusercontent.com/30364409/87137299-f3d91b80-c29c-11ea-91c8-ada337b8d7ee.png)

**Comment by dankcushions** [comment]
Interesting! That at least puts the issue somewhere in upstream GLideN64's VI emulation code. Perhaps it should be logged there? https://github.com/gonetz/GLideN64/issues (although @m4xw may still want to investigate it here also). I would presume once a centralised image is sent in upstream, it will also fix the issue in this core.

My apologies for presuming this wasn't a bug, btw! It sounds like it is, albeit with upstream GLideN64.

**Comment by akamming** [comment]
> That at least puts the issue somewhere in upstream GLideN64's VI emulation code. Perhaps it should be logged there? 

https://github.com/gonetz/GLideN64/issues (although @m4xw may still want to investigate it here also). I would presume once a centralised image is sent in upstream, it will also fix the issue in this core.

what do you mean by VI emulation code? do you refer to the video chip of the pi 4?  i think the issue is broader. I just reproduced the same issue on a retropie installed on my dell laptop (on old dell latitude E6320 with the latest debian)…

> My apologies for presuming this wasn't a bug, btw! It sounds like it is, albeit with upstream GLideN64.

no worries… you made a fair point...

**Comment by m4xw** [comment]
> 
> 
> Good question. Just checked, the anwser is yes:
> 
> ![image](https://user-images.githubusercontent.com/30364409/87138271-76160f80-c29e-11ea-9344-98b477a28f40.png)

No garbage happening tho when playing?

**Comment by akamming** [comment]
yes there is. The screen behaviour is exactly alike, just didn't make a lot of screenshots...

btw the garbage are the remains of moving objects which are not overwritten by other objects because of the alignment problem as far a i can see it, see this example:

![image](https://user-images.githubusercontent.com/30364409/87139972-0b1a0800-c2a1-11ea-8032-eedc385e11b1.png)


 The reactangle with the data of the car (top speed, power, etc...) just animated from down the screen to where it is now . so what's below the 3d screen are leftovers from that animation which weren't cleared by the top screen which is aligned too far to the top screen.. 
So my assumption is that when the alignment problem is fixed, the garbage will also be gone..

**Comment by dankcushions** [comment]
> what do you mean by VI emulation code

sorry, i mean the emulated VI of the n64. well, i guess it's the n64 framebuffer emulation code if overscan doesn't make a difference.

**Comment by akamming** [comment]
> what do you mean by VI emulation code
> 
> sorry, i mean the emulated VI of the n64. well, i guess it's the n64 framebuffer emulation 'off' code if overscan doesn't make a difference.

aha clear.. now no time to look further into this. next week i'm on holiday (currently packing the car) but when i'm back i'll try if i can figure out this framebuffer code a bit. can someone point me where this n64 fb b off code is located in the code? Would save me a lot of time as a newbie to this code....

**Comment by akamming** [comment]
I tried to take a look at the code, but found out it is too complex for me, so i decided to take @dankcushions  's advice an log the issue [upstream](https://github.com/gonetz/GLideN64/issues/2309)
