### ISSUE TITLE
Majoras mask crashes to HOS when exploring clocktown

### ISSUE THREAD

**Issue by Mikau28** [libretro/mupen64plus-libretro-nx#234]
This happens when trying to go to other sections of clock town. 

I have tried to obtain logs for the issue but the nxlink exits when it dumps to hos.

Setup is set to switch thread and GL

![CD1324CF-E46C-405B-A847-B522F761E1F9](https://user-images.githubusercontent.com/40307312/87474988-d37cca00-c5d8-11ea-9466-42503fe1ae7e.jpeg)
![DA765957-2873-4C4F-A777-96F69B465E81](https://user-images.githubusercontent.com/40307312/87474998-d8417e00-c5d8-11ea-9a14-eb0cbefad40c.jpeg)

Took a video of what happens
https://streamable.com/lx3u08

**Comment by Mikau28** [comment]
https://streamable.com/lx3u08

**Comment by m4xw** [comment]
I would've noticed, I smell full-speed framerate or shenanigans like that
