### ISSUE TITLE
F-1 World Grand Prix II Crash in racing

### ISSUE THREAD

**Issue by ToniBC** [libretro/mupen64plus-libretro-nx#237]
This game crashes or closes the emulator when starting a race.

Tested under Windows 10 x64, with Nvidia, Vulkan and with GFX GlideN64/Parallel, in HLE/Parallel RSP, and whenever a race starts, it goes black, you hear a sound click and there the emulator stays or closes.

If you run it with Parallel (core) in Parallel (Vulkan) mode you will hear the same sound click, but let it continue many times, although other times the game crashes.

It always happens when starting a career, then if it starts, everything works without problems.

Tested with default and custom options, but always happens.

**Comment by m4xw** [comment]
Happens with Interpreter?

**Comment by m4xw** [comment]
Also got a retroarch --verbose log?

**Comment by m4xw** [comment]
![grafik](https://user-images.githubusercontent.com/13141469/88072076-e5c8ac00-cb74-11ea-905c-48699d123e68.png)
I heard the pop, but it works just fine here with defaults.
Windows 10, x64, AMD/GLCore
So either way, highly likely not a direct -next issue

**Comment by ToniBC** [comment]
I will carry out more tests and I will tell you, but I tried it by default and in interpreter.

**Comment by m4xw** [comment]
Please do, I will leave it open for now.

**Comment by ToniBC** [comment]
The error is generated randomly, sometimes it enters and sometimes it does not. Many times this appears on the screen.

![F-1 World Grand Prix II (Europe) (En,Fr,De,Es)-200722-160057](https://user-images.githubusercontent.com/45365478/88186323-533c1180-cc35-11ea-9a6e-8ad4a59505bc.png)

I attach the two logs to you.

[retroarch__2020_07_22__15_59_25.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4960469/retroarch__2020_07_22__15_59_25.log)
[retroarch__2020_07_22__16_04_45.log](https://github.com/libretro/mupen64plus-libretro-nx/files/4960470/retroarch__2020_07_22__16_04_45.log)

It seems that everything is in the click of the sound, something happens there.

**Comment by m4xw** [comment]
Try count per op 1

**Comment by ToniBC** [comment]
I'm lost with that, can you specify a little more ???

**Comment by m4xw** [comment]
.. Set Count per Op to 1.
Dunno what else to say. Its a core option.

**Comment by ToniBC** [comment]
Sorry, I didn't see that option, that's why I stayed there thinking ...

It is not clear to me what that option does, but if I put it in 3 it starts almost always, in 4 it seems more stable, even the click of the sound before the race disappears.

**Comment by m4xw** [comment]
What about 1?

**Comment by ToniBC** [comment]
Tried all the values, from 0 to 5, only 3,4,5 let me enter being 4 the one that even disappears the sound problem.

Tested in 1 with interpreter or dynarec and you get the error screen or it closes.

At least, in my case, value 4 seems to work, 3 starts, but out of 5 attempts one fails.

**Comment by m4xw** [comment]
4 seems pretty high, does it work reliable at least?

**Comment by ToniBC** [comment]
I have tried with 1 and the default options and nothing, it does not enter or it gives error.

I booted 15 times and all correct with the value of 4, and the correct framerate.

They may affect other things, but at least it works. Do you consume more resources with that value?

**Comment by m4xw** [comment]
>Do you consume more resources with that value?
The lower the more resources.
The default value is 2 (0 means 2 too)

**Comment by m4xw** [comment]
Should be fixed, reopen if persists. The build should be on the bot in ~3h at worst
