### ISSUE TITLE
(Windows) Compilation of custom textures not working.

### ISSUE THREAD

**Issue by bslenul** [libretro/mupen64plus-libretro-nx#238]
Hey!

Mupen64Plus-Next refuses to compile texture packs in .png format. The correct core options are ON, the pack is in the correct folder, the game boots directly, it's like it's not even trying, and no .htc file is being created at all in the cache folder.

It works perfectly fine on my Linux VM and it's also working fine on Windows with Mupen64Plus standalone and on Project64.

I tried multiple things: deleted my core option file to reset options to default (and then turning ON high res textures option of course :p), I also tried copying my core option file from my Linux VM (where it works fine like I said), and it's not a write permission for the cache folder since the core can write .hts files to it with no issue for example.

Steps to reproduce (again, Windows only!):

* Grab "Tsumi to Batsu: Hoshi no Keishousha" rom.
* Grab translation texture pack from here: https://www.romhacking.net/translations/920/
* Extract `TSUMI NO BATSU` folder in `system\Mupen64plus\hires_texture\`.
* Convert the 2 PNGs in `Nintendo Logo` folder to 32bit, or just get rid of that folder (because [the doc](https://docs.libretro.com/library/mupen64plus/#hires-textures) says non-32bit PNGs can be problematic with Windows). The other PNGs are already 32bit.
* Start the game, make sure "GLideN64" is selected as RDP plugin, turn ON "Cache Textures" and "Use High-Res textures".
* Close Content and restart the game, and... the game will start normally, with vanilla textures, and no .htc will be created in the cache folder :(

**Comment by m4xw** [comment]
What about alt crc?

**Comment by bslenul** [comment]
Nope, that option works great with pre-compiled .htc (we talked about it on Discord few days ago) but doesn't help with the pack in .png format unfortunately.

**Comment by bslenul** [comment]
Any progress on this? Still not working with latest commit from the online updater (a6a6bfd) :(

Also I see that you've added the "potential upstream issue" label, but it works perfectly fine with upstream, I just compiled Mupen64Plus and GlideN64 myself to double check:

https://user-images.githubusercontent.com/33353403/115697600-f99f7980-a363-11eb-8846-cd6701b6a177.mp4

As you can see it compiles the files and creates the .htc perfectly fine on boot (I didn't even need to convert these 2 "Nintendo Logo" PNGs to 32bit btw), using `VideoPlugin = "mupen64plus-video-GLideN64.dll"` + `txHiresEnable = True`

**Comment by m4xw** [comment]
Internally fixed.

**Comment by m4xw** [comment]
Should be fixed, reopen if persists. The build should be on the bot in ~3h at worst
