### ISSUE TITLE
Missing geometry (or textures?) on GLES2 since commit 6469626

### ISSUE THREAD

**Issue by shantigilbert** [libretro/mupen64plus-libretro-nx#239]
After commit 6469626a8fc8191518ae35543b80fd0002fd1604 I am getting a lot of missing textures and/or geometry, I tried random commits after that one and some of them just show white boxes (no texture or geometry at all) and the latest commit has a lot of glitched geometry and/or textures.

see the attached video: https://youtu.be/zU3Xpgi6H7w

also I get this on the log

```
[libretro INFO] mupen64plus: Initializing 4 RDRAM modules for a total of 8 MB
[libretro INFO] mupen64plus: Starting R4300 emulator: Dynamic Recompiler
[libretro INFO] mupen64plus: Init new dynarec
[libretro INFO] mupen64plus: ARM CPU Features:
[libretro INFO] mupen64plus: Enabled TLB
WARNING! Not implemented.
WARNING! Not implemented.
WARNING! Not implemented.
```
While on the last working commit (78233e1a925b8b0677918b0fe0894d56383e3923) I did not get the "WARNING!" 

```
[libretro INFO] mupen64plus: Initializing 4 RDRAM modules for a total of 8 MB
[libretro INFO] mupen64plus: Starting R4300 emulator: Dynamic Recompiler
[libretro INFO] mupen64plus: Init new dynarec
[libretro INFO] mupen64plus: Enabled TLB
```

Thank you!

**Comment by m4xw** [comment]
What if you switch lod emu to any other value?

**Comment by shantigilbert** [comment]
Same issue if I change LOD to false (was True). 

Also this seems to only happens with the 007 game? 
I tried Ocarina of time - seems working fine
Mario Kart - working fine
Mario 64 - working fine
I am sure there are other games affected, but I do not know which ones to test.

Although I still get the "WARNING! Not implemented." on the log

**Comment by m4xw** [comment]
Are u using a GLES3 platform with a GLES2 build?

**Comment by shantigilbert** [comment]
I am using `platform=AMLG12B` for arm and `platform=odroid64 BOARD=N2` for aarch64 to compile and I can see `   GL_LIB := -lGLESv3` being set, these have worked well before, but only after that commit that it broke. 

should I do the opposite and force -lGLESv2 ?

**Comment by shantigilbert** [comment]
Ok so forcing both 
```
GLES3 = 1
-lGLESv3
```
On the Makefile fixes this issue. 

Thanks

**Comment by m4xw** [comment]
Wanna do a pr for that? 
Also so it can be further discussed if required

**Comment by shantigilbert** [comment]
I can if you want, problem is I am not sure if this applies to all OS where the N2 can run (but I do not see why it wouldn't?)

**Comment by m4xw** [comment]
Thats why we will discuss it on a PR if required, so others can shine in.
