### ISSUE TITLE
F-Zero X Expansion Kit won't save

### ISSUE THREAD

**Issue by oboewan42** [libretro/mupen64plus-libretro-nx#240]
CPU is set to cached interpreter (it freezes with dynarec), RSP is set to ParaLLEl, VI overclock is 1500.

Whenever I exit and restart the game, it gives me an error message saying that previously saved data could not be initialized, and all my saved tracks/vehicles are gone (my save data for the vanilla game is still there).

This also happens in the cart-hack version, just without the error message.

**Comment by m4xw** [comment]
Freezing with dynarec is a huge red flag, it def. works with it.
Something is up with your setup

**Comment by oboewan42** [comment]
Don't know what that could be, tried a fresh setup on a different OS (Linux vs Windows) and got the same issue. Specifically the freezing happens when I try to load or save a custom track or vehicle.

**Comment by m4xw** [comment]
Wonder if its ini shenanigans.
Can u try different count per op values?
If its ini, it's probably a eep size issue or smth like that

**Comment by m4xw** [comment]
Should be fixed, reopen if persists. The build should be on the bot in ~3h at worst
