### ISSUE TITLE
‘vld1q_u8_x4’ was not declared in this scope

### ISSUE THREAD

**Issue by louisabraham** [libretro/mupen64plus-libretro-nx#241]
I tried compiling on aarch64 but got the following error:

```
In file included from ./mupen64plus-rsp-paraLLEl/arch/simd/rsp/rsp_common.h:15,
                 from mupen64plus-rsp-paraLLEl/state.hpp:4,
                 from mupen64plus-rsp-paraLLEl/rsp_op.hpp:4,
                 from mupen64plus-rsp-paraLLEl/rsp_jit.hpp:11,
                 from mupen64plus-rsp-paraLLEl/parallel.cpp:4:
./mupen64plus-rsp-paraLLEl/arch/simd/rsp/SSE2NEON.h: In function ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’:
./mupen64plus-rsp-paraLLEl/arch/simd/rsp/SSE2NEON.h:2729:20: error: ‘vld1q_u8_x4’ was not declared in this scope; did you mean ‘vld1q_u8_x2’?
 2729 |     v = vqtbl4q_u8(vld1q_u8_x4(crypto_aes_sbox), w);
      |                    ^~~~~~~~~~~
      |                    vld1q_u8_x2
make: *** [Makefile:548: mupen64plus-rsp-paraLLEl/parallel.o] Error 1
```

**Comment by m4xw** [comment]
What toolchain?
It seems to not know neon intrinsics so you won't be able to use parallel rsp.

**Comment by m4xw** [comment]
Actually that line is probably not used anyway so let me know if ripping it out does the trick

**Comment by louisabraham** [comment]
I don't get the question "what toolchain". I compile on a pinebook pro. I'll try removing that line.

**Comment by louisabraham** [comment]
So, the problem appeared when I tried to compile the AUR package but does not happen when using `make` after cloning.

However, I cannot use it.

- Launching `retroarch -L mupen64plus_next_libretro.so zelda.n64` says "Failed to load content"
- Installing the core in retroarch says `Core installation failed`

**Comment by m4xw** [comment]
You are building the GL version and I highly doubt your pinebook supports the required standard.

**Comment by louisabraham** [comment]
Actually, there is OpenGL support via Panfrost. But I understand that this rare platform is not a priority for you!
