### ISSUE TITLE
(parallel RDP) Wrong Colors in Paper Mario logo

### ISSUE THREAD

**Issue by OtavioRaposo** [libretro/mupen64plus-libretro-nx#242]
Parallel-RDP:
![Paper Mario (USA)-200706-114707](https://user-images.githubusercontent.com/36393971/86606901-f8d95a80-bf7e-11ea-8644-ee7b43ece8a3.png)

angrylion:
![Paper Mario (USA)-200706-114828](https://user-images.githubusercontent.com/36393971/86606926-01ca2c00-bf7f-11ea-806e-cad430f06e68.png)

This shows after Mario fall from the sky, in the start of the game. Savestate (for Retroarch) if needed: 
https://drive.google.com/open?id=1THTUxeHkawmJlfXjKedHuVJTEoF3ZfS2

**Comment by m4xw** [comment]
Since you already reported it, I will just close it.
https://github.com/Themaister/parallel-rdp/issues/14

**Comment by OtavioRaposo** [comment]
Ok. I just didn't know if Themaister was still active in this hub.

**Comment by tony971** [comment]
It's been fixed upstream
