### ISSUE TITLE
Unclutter Core Settings menu

### ISSUE THREAD

**Issue by Bowi-QC** [libretro/mupen64plus-libretro-nx#244]
Hello! On Windows 10, could you please add some kind of way for users to hide Core Settings options that aren't useful for the chosen plugins and CPU core/engine/thingy

Hiding all the settings for Glide and Angrylion whenever I use ParaLLEl RSP and RDP would be awesome! Thanks a lot! 🙇‍♂️

**Comment by m4xw** [comment]
It was planned before I even added the new core options, in fact i didn't want to add them before that, for exactly this reason.
I accept.

**Comment by m4xw** [comment]
Fixed in b6e00ae4d09f242cf9ea6b32a4d105ada620f91e (transferpak branch), Might gonna cherry pick it to develop later.

**Comment by m4xw** [comment]
3e2f48a44b88683bedd9651dd02e5e5d35e35d7b on `develop`
