### ISSUE TITLE
Performance better when holding retroarch function/hotkey button

### ISSUE THREAD

**Issue by theofficialgman** [libretro/mupen64plus-libretro-nx#249]
Hardware: Nintendo Switch
Built From: Github Source Code and tested version included in retropie
USB Devices connected: none
Controller used: attached joycons
Attachment of config files: default except threaded renderer enabled (https://pastebin.com/yTnqrZcu) and (https://pastebin.com/ipkA2679)
How to replicate the problem:

Some background, I'm using retropie on a nintendo switch running l4t ubuntu. X11, x.org, and gnome for the display protocol, display server, and desktop environment.

What happens: Load any game which experiences constant slowdown and hold the hotkey enable button (function enable button) and suddenly the game runs faster. When you release the button, the slowdown reappears. CPU clockspeed (2Ghz) and gpu clockspeed are fixed at this time. the main mupen64plus-next process thread is at 80% and doesn't go higher until holding the home button at which point it goes to ~98% maxing out the cpu.

A simple test is to boot the titlescreen for major's mask and the difference is clear as day.

Note: my function key is not mapped to any speedup button or any funnybuisness, and this happens in the version of mupen64plus-libretro-nx distributed with retropie and if I build build directly from master in this repo (which I did). Performance is a little worse overall with the source but I assume that is because I didn't pass anything through to the make command.

**Comment by m4xw** [comment]
You shouldn't be using RetroPie as they don't build a GL version.
You shouldnt need anywhere near 2GHz CPU, that overall this sounds to me more like a RA Issue.

>A simple test is to boot the titlescreen for major's mask and the difference is clear as day.

It's smooth in HD on half your clocks lol (thats on Horizon)

**Comment by theofficialgman** [comment]
Like I said, I also built the master straight from this repo as well (just passing make) and was experiencing the same issue (poor performance). Are there some parameters that I need to pass through when building the core (obviously I can't use the libnx platform since that requires horizon files). I can try running it from a standalone install of retroarch (not the one built by retropie) and see if that makes any difference next.

**Comment by m4xw** [comment]
You should be building develop btw.
Either way this isnt a core issue.

**Comment by m4xw** [comment]
Btw none of these issues are existent with l4t lakka, so i suspect some bs with your OS.

**Comment by m4xw** [comment]
Now this made me think, might be that you have your joycons via bluetooth and the input driver pools for X until state change or smth, but that would be a driver issue.

**Comment by theofficialgman** [comment]
no everything is done with the joycons connected via rails. this isn't an issue with other emulators (snes, nes retroarch) or standalone dolphin. will do more tests later to see if I can pinpoint the issue.

**Comment by m4xw** [comment]
Iirc l4t still uses bluetooth when connected to rails.
Also it depends how its polled in that case, there is nothing in this core that would cause this.
You probably just dont notice it in other cores and standalone dolphin might poll on a thread.
You forgot to enable video threaded as well?

**Comment by theofficialgman** [comment]
No, l4t ubuntu uses the rails to communicate with the joycons (been this way for a long time now). Threaded video causes issues in my experience with opening the retroarch overlay menu (it causes it to crash) and performance isn't any better in the emulator if I enable it manually through the config file.

**Comment by m4xw** [comment]
That's some big red flags, there never have been issues like that in lakka l4t.

**Comment by theofficialgman** [comment]
same thing happens if I install retroarch from the ppa. it crashes at boot.

**Comment by theofficialgman** [comment]
opengl is definitely enabled on the build using retropie. see the verbose log when i load the emulator using the installed version from retropie and the installed retroarch from retropie
https://pastebin.com/RE5K5qDH

**Comment by m4xw** [comment]
So many issues with that, sdl is a shit backend, the udev stuff might cause issues, you have a gl core compiled build (targets 3.3 core)  but you get a 4.6 Compat context (this isn't supported), also no shit you will have issues with paper Mario in HD if you don't tweak the settings, lots of frame buffer effects, also make sure it doesn't auto switch drivers so yet it specifically to 'gl' and nothing else

**Comment by m4xw** [comment]
yo @theofficialgman `[INFO] [Video]: Restored video driver to "vulkan".`
That line looks very very funky for where its placed. I actually had ppl report performance issues with auto switching, so def. try setting it to `gl` in RetroArch -> Drivers
Tho that would be out of control of the core.

**Comment by theofficialgman** [comment]
@m4xw a few notes. Changing from sdl2 to another backend didn't provide any measurable improvement. As for the drivers, even if I set it to gl after the next boot automatically it has switched back to glcore. As for paper mario, you noted that I had resolution set to 720 with all frame buffer affect off. The only setting with measurable impact at that resolution was to turn off the framebuffer emulation entirely (not good for paper mario) which made the game run at fullspeed with tons of graphical glitches. Lowering the resolution to native (240) with framebuffer emulation on produce full speed emulation.

From your first response you gave the implication that 720 was achievable easily which is what I was targeting. I now know that that isn't the case.

As for the video driver, it is set to gl as seen in my retroarch config pastbin in the first post and I have no idea why 

> Restored video driver to "vulkan".
 
appears. 

Lastly, as for majora's mask, I still can't get smooth framerate in the opening sequence. Is it a prerendered cutscene which is handled outside the emulator? In game performance is fine but the opening sequence still causes trouble.

**Comment by m4xw** [comment]
On mobile rn so I keep it short, intro is not pre rendered, it's literally smooth in horizon without even overclocking. 
You know that the game runs at 20 fps right? If you have bad sync that will always suck. The reported fps in RA is vertical interrupts per seconds and does not mean actual frames. 
As for paper Mario, 720p with fb effects off should Def work (it does under horizon). Maybe I find time to whip a Lakka build up for you, that should tell if the culprit is your distribution.

**Comment by m4xw** [comment]
Ah and yea u need to recompile the core and remove the define I told u yesterday from makefile.common so it won't think it's a core context

**Comment by m4xw** [comment]
As for fbemu, you Def want color and depth buffer to be off and fbemu itself on.
yes it will barely handle it else.

**Comment by m4xw** [comment]
If it's a sync issue I guess it would be a issue with the shipped x server
