### ISSUE TITLE
Parallel-RDP missing interlacing option

### ISSUE THREAD

**Issue by nfp0** [libretro/mupen64plus-libretro-nx#251]
Parallel-RDP on ParallelN64 has an interlacing core option called `parallel-n64-parallel-rdp-interlacing` to control if the output is weave or bob deinterlacing. Mupen's Parallel-RDP doesn't seem to have this core option and seems to be hardcoded to output bob deinterlacing.
This makes it impossible to use it with CRT shaders that support interlaced content as these shaders typically except the weaved content.

I request that this core option be added for parity with ParallelN64 and so that we can use 480i N64 games (such as Pokemon Stadium) with CRT shaders,

**Comment by m4xw** [comment]
Fixed in f4b1b53ac6045c7905c03c9df9acfa2eeedf1704

**Comment by nfp0** [comment]
Awesome! I can confirm it's working correctly with shaders that support interlacing now. 👍 
Thanks for the fix!
