### ISSUE TITLE
1080 image/texture corruption

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#254]
Start 1080 Pal Version. Already the intro screens show "lines" which were not visible in the original.
If you enable "native res 2d textrects" you will become "peaks" instead of lines.
Can be reproduced with default settings.

![1080 Snowboarding-200901-162932](https://user-images.githubusercontent.com/10263536/91864297-584aa280-ec70-11ea-8deb-6500a1140297.png)

**Comment by m4xw** [comment]
What about standalone

**Comment by Papermanzero** [comment]
Dunno. Tested it with retroarch and the core.

**Comment by m4xw** [comment]
Then it sounds like a gliden issue and not a -nx issue

**Comment by m4xw** [comment]
Closing in favour of upstream issue.
