### ISSUE TITLE
Can't open N64 ROMs

### ISSUE THREAD

**Issue by Bezier89** [libretro/mupen64plus-libretro-nx#26]
Excited to see that someone is working on an updated Mupen64Plus core!

I downloaded the latest version of this core ("Mupen64Plus-Next OpenGL 1.0 1c2029a) in Retroarch. When I try to open an N64 ROM, it only allows for other N64 emulators (Parallel N64, old Mupen64Plus), but not this one. If it matters, these ROMs are in z64 format.

**Comment by m4xw** [comment]
No informations provided.

**Comment by Bezier89** [comment]
@m4xw What more information do you need?

**Comment by m4xw** [comment]
About everything. You didn't give me a single information.
Platform, what rom etc etc

**Comment by Bezier89** [comment]
@m4xw 

Platform: Windows 10
RetroArch: 1.7.5
ROMs: All of them (at least with my collection)

Full repro steps:

1. Select "Load Core"
2. Select mupen64plus_next_libretro.dll
3. Select "Load Content"
4. Select an N64 rom. Mine are in the [z64 format](https://en.wikipedia.org/wiki/List_of_Nintendo_64_ROM_file_formats#Normal_ROM_Files).
5. The ROM does not load. Rather, it prompts me to select an emulator. The only options present are the old Mupen64Plus core and Parallel 64.

**Comment by m4xw** [comment]
Update your core informations.

**Comment by Bezier89** [comment]
@m4xw 

Ah, got it. Had to update core info and _redownload_ the core. Seems weird that Retroarch would even let me download the core in a broken state like that, especially since it appeared to be a recent version (commit from 4 days ago). Anyway, thanks for your help!
