### ISSUE TITLE
Mupen64Plus-Next not working on Orange Pi Plus 2E (Lakka OS)

### ISSUE THREAD

**Issue by d-apps** [libretro/mupen64plus-libretro-nx#260]
I am trying to play some N64 games but everytime I try to run a game I get a blackscreen and RetroArch restarts.

Before I install Lakka OS I had RetrOrangePi installed and I was using Mupen64Plus-Next, the core was working fine, almost all of my romset was working, decent/playable fps.

Since Mupen64Plus-Next was not working on Lakka OS I tried ParaLLel N64 core, at least games are booting but the fps is bad, I had some headackes trying to change the GFX Plugin and other settings (requires restart but when I try to restart it freezes and when it doesn't freeze it doesn't save the new settings). So I tried to change retroarch core cfg file, but even lowering the settings fps were too slow.

Which version of Lakka are you using?
**2.3.1** and with **Lakka-H3.arm-3.0-devel-20200913000629-60c3efd-orangepi-plus2e (Nightly 2020-09-13)**

What system hardware are you using?
**Orange Pi Plus 2E**

What did you do?
**Select a Nintendo 64 game, select Mupen64Plus-Next, run.**

What did you expect to happen?
**Run the game.**

[Mupen64Plus-Next log.txt](https://github.com/libretro/Lakka-LibreELEC/files/5185759/Mupen64Plus-Next.log.txt)

I opened this issue as recommendation by Ntemis from Lakka repository, original issue: https://github.com/libretro/Lakka-LibreELEC/issues/1024

**Comment by m4xw** [comment]
I can't accept a bug report like this without a gdb trace.

**Comment by d-apps** [comment]
> I can't accept a bug report like this without a gdb trace.

Could you guide me how to gdb trace?

**Comment by m4xw** [comment]
Dunno about lakka :/

**Comment by d-apps** [comment]
I ended up reinstalling RetrOrange Pi v4.3, since on that version Mupen64Plus works fine.

**Comment by m4xw** [comment]
I will close this for now since this is also the first time I heard about it.
If someone can provide more infos I can consider reopen
