### ISSUE TITLE
Update Parallel-RDP

### ISSUE THREAD

**Issue by OtavioRaposo** [libretro/mupen64plus-libretro-nx#261]
I don't know if this is the right place to ask, but there were some bug fixes in parallel-rdp last week that are still not available in the current mupen core. It fixes some things like color errors in Paper Mario, for example.

**Comment by m4xw** [comment]
It's on my TODO, I got side tracked with the Mario Allstars collection ;)

**Comment by OtavioRaposo** [comment]
Ok, I would thank you if you let me know. Try not to spend your time finding the hidden Super Mario Galaxy 2.

**Comment by m4xw** [comment]
8a71531
