### ISSUE TITLE
[Feature Request] Rom name instead of internal name for Highres Texture Packs

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#262]
Currently, mupen64plus next uses the internal rom names for hires texture packs. However for most standard users it is hard to find out what the regular internal name is. Instead it would be more convenient to use the rom name to detect the high res pack. Similar to what beetle-psx does.

This would be a QoL improvement.

**Comment by m4xw** [comment]
No. Too invasive change for now.
