### ISSUE TITLE
Vigilante 8 - Multiplayer Brawl doesn't work with GlideN64, HLE & dynarec + HUD blinking & disappearing in MP

### ISSUE THREAD

**Issue by Gagert** [libretro/mupen64plus-libretro-nx#263]
This game has a history of being one of the harder N64 games to emulate, especially with traditional graphic plugins such as GlideN64. I even created a [thread regarding this on the GlideN64 github page](https://github.com/gonetz/GLideN64/issues/1285) a couple of years ago.

With the older and no longer supported Mupen64Plus libretro core, I'm able to start a game in Multiplayer Brawl, select cars for all 4 players and actually start a game. The graphics are surely enough very bugged when entering a race under those settings, but I'm actually able to enter the race in this mode in the old Mupen64Plus libretro core with dynarec (or dynamic interpreter as it's called in this old libretro core).

In this N64 libretro core however, with GlideN64, HLE & dynarec enabled, the game crashes after entering the Multiplayer Brawl menu when the game is supposed to enter the car selecting menu for all 4 players (the music continues but the game freezes). 

The game works under these settings if I instead chose ParaLLel-RDP as the RDP plugin and then selecting a higher upscaling factor for higher resolution, but even with the upscaling factor set to 1x, the game runs very slow on my gaming PC as the ParaLLel-RDP plugin is fairly demanding hardware wise.

There's also issues with the HUD in the 2 Player Versus mode (which works in GlideN64), where Player 2 is missing the HUD itself. Running the game with ParaLLel-RDP makes the Multiplayer Brawl setting work & successfully go in-game, but there the Player 1 HUD is blinking, while it seems to be no issues with the HUD for the 3 other players (I've tested in 4 player mode).

**Comment by m4xw** [comment]
Hey, thanks for your report but I have no intentions to fix game specific upstream issues.
This is not a -next bug by itself.
Also a note: Theres no dynamic interpreter, only cached interpreter and dynarec. Even in the old core.

**Comment by m4xw** [comment]
Tho, If you get me a backtrace from the crash on the latest ver, I can spend a quick look.
I don't have time for major efforts tho.

**Comment by makwan99** [comment]
hi guys i am die hard vigilante 8 fan since 2016 i am trying to run this game in multiplayer with my brothers it keeps blinking in all 4 players can you please fix this issue i am very thankful if you do 


and mr gagert did you find any fix for this?

**Comment by Gagert** [comment]
@makwan99 nope
