### ISSUE TITLE
RA becomes unresponsive with threaded renderer enabled

### ISSUE THREAD

**Issue by Krispy3000** [libretro/mupen64plus-libretro-nx#266]
I am running Mupen-Next on a GPD XD+ which I flashed LineageOS onto. This is nice because the drivers are much more stable and supports GLES 3.2. However, when I try to enable threaded renderer, titles that don't run full speed make RA become unresponsive instead of just dropping frames. I think having threaded renderer working is all that it would take to see Mupen-Next perform at the level Mupen FZ does on these Android devices.

(Side note, turning color buffer on, even 'double buffer' is very slow on this GPU.)

**Comment by m4xw** [comment]
You need to use Early Input Polling.
The core actually tells the frontend to force it but it doesnt seem to work (will raise that issue internally).

**Comment by m4xw** [comment]
If that didn't do the trick please reopen

**Comment by Krispy3000** [comment]
Thanks that was exactly the problem. Hope there is a speedy remedy for the force issue.

**Comment by m4xw** [comment]
> 
> 
> Thanks that was exactly the problem. Hope there is a speedy remedy for the force issue.

Thanks for confirming
