### ISSUE TITLE
Battle for Naboo and Indiana Jones "freeze" in Retroarch 64bit.

### ISSUE THREAD

**Issue by frafes** [libretro/mupen64plus-libretro-nx#268]
When using mupen64plus-libretro-nx with Dynarec core, the games "Indiana Jones" and "Star Wars - Battle for Naboo" sometimes will "freeze" and Retroarch will not respond for 1 or 2 minutes. It happens only in Retroarch 64bit. 

In Retroarch 32bit, Battle for Naboo runs fine. Indiana Jones runs fine with CXD4 RSP Plugin but crashes with ParaLLEl RSP.

To reproduce it just go to the game title screen and wait for the demo gameplay. The screen will be black and Retroarch will not respond for some minutes.

OS: Windows 10 x64

**Comment by m4xw** [comment]
What about Cached interpreter?
Also I rather reopen #222 (lets move to there) and add your information there.
