### ISSUE TITLE
Core runs slow, issue forcibly closed as "spam" for valid issue

### ISSUE THREAD

**Issue by DoktorSeven** [libretro/mupen64plus-libretro-nx#27]
It's just slow, period.  I have not the best CPU, a quad core AMD 2.4GHz, and it runs unplayably slow at a few frames per second; however, running plain (standalone) mupen64plus with the Glide64 plugin on the exact same machine runs perfectly.  Something is wrong with your implementation here, or with RetroArch in general, yet RA seems to run every other core at least somewhat equivalent to standalone emulators, and runs N64 via parallel just fine.

_Originally posted by @DoktorSeven in https://github.com/libretro/mupen64plus-libretro-nx/issues/12#issuecomment-466708191_

Closing this as "spam" and removing the ability to post new replies?  That's a terrible way to respond to people.  Though, what do I expect from the greater libretro community and their half-assed, slapped together from random bits and pieces "emulator"?  I know that sounds trollish, but honestly, every time I deal with issues with this emulator, that's the attitude I get.  Might want to adjust that.

**Comment by m4xw** [comment]
You compare graphics plugin that are 5+ years apart in development.
Also Glide64 is less demanding, while GlideN64 is designed with high end hardware in mind.
Your Issue is out of scope, so please stop spamming the Issue tracker.
