### ISSUE TITLE
Better 64DD (.ndd) support

### ISSUE THREAD

**Issue by SamRohod** [libretro/mupen64plus-libretro-nx#270]
The "Mupen64Plus-Next" core doesn't seem to support the .ndd extension in the better way that "ParaLLEl N64" does.

In "Mupen64Plus-Next":
After installing the file IPL.n64 to <RetroArch_Directory>\system\Mupen64plus\
You still have to
1- Load the core
2- Use the subsystem to load the disk file (.ndd)
3- Use the subsystem to load a cartridge file
4- Use the subsystem to run the game
This works great for a disk-cartridge combination game (like the F-Zero X with the Expansion Kit disk), but for a disk only game (like Super Mario 64 - Disk Version) this doesn't work well.

In "ParaLLEl N64":
After installing the file 64DD_IPL.bin to <RetroArch_Directory>\system\
If the game is a disk only game, the core just run the .ndd file like any other supported file.
For a disk-cartridge combination it runs like "Mupen64Plus-Next" (which is great for that)

**Comment by m4xw** [comment]
That already works, in fact its fallback for when subsystem was broken on static platform.
Add the ipl, have rom.extension and rom.extension.ndd in the same folder and then start the .ndd
