### ISSUE TITLE
Donkey Kong 64 Camera Issue Regression

### ISSUE THREAD

**Issue by retropieuser** [libretro/mupen64plus-libretro-nx#273]
It seems a problem that was fixed on the lr-mupen64plus core for DK64 is back in lr-mupen64plus-next. At least it is on the version on the raspberry pi retroarch I'm testing it with. It seems fixable in the standalone mupen64plus emulator by updating the GLideN64.custom.ini settings and changing frameBufferEmulation\copyDepthToRDRAM= 0. However changing this in options in retroarch doesn't seem to work?

https://youtu.be/P5wDA_2_gWI

Here's an example of how the camera glitch operates, anytime the game isn't in a fixed camera position it seems to reset.

Edit:- I just put a pull request in as I updated the file

**Comment by m4xw** [comment]
This is not a regression but a long known standalone issue
https://github.com/libretro/mupen64plus-libretro/issues/86#issuecomment-452648612

**Comment by maxwell-kalin** [comment]
So this is a wont-fix?

since upstream is dead?

**Comment by Jj0YzL5nvJ** [comment]
https://imgur.com/a/9fFY9VY
