### ISSUE TITLE
"Failed to load content" while trying to start a N64 ROM

### ISSUE THREAD

**Issue by kartikynwa** [libretro/mupen64plus-libretro-nx#278]
Hello. Sorry if this is not the right place to ask this. Please feel free to let me know if that's the case.

I am on RetroArch 1.9.0 on Void Linux x86_64-glibc (from distro's package manager). When trying to start a game (only tried it with Majora's Mask but I don't think that's relevant), I get a message saying "Failed to load content" and RetroArch goes back to the home screen.

This is the log: [log.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5474307/log.txt)

This happens for both `gl` and `vulkan` video drivers and the error messages are the same in both cases as well.

**Comment by m4xw** [comment]
Your frontend is compiled against OpenGL**ES** so OpenGL won't work.
Even if you select vulkan as driver it will request what you set in the core options.
You may try setting the RDP plugin "parallel" in the core options and then using vulkan or recompile your frontend against OpenGL.
Keep in mind 3.3 core or 4.3 compat profile are required :)

**Comment by kartikynwa** [comment]
You were correct. I wasn't sure because our RetroArch is built against both `gles` and `gl`. Once I turned off the `gles` build option, the core works with both `gl` and `vulkan` driver. Thanks for your quick response.

**Comment by m4xw** [comment]
Np, its indeed a bit inconvenient and on my todo to support both runtime.
Currently the core is either built against GL or GLES, never both
