### ISSUE TITLE
Games failed to launch on Thinkpad X200

### ISSUE THREAD

**Issue by RefinedAnarchy** [libretro/mupen64plus-libretro-nx#281]
CPU: Core 2 Duo P8600
GPU: GMA 4500MHD 
OS: Parabola GNU/Linux-libre
Window Manager: Sway
glxinfo:
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 20.2.2
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
log:
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[INFO] [Wayland]: Seat name: seat0.
[INFO] [Wayland]: Physical width: 260 mm x 160 mm.
[INFO] [Wayland]: Video mode: 1280 x 800 @ 60.0040 Hz.
[INFO] [Wayland]: Display scale factor 1.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [Wayland]: Loaded keymap.
[INFO] [GL]: Found GL context: wayland
[INFO] [GL]: Detecting screen resolution 0x0.
[ERROR] [EGL]: #0x3009, EGL_BAD_MATCH
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] failed_to_start_audio_driver

**Comment by m4xw** [comment]
Your mupen build is compiled against opengl, but your frontend seems to be GLES?
