### ISSUE TITLE
Rewind only works for 2 or 3 seconds

### ISSUE THREAD

**Issue by Darknior** [libretro/mupen64plus-libretro-nx#287]
## Description

When i play other libretro emulators, like SNES, Genesis, FBNeo, i can REWIND like i want to 3 or 20 seconds without any problem.
But on Mupen64 Next (like with psx: Duckstation, psx: Madnafen, and n64: Parallel64) i can only REWIND 2 or 3 seconds and it stop, i can't go before. It not crash the emulator ... but 2 or 3 second is not enough ... the feature is broken :(

## Steps to reproduce

Launch a game, play 2 minutes and try to REWIND

## Your device/OS/platform/architecture

Same on RPI3b+, Odroid N2, RPI4 and PC.
All tested with Batocera.

**Comment by m4xw** [comment]
Rewind is not supported.

**Comment by Darknior** [comment]
ok thanks. It's because we can activate it in Libretro options.

**Comment by m4xw** [comment]
Ye, you aren't the first one.
Savestates are too heavy tho to use retroarch's implementation of rewind, it would be required to write a implementation from scratch for mupen next.

**Comment by Darknior** [comment]
Ok i understand fine, like other PSX emu, Saturn emu, Dreamcast emu ... 
And do you think it can be possible to found a solution and make it from scratch one day ?

It's really so bad an emulator can't hide this option, or also the latency reduce option, when it not working fine to prevent users to use them. It's what we do on Batocera we hide these option in the ES menu, to prevent users and many questions in Forums ... but they can always try them by libretro menu ...
Thanks for you answers :)

**Comment by m4xw** [comment]
> And do you think it can be possible to found a solution and make it from scratch one day ?

Maybe, I don't have much interest implementing it myself tho.
