### ISSUE TITLE
Beetle Adventure Racing freezes when selecting a certain car

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#289]
Whenever you select the green car and try to play the first track, the game freezes. Other cars work fine.

Here's a save to unlock all cars:

[Beetle Adventure Racing! (USA) (En,Fr,De).zip](https://github.com/libretro/mupen64plus-libretro-nx/files/5730640/Beetle.Adventure.Racing.USA.En.Fr.De.zip)

**Comment by m4xw** [comment]
What about standalone?

**Comment by Tasosgemah** [comment]
> 
> 
> What about standalone?

I'm sorry, i couldn't test it on the standalone because the save files are incompatible.

**Comment by m4xw** [comment]
https://github.com/heuripedes/pj64tosrm should work

**Comment by Tasosgemah** [comment]
Not sure what is this or how it works... Is it a save converter?

**Comment by Tasosgemah** [comment]
Ok, i managed to find a save for standalone Mupen. It happens there too.

**Comment by m4xw** [comment]
Thanks for confirming
