### ISSUE TITLE
Input poll behaviour issues

### ISSUE THREAD

**Issue by m4xw** [libretro/mupen64plus-libretro-nx#29]
Seems currently it only works with poll behaviour: early or late, according to some reports

**Comment by mudlord** [comment]
I remember reading you didnt call poll_cb, anywhere, which is needed for inputs to work.

Not sure if this is still the case: tried looking at old parallel code for when to poll?

**Comment by m4xw** [comment]
@mudlord I remember seeing the change in the main loop (the one with retro return).
Good call, that likely can be it.

**Comment by mudlord** [comment]
Well, in libretro, you must call the poll_cb() callback before you can get any input data. My libretro client expects that, as I guess many others including RetroArch itself.

I found in new_vi is a good spot to call the callback.

**Comment by mudlord** [comment]
I guess I can play around with it my time. I got to do some customizations anyway for mupen hle to handle my N64 clone controller.
