### ISSUE TITLE
Buffering/Stuttering in N64 games

### ISSUE THREAD

**Issue by ItsAshleyFTW** [libretro/mupen64plus-libretro-nx#291]
Whenever I launch an N64 game there is a small pause whenever something new gets loaded into memory. When I restart the game from the Quick Menu, the game stops buffering, but when I exit out of RetroArch and launch the game again, the game buffers again. At some points the game buffers several times in a row. Is there any way around this? 

It's not a problem with the system I'm using, the game runs full speed otherwise. (I'm using the Mupen64Plus-Next v2.1 core on the Anbernic RG351P)

**Comment by m4xw** [comment]
Sounds like shadercache. If thats not supported then you are out of luck. If its super underpowered / low mem speed it can be dynarec doing dynarec things, its all wontfix.

**Comment by ItsAshleyFTW** [comment]
I looked in the Quick Menu, there's no option for "Cache GPU Shaders." Guess I'll just have to wait until it gets supported.

**Comment by m4xw** [comment]
It is supported with GLES3 or GL.
If your platform doesnt support that, nothing i can do.

**Comment by ItsAshleyFTW** [comment]
I have two N64 cores on my device. Mupen64Plus v2.5 GLES2 and Mupen64Plus-Next v2.1 GLES2. The first one has that option but not the second one. But on my Windows PC, the Mupen-Next core has that option. Why is that? Surely Linux or Android is capable of using the shader cache.
