### ISSUE TITLE
Densha De Go! 64 english translation not working with dynarec enabled (x86_64/aarch64)

### ISSUE THREAD

**Issue by stuken** [libretro/mupen64plus-libretro-nx#295]
As per title. With this patch applied [https://www.romhacking.net/translations/2947/](url) the game will sit at a black screen when the dynarec is enabled. Both interpreter modes boot correctly.
The unpatched rom works fine with the dynarec enabled. Standalone works in all cpu modes with both patched and unpatched roms.

**Comment by m4xw** [comment]
Add a --verbose log, copy of core options

**Comment by m4xw** [comment]
Also did you make sure that your standalone test used a recent ver of gliden and mupen core?

**Comment by stuken** [comment]
Here are the log and core opts.
[retroarch__2021_01_06__20_05_02.log](https://github.com/libretro/mupen64plus-libretro-nx/files/5777970/retroarch__2021_01_06__20_05_02.log)

[Mupen64Plus-Next.opt.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5777972/Mupen64Plus-Next.opt.txt)

I've tested against the latest build of m64p https://github.com/loganmc10/m64p/releases/tag/Jan42021

**Comment by m4xw** [comment]
Can you try my experimental branch?

**Comment by stuken** [comment]
The latest build artifacts off the experimental branch are not on the libretro gitlab anymore. is there anywhere else they are available?

**Comment by m4xw** [comment]
Best you compile it yourself.
The branch doesn't integrate right in the Infra

**Comment by m4xw** [comment]
Gillou found a fix

**Comment by m4xw** [comment]
Should be fixed, reopen if persists. The build should be on the bot in ~3h at worst
