### ISSUE TITLE
Kirby freezes when you kill the first mini-boss, in the first level

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#299]
This is very early in the game so no need for a save. Just play the first level until you reach the first mini boss (should take 2 minutes).

When you defeat him, the game freezes.

The standalone doesn't have this issue. However, you can fix this in the libretro version if you enable "pure interpreter". Though, i'm not sure if the standalone (i'm using m64p) has this option selected, i can't find this anywhere. Maybe some games are pre-configured to use interpreter in m64p?

**Comment by m4xw** [comment]
you mean m64p gui? It doesn't ship with dynarec at all.

**Comment by Tasosgemah** [comment]
Yes that's what i'm using.

**Comment by m4xw** [comment]
Then its yet another new_dynarec issue, you might wanna create a issue in -core upstream
