### ISSUE TITLE
Q: Texture transparency in Super Smash Bros on RPI

### ISSUE THREAD

**Issue by hhromic** [libretro/mupen64plus-libretro-nx#30]
In Super Smash Bros (USA) I'm observing a texture transparency glitch on Raspberry PI. The texture is the "far away circle" object. See example photo for clarification:

![image](https://user-images.githubusercontent.com/5802993/53433007-82703400-39eb-11e9-9393-63564c8ca40f.png)

It happens in every part of the game where that circle needs to be displayed, not only in demo mode. More than an issue, this is a question if this is a known glitch in the old 2.x GLideN64 code. Also, this doesn't happen in current Windows build. I tried different core options and none seems to help.

**Comment by hhromic** [comment]
To make it clear, this also happens with the old mupen64plus core so is not something introduced in the "next" core. I'm just wondering if this is solvable easily or just something to live with for now. Also maybe the new GLideN64 plugin addresses it.

**Comment by m4xw** [comment]
fbemu?

**Comment by hhromic** [comment]
Yep, tried enabling/disabling it, no change. I also tried other options as well with no effect. FWIW seems to be the only noticeable (i.e. "ugly") glitch in this game. Have you seen something like this in other games?

**Comment by m4xw** [comment]
I only saw issues like this related to fbemu.
Not sure if GlideN would fix it, you can always try standalone mupen+gliden 3.0, if it runs there expect it to be fixed.
Want me to leave this open?

**Comment by hhromic** [comment]
I will be testing on standalone mupen+gliden 3.0 later today to confirm.
Lets leave it open until that. Thanks!

**Comment by hhromic** [comment]
Okay I know what is happening now. It turns out that FrameBuffer Emulation is actually always forced to disabled in RPI devices, no matter the option in the core settings:
https://github.com/libretro/mupen64plus-libretro-nx/blob/1c2029abcf15b486a5e7ae5517521c1559f31d37/custom/GLideN64/mupenplus/Config_mupenplus.cpp#L121-L125

I temporarily allowed for it to be enabled and while the game glitches heavily (probably the reason FBEmu is always disabled on RPI for GLideN 2.0) the glitch in this issue is indeed fixed.

I tested standalone Mupen64plus + GLideN64 3.0 and with FBEmu enabled the game works much better, just some glitches with background textures that should be in the back and instead are rendered in front of other objects. This means that the upcoming GLideN64 3.0 will address this issue and also improve FBEmulation vastly on RPI devices.

I will close this issue for now and leave the info for posterity :) Thanks anyway!
