### ISSUE TITLE
Top Gear Overdrive (U) - Crashes immediatelly

### ISSUE THREAD

**Issue by Shideravan** [libretro/mupen64plus-libretro-nx#301]
**Core used**
Mupen64plus-Next + Parallel RDP. Latest version.

**Specs**
Windows 10 x64, i7-4790, GTX 1070 

**Issue**
Emulator crashes immediatelly when try to load this game.

**Comment by m4xw** [comment]
Standalone behaviour?
What about GLideN?

**Comment by Shideravan** [comment]
When, with Parallel emulator core it works fine.

**Comment by mountnside** [comment]
No, does it work with the standalone version of Mupen64Plus and GLideN64, first?

**Comment by Jj0YzL5nvJ** [comment]
https://imgur.com/a/L1TWRfu
https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd

**Comment by Shideravan** [comment]
Mupen64Plus (command line version, default configuration). Yes, it's working (messy graphics though)
![image](https://user-images.githubusercontent.com/12163923/107156792-20eacb00-695f-11eb-9165-13b3577a5904.png)

**Comment by m4xw** [comment]
> Rice
> Glide
> 2 year old mupen build
None of these are a valid comparision

**Comment by Jj0YzL5nvJ** [comment]
> None of these are a valid comparision

Mine is technically "7 days" old at most, isn't that valid?

[HLE](https://github.com/mupen64plus/mupen64plus-rsp-hle/commit/e653930d75019f88dd386a3d534008d89dbc12ff): NewDynarec [2.5.9-183-g7bceeb57](https://github.com/mupen64plus/mupen64plus-core/commit/7bceeb572a2f85f617bee30682fd6d70a33ced16) + GLideN64 [rev.dc6340bf](https://github.com/gonetz/GLideN64/commit/dc6340bfff13c103397167e4c8028483bb474663)
[LLE](https://github.com/Jj0YzL5nvJ/parallel-rsp/commit/c8fcb90d3ad750314256c13f81509c40e7ae3bcc): NewDynarec [2.5.9-183-g7bceeb57](https://github.com/mupen64plus/mupen64plus-core/commit/7bceeb572a2f85f617bee30682fd6d70a33ced16) + angrylion's RDP Plus [v1.6-1](https://github.com/ata4/angrylion-rdp-plus/commit/904ca2279b902724279eefb2a1c2e155ddb475ac)

See the videos: https://github.com/libretro/mupen64plus-libretro-nx/issues/301#issuecomment-774459439

**Comment by Jj0YzL5nvJ** [comment]
mpv https://imgur.com/5RaYWvg https://imgur.com/ljguGDO https://imgur.com/NS09McZ https://imgur.com/4gT8WdF

**Comment by m4xw** [comment]
> Mine is technically "7 days" old at most, isn't that valid?

That might be too new ;)
However seems to not be a -core issue then.
So i need a backtrace which he probably isn't able to provide :/

**Comment by Tasosgemah** [comment]
I have the same problem. 

The game loads fine in m64p but crashes in RetroArch.

However, if i use a frontend like RocketLauncher or Launchbox to launch the game with RA as the emulator, it loads! It only crashed if i try to load the game through RA's own UI.

**Comment by daninthemix** [comment]
Yep confirmed here too. Latest Retroarch, latest core.

**Comment by m4xw** [comment]
Might be fixed on last release (on the bot in ~3h), let me know

**Comment by Tasosgemah** [comment]
Game loads fine for me when i load it from RA now.

**Comment by daninthemix** [comment]
Yes the Top Gear games load fine now. However Battletanx Global Assault behaves the same way they used to - a hard Retroarch crash on launch.

**Comment by m4xw** [comment]
> 
> 
> Yes the Top Gear games load fine now. However Battletanx Global Assault behaves the same way they used to - a hard Retroarch crash on launch.

Was that on latest build? What platform, can you get a gdb trace?
Feel free to create a seperate  issue
I will be closing this one
