### ISSUE TITLE
Add make configuration options in readme and make --help

### ISSUE THREAD

**Issue by lelecanfora** [libretro/mupen64plus-libretro-nx#303]
Currently there is no way to know the available and working build options and make --help only provides the list of different libraries that can be built, no their configs.

Please add a full list to the readme and make --help

**Comment by m4xw** [comment]
The Makefile itself serves as documentation.
All common relevant options are right at the top https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/Makefile#L1-L22

Thats also why every platform is nicely categorized even if its redundant, for documentation purposes.
You probably made this as a convinience suggestion, but my take is: If ya can't figure by looking at Makefile, you probably shouldn't try it to begin with.

**Comment by m4xw** [comment]
However I will have Contribution guidelines in the future, those might elaborate this a bit 👍

**Comment by lelecanfora** [comment]
Thanks, yes I looked at the makefile and saw the flags, that still doesn't mean that I understand what they do and how do I get the best performance out of my Pi 4... currently the develop branch does not build on the pi 4...

**Comment by m4xw** [comment]
Theres no magic flag u can change to get better performance.
The "rpi" target is intended for the original raspbian distribution and retropie.
If you don't use it, you shouldnt use the rpi platform target
The only thing you might need to add is -DGL_USE_DLSYM, which isnt a Makefile variable to begin with (currently), but could be added.

**Comment by m4xw** [comment]
However if you use raspbian and it doesnt build there, please open a Issue for _that_

**Comment by lelecanfora** [comment]
Thanks again, yes it doesn't build if I simply run "make -j4" and again if I run "make -j4 CFLAGS='-FORCE_GLES3=1'" I will write an issue for that

**Comment by m4xw** [comment]
So.. Where are you building on.
If you are indeed on raspbian, you need to pass platform=rpi4 since it will use the unix target otherwise.
Also the latter line you quoted wouldn't work to begin with, it would just be `make -j4 FORCE_GLES3=1`

**Comment by lelecanfora** [comment]
understood, thanks for the clarification, I've opened this issue: https://github.com/libretro/mupen64plus-libretro-nx/issues/304

**Comment by m4xw** [comment]
run make clean first

**Comment by lelecanfora** [comment]
it built with the platform rpi4 and the force gles3 option, I will test its performance soon, thanks for helping me with it and thanks for the whole project

**Comment by m4xw** [comment]
Dont forget to turn on thr renderer ;)
I think we could add a detection specific for raspbian tho, but as far the Makefile is concerned, its a standard linux platform by default.
