### ISSUE TITLE
Unable to use the parrallel gfx plugin with a 6800XT

### ISSUE THREAD

**Issue by buddwm** [libretro/mupen64plus-libretro-nx#306]
This could be an AMD driver issue, but figured I would post it for visibility.  It seems any of the available Catalyst drivers for the AMD 6800/6900 series experience this problem in Windows.

When loading any N64 rom with the parallel gfx plugin, I will get the following and then Retroarch either freezes or simply closes without any other information:

![retro_n64_vulkan_crash](https://user-images.githubusercontent.com/12883173/106367696-0a62c500-630a-11eb-960f-db4aa5964369.png)

It appears to be a problem with Vulkan in general as I experience a similar issue with Flycast (folks reporting that [here](https://www.reddit.com/r/RetroArch/comments/l04f0p/can_anyone_with_a_amd_radeon_card_please_see_if/) for reference).  I haven't had the chance to test in Linux just yet.

This happens with the stable and latest nightly of the core/retroarch.

**Comment by buddwm** [comment]
I can confirm that it works in Linux using the opensource mesa drivers.  So this appears to be a Windows specific issue.

**Comment by Immersion95** [comment]
Same problem on Windows :(

**Comment by Immersion95** [comment]
With latest drivers for Windows/AMD/Latest RA/CORE : I only have 2 crashing games of my libraries and it's Mario Tennis & F-Zero. I currently use Angrylion GFX for them.

**Comment by buddwm** [comment]
This issue is still happening, but I think I have more context on what it is now.  Any 3D console in Retroarch, such as N64 cores or the Flycast core that uses Vulkan, will crash with the following error when the Retroarch overlay is in use (widgets, the Retroarch menu, etc):
```[INFO] [Vulkan]: QueuePresent failed, destroying swapchain.
[ERROR] [Vulkan]: Failed to create swapchain.```

If I disable widgets or don't invoke any overlay such as the Retroarch menu, then cores like Flycast will run just fine.

**Comment by Immersion95** [comment]
> This issue is still happening, but I think I have more context on what it is now. Any 3D console in Retroarch, such as N64 cores or the Flycast core that uses Vulkan, will crash with the following error when the Retroarch overlay is in use (widgets, the Retroarch menu, etc):
> 
> ```
> [INFO] [Vulkan]: QueuePresent failed, destroying swapchain.
> [ERROR] [Vulkan]: Failed to create swapchain.
> ```
> 
> If I disable widgets or don't invoke any overlay such as the Retroarch menu, then cores like Flycast will run just fine.

How do you disable ? I tried but it still crashes.

**Comment by m4xw** [comment]
Closing this as dupe now.
