### ISSUE TITLE
Segmentation fault with paraLLEl-RDP

### ISSUE THREAD

**Issue by Yqnn** [libretro/mupen64plus-libretro-nx#309]
Hello,
When I start the core, using using Vulkan and paraLLel plugins, it immediately crashes with a segfault error.
With other plugins it works well.
[mupen.log](https://github.com/libretro/mupen64plus-libretro-nx/files/5920499/mupen.log)

**Comment by Yqnn** [comment]
With mupen compiled in debug, there is the following error message:
```
[New Thread 0x7fbc86ffd700 (LWP 747)]
[New Thread 0x7fbc85da1700 (LWP 748)]
[ERROR]: VK_KHR_16bit_storage for SSBOs is not supported! This is a minimum requirement for paraLLEl-RDP.
[New Thread 0x7fbc855a0700 (LWP 749)]
[libretro ERROR] This device probably does not support 8/16-bit storage. Make sure you're using up-to-date drivers!
[Thread 0x7fbc86ffd700 (LWP 747) exited]
[Thread 0x7fbc85da1700 (LWP 748) exited]
retroarch: libretro-common/libco/amd64.c:127: crash: Assertion `0' failed.
[Thread 0x7fbc855a0700 (LWP 749) exited]
```
Seems it's related to the gpu driver.


I'm using mesa, with vulkan-drivers=intel option.
Is it supposed to be supported ?

**Comment by m4xw** [comment]
> MESA-INTEL: warning: Haswell Vulkan support is incomplete

Its not.
