### ISSUE TITLE
Can't build mupen64plus-next core on Odroid XU4

### ISSUE THREAD

**Issue by Cee123** [libretro/mupen64plus-libretro-nx#310]
For some reason, the building of this core will not work on the Odroid XU4

Screenshot of the error message received
![20210210_164858-20210210-165225131](https://user-images.githubusercontent.com/43462099/107487696-67d7fb00-6bc1-11eb-98a4-410e6d69f56b.jpg)

**Comment by m4xw** [comment]
Enable dynarec

**Comment by Cee123** [comment]
> 
> 
> Enable dynarec

Ok thanks, I'll try that and see if it works. I'll try and find the option for that under the Makefile.

**Comment by Cee123** [comment]
> 
> 
> Enable dynarec

That didn't help. I'm going to need more details than that. I can't see anywhere under the Makefile where I can just "Enable dynarec".

**Comment by Cee123** [comment]
Nope, not working.

**Comment by Cee123** [comment]
> 
> 
> Enable dynarec

How do I do that?

**Comment by Cee123** [comment]
make WITH_DYNAREC=arm
And
make WITH_DYNAREC=aarch64

Dont work either. Just brings up even more error messages.

**Comment by Cee123** [comment]
Well the issue seemed to be related to the version of Ubuntu I was trying to build it on. I was using an older version of Ubuntu Mate. I've since relfashed to a newer version of Ubuntu and it seems to be working beyond that point. But now I'm running into another issue, it keeps freezing when it reaches this point during the build process.

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/43462099/107743076-312dec00-6d4b-11eb-8d85-c00471ea9c73.jpg)

**Comment by Cee123** [comment]
Ok so i finally got it to compile. I was running sudo ./libretro-build.sh mupen64plus_next and it kept running out of memory. So i switched over to sudo make -j4 platform=odroid and it worked.
