### ISSUE TITLE
Bomberman 64: The Second Attack controller bug

### ISSUE THREAD

**Issue by BParks21** [libretro/mupen64plus-libretro-nx#313]
When playing this game with any configuration the analog seems to stop working correctly at random.

**Comment by m4xw** [comment]
Anything in the log?

**Comment by BParks21** [comment]
I'll reproduce and provide the log.

**Comment by BParks21** [comment]
@m4xw Ok here is the log. I've tested it with 3 different controllers. 
[retroarch.log](https://github.com/libretro/mupen64plus-libretro-nx/files/5999206/retroarch.log)

**Comment by HappehLemons** [comment]
This happens to me as well, and I've tested other emulators and they all have this same issue. I'm almost convinced it's a copy protection method.

**Comment by m4xw** [comment]
Thats good enough to label it as a upstream issue for me.
