### ISSUE TITLE
[Feature Request] standalone version

### ISSUE THREAD

**Issue by Toadfield** [libretro/mupen64plus-libretro-nx#314]
I hate using Retroarch,it would be cool to just use this as a standalone.

**Comment by m4xw** [comment]
duplicate

**Comment by Toadfield** [comment]
Can you give me the link of the original feature request?
If I search for "standalone",then I can't find anything.

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/issues/100
