### ISSUE TITLE
Threaded renderer blocks input

### ISSUE THREAD

**Issue by bladeSk** [libretro/mupen64plus-libretro-nx#317]
When I enable the threaded renderer, the core is no longer able to receive any input and neither is Retroarch, so it's not even possible to turn off the option without editing the config file manually.

I'm on Retroarch 1.9.0, Mupen64Plus-Next (2.1-OpenGL b494ebf), HOS 11.0.1, Atmosphére 0.18.1.

**Comment by m4xw** [comment]
Set poll behaviour to early in retroarch.
I try to force it in the core but that doesnt seem to work

**Comment by bladeSk** [comment]
OK, thanks. It would be helpful if you could mention this in the help text below the option, since forcing the poll behavior doesn't work.

**Comment by m4xw** [comment]
Good suggestion, ideally we fix whats up with the frontend just ignoring what I tell it tho
