### ISSUE TITLE
How to start the Transfer Pak?

### ISSUE THREAD

**Issue by Arlisbloxer05** [libretro/mupen64plus-libretro-nx#318]
As the title suggests, I'm having trouble with getting the Transfer Pak to run. I select the save file first, then the GBC rom, then the N64 rom, then I click the Start Transfer Pak button. Screen goes black for a few seconds but then it immediately goes back to the retroarch menu saying no items. Am I doing something wrong?

**Comment by m4xw** [comment]
Its a frontend bug on static platforms (like switch), same thing with 64dd and simliar workaroud.

If you have ROM.n64, place the GB ROM named ROM.n64.gb (saveram would be ROM.n64.sav), then just Load Content ROM.n64 and it will load it.
Make sure you switch your pak to "transfer" in the core options for the game to detect it.

**Comment by Arlisbloxer05** [comment]
Hm, interestingly enough i cant change the pak options in core options. there's no option for it anywhere...

**Comment by m4xw** [comment]
Does the core version include 9ae6f16 in the bottom left?

**Comment by Arlisbloxer05** [comment]
Yep, it does

**Comment by m4xw** [comment]
Then you look wrong.

**Comment by Arlisbloxer05** [comment]
i look wrong? what do my looks have to do with something not working?
