### ISSUE TITLE
How is the transferpack working?

### ISSUE THREAD

**Issue by Conan179** [libretro/mupen64plus-libretro-nx#326]
Is it permissible to ask how exactly it is used? I loaded Pokemon Stadium, assigned 1 Transfer Pack to the controller in the Retroarch settings, and then wanted to load my Pokemon Crystal. But I can neither choose my game nor the sav. Retroarch 1.9.0 Mupen64Plus-Next 9ae6f16
![2021-03-21 10 37 30](https://user-images.githubusercontent.com/1906242/111904865-3c122580-8a49-11eb-9fdc-05227eeba150.jpg)

**Comment by m4xw** [comment]
You need to load it together with the game.
If it doesnt show you have the wrong file extensions.

**Comment by Conan179** [comment]
i have try red.gb and kristal.gbc both are dont see at the menu.

**Comment by m4xw** [comment]
Pic

**Comment by m4xw** [comment]
Fwiw heres wip updated docs https://github.com/libretro/docs/pull/581/files

**Comment by Conan179** [comment]
here
![2021-03-21 14 09 00](https://user-images.githubusercontent.com/1906242/111906067-1daf2880-8a4f-11eb-888a-5b2f1175fee2.jpg)
old 9ae6f16 version
![2021-03-21 14 07 47](https://user-images.githubusercontent.com/1906242/111906081-2c95db00-8a4f-11eb-9bec-4a75519276a8.jpg)
after update to 8fb4742
![2021-03-21 14 09 48](https://user-images.githubusercontent.com/1906242/111906100-40d9d800-8a4f-11eb-8b5e-f30cdde47153.jpg)

**Comment by Conan179** [comment]
![2021-03-21 14 41 46](https://user-images.githubusercontent.com/1906242/111907032-d70ffd00-8a53-11eb-944d-e1e1d5187749.jpg)
and blackscreen and back to menu.
![2021-03-21 14 45 56](https://user-images.githubusercontent.com/1906242/111907098-1fc7b600-8a54-11eb-91ba-dc0259750df9.jpg)

I followed the instructions exactly.

**Comment by Conan179** [comment]
debug log wrote this:
Special game type: N64 Disk Drive
  Ident: ndd
  ID: 1
  Content:
[INFO]     Disk (required)
[INFO]     Cartridge (required)
[INFO] Subsystem ID: 1
Special game type: N64 Transferpak
  Ident: gb
  ID: 2
  Content:
[INFO]     Gameboy RAM (required)
[INFO]     Gameboy ROM (required)
[INFO]     Cartridge (required)
[INFO] Subsystems: 2
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] [SRAM]: SRAM wird nicht gespeichert.
[INFO] [Playlist]: Lade Verlaufs-Datei: [/retroarch/content_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Favoritendatei wird geladen: [/retroarch/content_favorites.lpl].
[INFO] Got AppletHook OnFocusState - new focus state is 1
[INFO] [Subsystem]: Setting current subsystem to: 1(gb) Content amount: 3
[INFO] [Subsystem]: Subsystem id: 1 Subsystem ident: gb Content ID: 0, Content Path: /retroarch/poke/gelb.sav
[INFO] [Subsystem]: Setting current subsystem to: 1(gb) Content amount: 3
[INFO] [Subsystem]: Subsystem id: 1 Subsystem ident: gb Content ID: 1, Content Path: /retroarch/poke/gelb.gb
[INFO] [Subsystem]: Setting current subsystem to: 1(gb) Content amount: 3
[INFO] [Subsystem]: Subsystem id: 1 Subsystem ident: gb Content ID: 2, Content Path: /retroarch/poke/Stadium64.z64
[INFO] [CONTENT LOAD]: Updating firmware status for: /retroarch/cores/mupen64plus_next_libretro_libnx.nro on /Roms/system
[INFO] [CORE]: Kein Inhalt, starte Dummy-Core.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] Threaded video stats: Frames pushed: 1142, Frames dropped: 0.

**Comment by m4xw** [comment]
Ah thats on Switch.
You encounter a RA bug. Use the alternate way in the doc I linked, implemented that specifically for switch.

**Comment by Conan179** [comment]
😢
Oh sorry, ok I'll test it.

**Comment by Conan179** [comment]
@m4xw the alternate way is working.
![2021-03-21 17 16 40](https://user-images.githubusercontent.com/1906242/111913708-a5a52a80-8a6f-11eb-9613-5dde23298367.jpg)
Kristall on Stadium2
![2021-03-21 17 25 06](https://user-images.githubusercontent.com/1906242/111913720-b786cd80-8a6f-11eb-9fc2-c792f9ec1fb8.jpg)
Yello on Stadium1
(the Gameboy towers on both games (to play the gb game on the TV Screen) is not working, the framerate are going to tge ground...)
![2021-03-21 17 16 59](https://user-images.githubusercontent.com/1906242/111913873-16e4dd80-8a70-11eb-8ce9-310ee7c0c5e0.jpg)
![2021-03-21 17 25 34](https://user-images.githubusercontent.com/1906242/111913875-18160a80-8a70-11eb-834c-e804e8cc097b.jpg)

Thank for your Help and im sorry for my Noob question

**Comment by m4xw** [comment]
Yea GB Tower isn't working on Standalone either, not sure whats up with it.
