### ISSUE TITLE
Corrupted Text Boxes in Ogre Battle 64

### ISSUE THREAD

**Issue by alessandropaggi** [libretro/mupen64plus-libretro-nx#329]
I'm running lr-mupen64plus-next (`a6a6bfd56c8a8d6077182c280bf9eb33c7fba0e8`) on RetroPie (Pi 4), and I've noticed that the text boxes in `Ogre Battle 64 - Person of Lordly Caliber (USA).n64` look weird (see attached images).
I think it's the same issue reported [here](https://github.com/gonetz/GLideN64/issues/1047).

![Ogre Battle 64 - Person of Lordly Caliber (USA)-210408-001659](https://user-images.githubusercontent.com/34541143/113941772-08344f80-9800-11eb-8bca-9234dad0c1eb.png)
![Ogre Battle 64 - Person of Lordly Caliber (USA)-210407-233202](https://user-images.githubusercontent.com/34541143/113940831-652f0600-97fe-11eb-9adf-01f687ee11c0.png)

**Comment by m4xw** [comment]
Yea that looks like a upstream issue

**Comment by alessandropaggi** [comment]
The issue appears fixed in upstream PR [2470](https://github.com/gonetz/GLideN64/pull/2470), but it still present in lr-mupen64plus-next GLideN64.

**Comment by alessandropaggi** [comment]
It is fixed now.
