### ISSUE TITLE
Crash when starting core with ParaLLEl RDP

### ISSUE THREAD

**Issue by mariomadproductions** [libretro/mupen64plus-libretro-nx#330]
No problem with other video plugins, ParaLLEl N64 libretro core or [m64p](https://github.com/loganmc10/m64p)
Platform: Linux Mint 20.1
RetroArch version: 1.9.1
Mupen64Plus-Next version: 2.2-Vulkan a6a6bfd
[Mupen64Plus-Next.opt.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/6285389/Mupen64Plus-Next.opt.txt)
[log.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/6285407/log.txt) (using `retroarch --verbose --log-file=log.txt`)

**Comment by m4xw** [comment]
Not supported

**Comment by mariomadproductions** [comment]
Oh, I didn't notice that. It should be using my Geforce GT 620.

**Comment by mariomadproductions** [comment]
@m4xw Oh, I didn't notice that. It should be using my Geforce GT 620. Why is it choosing the integrated graphics?
