### ISSUE TITLE
[Misc] Support for PI_STATUS_INTERRUPT

### ISSUE THREAD

**Issue by m4xw** [libretro/mupen64plus-libretro-nx#331]
As per fraser on Discord64
```
That being said there is an undocumented bit that is valid on hardware and cen64, but no other emulator has chosen to support it. 
PI_STATUS_INTERRUPT 
Here is how I know about it https://github.com/tj90241/n64chain/issues/3
There isn't much documentation on this bit ANYWHERE.
https://github.com/n64dev/cen64/blob/1b31ca9b3c3bb783391ab9773bd26c50db2056a8/pi/controller.c#L46
```

Comes at no cost, literally nothing existing uses it so low prio.

**Comment by loganmc10** [comment]
https://github.com/mupen64plus/mupen64plus-core/pull/868

**Comment by m4xw** [comment]
@loganmc10 Thanks, will close this when I do a rebase once Gillou is finally ready with the dynarec changes.
Just curious: Did a homebrew rom u tested spin on it? :P
