### ISSUE TITLE
Overscan crop leaves black bars on top and bottom of screen

### ISSUE THREAD

**Issue by mariomadproductions** [libretro/mupen64plus-libretro-nx#335]
Compare before applying overscan to after applying overscan:
![Screenshot from 2021-04-22 18-59-03](https://user-images.githubusercontent.com/9919020/115766747-38532500-a3a0-11eb-9893-954e1ff7877b.png)
![Screenshot from 2021-04-22 19-23-09](https://user-images.githubusercontent.com/9919020/115766752-39845200-a3a0-11eb-8d64-94276e6d9097.png)

It works fine for the left and right, but not for the top and bottom. Same result nomatter if RetroArch's automatic overscan crop is turned on or off, and nomatter if RetroArch's integer scanling is on or off.

**Comment by m4xw** [comment]
If you think something is wrong, make a gliden issue.
This is not a core issue if any.

**Comment by Sanaki** [comment]
This may be a configuration issue of some sort. I tried US, EU, and AUS versions. With 6/14/10/8 for US and 9/12/11/11 for EU and AUS, I have no black bars whatsoever. Maybe you have aspect ratio manually specified rather than core-provided in retroarch itself?

**Comment by mariomadproductions** [comment]
Yeah I'm using 6/13/9/8 for the USA ROM (default in-game screen scale). I get the same result in m64p. You know, I think this is just a stupid mistake on my part. Its simply that my screens aspect ration doesn't match the aspect ration of the emulator output, so its only natural there would be black bars. Sorry for wasting your time here.

**Comment by m4xw** [comment]
Might wanna close the gliden issue then
