### ISSUE TITLE
[Linux] Crash when closing game using transfer pak

### ISSUE THREAD

**Issue by Sanaki** [libretro/mupen64plus-libretro-nx#337]
Using the naming scheme method, reads from the transfer pak work fine, but on closing the game/core, retroarch will crash reliably. Based on timing, this appears to be related to attempting to write the GB save. The GB save is never succesfully updated.

```
[libretro INFO] mupen64plus: Stopping emulation.
[libretro INFO] mupen64plus: R4300 emulator finished.
corrupted double-linked list
Aborted (core dumped)
```
Using the subsystem method, the error changed to `double free or corruption (!prev)`, but that may just be coincidence.

Linux Mint 19.3 x86_64 (kernel 5.4.0-72)
Compiled using GCC 10.3.0

**Comment by m4xw** [comment]
I've heard of that before. Totally forgot about it.
Can you run with gdb and get a trace?

**Comment by m4xw** [comment]
Lol for some reason i read the title as rumble pak, nvm the title edit.

**Comment by Sanaki** [comment]
```gdb
[libretro INFO] mupen64plus: R4300 emulator finished.
corrupted double-linked list

Thread 1 "retroarch" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffecc7c921 in __GI_abort () at abort.c:79
#2  0x00007fffeccc5967 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fffecdf2b0d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fffecccc9da in malloc_printerr (str=str@entry=0x7fffecdf0c3a "corrupted double-linked list") at malloc.c:5342
#4  0x00007fffeccd425f in _int_free (have_lock=0, p=<optimized out>, av=0x7fffed027c40 <main_arena>) at malloc.c:4325
#5  __GI___libc_free (mem=<optimized out>) at malloc.c:3134
#6  0x00007fffb55ec775 in close_file_storage (fstorage=0x7fffba36cf38 <l_gb_carts_data+152>) at mupen64plus-core/src/backends/file_storage.c:76
#7  0x00007fffb5631348 in release_gb_rom (opaque=0x7fffba36cf30 <l_gb_carts_data+144>) at mupen64plus-core/src/main/main.c:1077
#8  0x00007fffb5632a92 in main_run () at mupen64plus-core/src/main/main.c:1478
#9  0x00007fffb55eb81d in CoreDoCommand (Command=M64CMD_EXECUTE, ParamInt=0, ParamPtr=0x0) at mupen64plus-core/src/api/frontend.c:188
#10 0x00007fffb56e3b5b in EmuThreadFunction (param=0x555557af0750) at libretro/libretro.c:408
#11 0x00007fffb57c0676 in co_init () at libretro-common/libco/amd64.c:121
#12 0x0000000000000000 in  ()
```

**Comment by m4xw** [comment]
thanks

**Comment by m4xw** [comment]
https://git.libretro.com/libretro/mupen64plus-libretro-nx/-/pipelines/28018 @Sanaki

**Comment by Sanaki** [comment]
No change in behavior.

**Comment by m4xw** [comment]
You sure its the same crash?
I duped the buf so it shouldnt double free unless its maybe in a error case?
Can u give me a updated trace with that binary?

**Comment by Sanaki** [comment]
Literally the same crash. I checked gdb and didn't post it because it was identical to the prior one. I can pop it back in and grab that for you anyway if you'd prefer.

**Comment by m4xw** [comment]
Spooky, i must be overseeing smth obvious

**Comment by m4xw** [comment]
https://git.libretro.com/libretro/mupen64plus-libretro-nx/-/jobs/580589/artifacts/browse @Sanaki

**Comment by Sanaki** [comment]
Ayy, that one worked.
