### ISSUE TITLE
low performance on extremely low end hw

### ISSUE THREAD

**Issue by Svadkos** [libretro/mupen64plus-libretro-nx#34]
It's not some little lag it's more like number of static pictures which change from time to time. 
My hardware is pretty old, but it can run GLideN64 plugin in standalone mupen64plus.
Same problem I experience on this https://github.com/libretro/mupen64plus-libretro core, while parallel core runs well (except angrylion plugin, but it's still playable).

```
CPU:       Topology: Quad Core model: AMD Athlon X4 750K bits: 64 type: MCP arch: Piledriver rev: 1
           L2 cache: 2048 KiB
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 27157
           Speed: 2499 MHz min/max: 1400/3400 MHz Core speeds (MHz): 1: 2774 2: 3368 3: 2271 4: 2251
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E]
           vendor: PC Partner Limited driver: radeon v: kernel bus ID: 01:00.0
           Display: wayland server: X.Org 1.20.4 driver: radeon resolution: 1920x1080~60Hz
           OpenGL: renderer: AMD VERDE (DRM 2.50.0 5.0.0-arch1-1-ARCH LLVM 7.0.1) v: 4.5 Mesa 18.3.4
           direct render: Yes
```

**Comment by m4xw** [comment]
Your best bet is to wait https://github.com/libretro/mupen64plus-libretro-nx/issues/4 , please note this core is prioritizing high end hw, it runs decently on a raspberry or even fullspeed on a underclocked nintendo switch (760MHz aarch64 CPU. 378MHz GPU).

**Comment by Svadkos** [comment]
This core doesn't use even this hardware. GPU is not used at all, CPU use is 20-25%. And then again same problem i experienced with the old core, and I can run GLideN64 fullspeed without problems.
> Your best bet is to wait #4 
Alright, I will test again when this issue is resolved.

**Comment by m4xw** [comment]
We use a ~3 year old version of GlideN64, so you have to run your tests with a ancient version ;)

**Comment by Svadkos** [comment]
Ah I see, that is always a problem with libretro cores to find out which version of emulator is actually in use.

**Comment by Jj0YzL5nvJ** [comment]
@Svadkos, [edit this line](https://github.com/libretro/mupen64plus-libretro-nx/blob/mupen_next/GLideN64/src/BufferCopy/ColorBufferToRDRAM_BufferStorageExt.cpp#L40) and add `GL_CLIENT_STORAGE_BIT` to solve your issue.

Info:
https://github.com/gonetz/GLideN64/issues/1561
https://github.com/gonetz/GLideN64/pull/1960

**Comment by Svadkos** [comment]
> [edit this line](https://github.com/libretro/mupen64plus-libretro-nx/blob/mupen_next/GLideN64/src/BufferCopy/ColorBufferToRDRAM_BufferStorageExt.cpp#L40) and add `GL_CLIENT_STORAGE_BIT` to solve your issue.

Sadly, it didn't help. I see there was another patch https://github.com/gonetz/GLideN64/pull/1735 and I can't even find files which was changed by that pull request in this repository.
Also I tried to start retroarch with `LIBGL_ALWAYS_SOFTWARE=1` and it worked much better.

**Comment by Jj0YzL5nvJ** [comment]
> Also I tried to start retroarch with `LIBGL_ALWAYS_SOFTWARE=1` and it worked much better.

Then try with `MESA_GL_VERSION_OVERRIDE=3.3COMPAT MESA_GLSL_VERSION_OVERRIDE=420 MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage` instead.

**Comment by Svadkos** [comment]
> Then try with `MESA_GL_VERSION_OVERRIDE=3.3COMPAT MESA_GLSL_VERSION_OVERRIDE=420 MESA_EXTENSION_OVERRIDE=-GL_ARB_buffer_storage` instead.

Nope, still the same lag and no gpu usage. 

Anyway, I've tested build from GLideN64 branch and lag is gone. There was visual glitch on N64 logo, and it crashed when I tried to switch to fullscreen, but those are for another issue.
