### ISSUE TITLE
Run-ahead isn't "re-enabled" on close content

### ISSUE THREAD

**Issue by bslenul** [libretro/mupen64plus-libretro-nx#340]
Mentioned here a while ago: https://github.com/libretro/RetroArch/issues/11116#issuecomment-668111891 but completely forgot about it :p 

Basically running a game with Mupen64Plus-Next core with run-ahead enabled and second instance will give a "Failed to load state. Run-ahead has been disabled." message, which is fine, however it doesn't "re-enable" run-ahead when you close content, so if you start another game with a different core that supports run-ahead you'll get the same message and it won't work... Only solution is to restart RetroArch :/

**Comment by m4xw** [comment]
and?

**Comment by bslenul** [comment]
And run-ahead should work again with other cores after using Mupen64Plus-Next, without having to restart RetroArch...

**Comment by m4xw** [comment]
Not a core problem

**Comment by bslenul** [comment]
I'm confused then, jdgleaver said "that looks like a genuine core error" on the issue I mentioned.
