### ISSUE TITLE
Backport NO_LIBCO from parallel-n64

### ISSUE THREAD

**Issue by kivutar** [libretro/mupen64plus-libretro-nx#341]
I see that parallel-n64 has a NO_LIBCO define to run the emulator without coroutines.
It was used for the emscripten build.

It would also be useful to run mupen in libretro frontends made in languages that can't support libco like Ludo in Go.

See https://github.com/golang/go/issues/39411

**Comment by m4xw** [comment]
No. emscripten is a lost cause rn anyway, i already have it running with the thr renderer etc but rendering is a mess
