### ISSUE TITLE
Feature Request: Graphics plugin for low-end systems

### ISSUE THREAD

**Issue by fpi1337** [libretro/mupen64plus-libretro-nx#344]
Hi,

just wanted to suggest the option to choose between multiple graphic plugins (which is already the case with angrylion and GLideN64) but keeping in mind low-end-systems. Since the core is a huge improvement over the old mupen64plus-core. The latter one always had problems to scale the predefined resolution when going in fullscreen mode. With the new core this isn't an issue anymore. Anyway, it would be really cool to have an option in terms of graphics which are more suited for older systems.

**Comment by m4xw** [comment]
glide branch is a thing, but from my testing a well configured gliden will be superior in performance on any fairly recent system.

**Comment by m4xw** [comment]
It will happen. I dont need a issue for this.

**Comment by fpi1337** [comment]
> It will happen. I dont need a issue for this.

very glad to hear that!!

> glide branch is a thing, but from my testing a well configured gliden will be superior in performance on any fairly recent system.

yep, I know that but for systems that are a little bit older but still "powerful" the lacking Open GL support of these graphic cards would cause some games to stutter or to crash while this has not to be the case when it comes to processing power and plugins. :-) I could imagine many users transforming their older workstations into a retor emulation station (including N64 emulation), failing to achieve this at the point where it comes to performance in terms of graphics. As you said: glide (in comparison to GLideN64) is a pretty nice plugin for older systems.

Anyway, very nice to hear that and thank you!
