### ISSUE TITLE
[Win] Retroarch freezes when loading relatively old save state

### ISSUE THREAD

**Issue by vinxi2** [libretro/mupen64plus-libretro-nx#346]
Hi everybody,
I recently loaded Diddy Kong Racing and was trying to restore a save state from August 2020. When I try to load it Retroarch just freeze.

The log just says:

[INFO] [State]: Loading state "F:\RetroArch\states\Diddy Kong Racing (Europe) (En,Fr,De).state", 16793412 bytes.
[INFO] [State]: Saving state "RAM", 16793440 bytes.

Thanks

**Comment by m4xw** [comment]
Savestate compat is never guaranteed.
