### ISSUE TITLE
[Android] Retroarch freezes when making a save state

### ISSUE THREAD

**Issue by DiaBomb** [libretro/mupen64plus-libretro-nx#347]
I tried far and wide to identify the cause, but I can't tell. It's not happening when loading a state. Every game I tried does the same (Banjo Kazooie, Majoras Mask, Star Fox) If the auto save and load on game start/stop options are enabled the same thing happens but again, only when closing the game, so it makes a save. Randomly, the save gets made successfully but when trying to save again either on the same slot or a new one the freeze happens again.

My Retroarch version is 1.9.4 and the core is 34aec88 running on vulkan GLES3

This only happens on android. On Windows, saving still works.

**Comment by m4xw** [comment]
thr gl on?

**Comment by DiaBomb** [comment]
Huh, I set the video driver and output both to gl, but the core is still using vulkan it seems (in the pause menu the core name says vulkan). Any other setting I'm missing?

**Comment by DiaBomb** [comment]
I must have overlooked something. It appears the freeze is caused by the "Save Runtime Log (Aggregate)" option. Only when that is on, Retroarch freezes when saving a state. And I thought I checked each option in the saving menu...

Either way, I guess it's "fixed" for me now

**Comment by m4xw** [comment]
sounce like a race when logging

**Comment by DiaBomb** [comment]
Probably playing Mario Kart on Job smh

**Comment by m4xw** [comment]
using a ancient ra version?
Try enable sounds in the menu in the RA settings

**Comment by fmcgarry** [comment]
> using a ancient ra version?
> Try enable sounds in the menu in the RA settings

This seems to work, thanks! 

For reference:
Settings->Audio->Menu Sounds. Enable all options. You should hear menu clicks now as you move through the menus.

For some reason I had a little bit of a hard time enabling "Mixer" first without crashing, so I just made sure it was enabled last.

**Comment by DiaBomb** [comment]
And that worked, I had to go into the config and set "audio_enable_menu" to true because setting it in Retroarch itself just crashes. Thankfully, the config file of RA isn't hidden.

**Comment by m4xw** [comment]
I use a api extension to exactly work around that issue... I might need to think of smth additional.
This might be a frontend regression tho, not sure.

**Comment by m4xw** [comment]
I dont think this should be a issue anymore?
Reopen if needed

**Comment by DiaBomb** [comment]
I just checked and turned the menu sounds back on again, and the issue is actually still happening. I updated both RetroArch and the core. Enabling the menu sounds setting still crashes retroarch. So this problem might be on their side. But strangely enough, now with either menu sounds on or off, the crash still happens. Even weirder is that before I changed anything, saving worked perfectly.

**Comment by eadmaster** [comment]
> And that worked, I had to go into the config and set "audio_enable_menu" to true because setting it in Retroarch itself just crashes. Thankfully, the config file of RA isn't hidden.

Same here,  this fix should me mentioned in the https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/README.md
