### ISSUE TITLE
Transfer Pak doesn't save/write into the .sav file.

### ISSUE THREAD

**Issue by DavidG777** [libretro/mupen64plus-libretro-nx#349]
First of all I'm not a coder or used to github, so I apologize if this is formatted wrong or something, and I'll provide any info if required.
I'm using the latest version of the core on the latest version of Retroarch (as of 06/16), with the transfer option enabled on Pokemon Stadium 2, using a Pokemon Crystal ROM and save file, using the filename method to load them.

If I make any changes to the save file in-game, such as moving items or Pokemon between boxes, and save, the changes will not be written to the GBC .sav file (the N64 file will save properly, but not the GBC save), and will be gone when I boot the core again. I think I have full read/write permissions, and I tried to do this with the save file on different folders too.

This does not happen on the NRage plugin using PJ64, that saves fine using the same ROMs/save.

I could not find a similar issue, sorry if this is a repost!

**Comment by m4xw** [comment]
I had that before fixed, maybe i broke smth again?
Currently working on a huge rebase, if u want to try it already https://cdn.discordapp.com/attachments/555706037412560909/854389448912666624/mupen64plus_next_libretro.dll
Will investigate if i can repro

**Comment by DavidG777** [comment]
Tried that version, didn't work still.

This could very well be some kind of file writing issue on my Retroarch installation. I looked over the net to see if anyone had this issue and couldn't find anything. I'll see if I can test it on a new RA install tonight.

**Comment by m4xw** [comment]
Should be fixed, reopen if persists. The build should be on the bot in ~3h at worst
