### ISSUE TITLE
Only 1P can play. Offline multiplayer impossible

### ISSUE THREAD

**Issue by rrocha9** [libretro/mupen64plus-libretro-nx#353]
Hi! I was running retroarch (1.9.0) on my Nintendo Swith and offline multiplayer worked perfectly. Now I upgraded Retroarch to (1.9.6) and only player 1 can play. I can connect the other controllers but only the home button and the capure button work. The games I use are Pokemon Stadium and Pokemon Stadium 2. What can I do?

**Comment by m4xw** [comment]
Not a core issue
