### ISSUE TITLE
Core crashes RetroArch when closing content on xbox one/series consoles

### ISSUE THREAD

**Issue by danprice142** [libretro/mupen64plus-libretro-nx#354]
Im hoping this can be fixed its only this core and Flycast that still do this psx2 and dolphin cores have been fixed and no longer do this

**Comment by m4xw** [comment]
Said platform is not officially supported.

**Comment by danprice142** [comment]
not supported on xbox or the UWP retroarch? Because it does the when using the UWP on Windows too

**Comment by m4xw** [comment]
UWP itself is not officially supported for mupen next.
I don't use it myself and support for it is only on a branch currently, issues are to be expected.
