### ISSUE TITLE
Linux - Rogue Squadron Hang Black Screen

### ISSUE THREAD

**Issue by 7oxicshadow** [libretro/mupen64plus-libretro-nx#36]
I realise that this is still under heavy development but I just wanted to mention an issue that I have seen on Linux.

I have built from the latest source (Commit : 07f09151a439be1a60db8cdd61249b8403d86df2) and the core appears to work well for most games (top gear rally is working great and that used to have a terrible stuttering issue) but when I try rogue Squadron it just hangs at a black screen at startup.

The UI and everything works so it hasn't frozen, it just seems to halt the emulation?

Is there any debug or anything that I can enable to provide any further information to yourself?

[libretro INFO] mupen64plus: Goodname: Star Wars - Rogue Squadron (U) (M3) (V1.0) [!]
[libretro INFO] mupen64plus: Name: Rogue Squadron      
[libretro INFO] mupen64plus: MD5: 47CAC4E2A6309458342F21A9018FFBF0
[libretro INFO] mupen64plus: CRC: 66A24BEC 2EADD94F

Fedora 29 64 bit (KDE)
i7 6700K @ 4.5Ghz
32GB Ram

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/tree/GLideN64

**Comment by m4xw** [comment]
Let me know if it works or if u have trouble building

**Comment by 7oxicshadow** [comment]
That worked great. Builds fine :)

Sorry for raising a bug. I didnt notice the GlideN64 branch.

Thanks for your work on this

**Comment by m4xw** [comment]
No problem, glad it works.
If it is a valid bug i would reopen ;)
