### ISSUE TITLE
Potential error(e.g., deadlock, ill peformance) due to the unreleased lock savestates_lock

### ISSUE THREAD

**Issue by jenny-cheung** [libretro/mupen64plus-libretro-nx#362]
Hi, developers, thank you for your checking. The lock `savestates_lock` may not be correctly released if the` gzopen ` fails. Finally, the method returns with the unreleased lock. The fix is to insert `pthread_mutex_unlock(&savestates_lock);`  before returning.

https://github.com/libretro/mupen64plus-libretro-nx/blob/fb0b9c52b892d0af2016f97d314fe1473ee9c77b/mupen64plus-core/src/main/savestates.c#L1586

```
static void savestates_save_m64p_work(struct work_struct *work)
{
   ...;

#ifdef USE_SDL。// the lock
    SDL_LockMutex(savestates_lock);
#else
    pthread_mutex_lock(&savestates_lock);
#endif

    ...;
    f = gzopen(save->filepath, "wb");

    if (f==NULL)
    {
        main_message(M64MSG_STATUS, OSD_BOTTOM_LEFT, "Could not open state file: %s", save->filepath);
        free(save->data);
        return;  //return without releasing
    }

    gzres = gzwrite(f, save->data, save->size);
    if ((gzres < 0) || ((size_t)gzres != save->size))
    {
        main_message(M64MSG_STATUS, OSD_BOTTOM_LEFT, "Could not write data to state file: %s", save->filepath);
        gzclose(f);
        free(save->data);
        return;  //return without releasing
    }
 ...;
}
```

Best,

**Comment by m4xw** [comment]
that code is never compiled in

**Comment by jenny-cheung** [comment]
@m4xw, So, It is a true bug? It warns by a static analysis we developed. We would like to know how precise it is. Thank you for your help!

**Comment by m4xw** [comment]
its behind a ifdef that will never trigger for this project.
The core does everything in-memory and passes it to the frontend.
You are looking at dead code from standalone.

**Comment by m4xw** [comment]
As you can see: https://github.com/libretro/mupen64plus-libretro-nx/blob/fb0b9c52b892d0af2016f97d314fe1473ee9c77b/mupen64plus-core/src/main/savestates.c#L1589

We only use the libretro codepaths, this is ifndef!

**Comment by jenny-cheung** [comment]
OK. Thank you for your detailed reply.
