### ISSUE TITLE
N64 Games - Black Screen (Audio) with graphical glitches.

### ISSUE THREAD

**Issue by AteNoodles** [libretro/mupen64plus-libretro-nx#363]
Running RetroArch on an Xbox Series S, Mupen64plus core throws a black screen at me when running games using either GL or DX11. Has been noted that's what happens when you're trying to run a GLES2 core and a GLES3 capable system.

**Comment by m4xw** [comment]
I dont officially support xbox and you wont find any recent builds provided by mself.
