### ISSUE TITLE
When Rom is not working... 

### ISSUE THREAD

**Issue by nayasis** [libretro/mupen64plus-libretro-nx#372]
I frustrated all of my N64 roms are not working suddenly.

I found that follow option (in **retroarch.cfg**) caused this disaster and many people did experience like me.
```
driver_switch_enable = "false" -> driver_switch_enable = **"true"**
```

mupen works only gl1 driver ?? and above option change your driver from current (Vulkan, dxd11 ... ) to just one that works core properly.

Hope it helps you. Thank you :)

**Comment by m4xw** [comment]
"suddenly".ü
You switched the gfx plugin. Driver switch behaviour is not officially supported by me.
