### ISSUE TITLE
Unable to map C button

### ISSUE THREAD

**Issue by robhol** [libretro/mupen64plus-libretro-nx#373]
I'm on Next 2.3 Vulkan, running in RetroArch 1.9.9 (stable).

When trying to bind a button on my controller to C up/down (C Button Y +/-), nothing happens when that button is pressed. The same physical button works fine when set to any other button, d-pad or the control stick.

(The right analog stick is bound to C Button X/Y +/- by default, and all of these work as expected. I'm not sure what that means...)

Please let me know if any more information is needed.

**Comment by Papermanzero** [comment]
You need to activate independent C buttons in the options menu

**Comment by robhol** [comment]
Thank you. I've activated it, but the button still does not work for "vertical" C buttons, only left and right. 
Are there any other relevant options? I am not using "C buttons mode" and nothing is bound to it.

**Comment by Papermanzero** [comment]
You should not use C X/Y axis. 
If you use the C Buttons for mappings it should work.
The C Button Mode provides C1 - C4 Buttons which can be mapped independently.
Could you provide a screenshot of your mappings?

**Comment by robhol** [comment]
I didn't notice right away that enabling independent controls actually made "C Up" etc show up. Binding the buttons to these and the analogs to the XY axes works, though I'm still confused that the horizontal "C axis" still seems to work for buttons whereas the vertical does not.

Anyway, that solves my issue - thank you very much!
