### ISSUE TITLE
Rumble not working and Rumble Feature Request

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#374]
With Retroarch 1.9.8 and Windows 10 I updated the core to the latest release.
However it seems all rumble games (like Starfox64, Snowboard Kids, Gauntlet Legends etc.) are not working with rumble.
The emulator detects the rumble pak however the Xbox360 controller does not rumble.

Moreover is it possible to increase or deacrease the rumble intesity?
That would be a cool a feature to change the intesity of the rumble.

**Comment by m4xw** [comment]
Rumble is working, probably a frontend issue.
Rumble intensity is managed by the frontend too

**Comment by Papermanzero** [comment]
Strange both settings cannot changed via frontend with the latest releases.

**Comment by m4xw** [comment]
On switch f.e. the rumble intesity is maxed in the input driver backend btw

**Comment by Papermanzero** [comment]
thanks @m4xw 
Will raise a request to the frontend

by the way. thanks a lot for this awesome awesome emulator. best n64 emulator out there.
hands down 😊

**Comment by m4xw** [comment]
I will ask internally
