### ISSUE TITLE
mupen shader cache issue on xbox series x

### ISSUE THREAD

**Issue by Nejsplitter** [libretro/mupen64plus-libretro-nx#378]
on mupen64plus next gles3 on xbox series x retroarch there is no option to compile a shader cache while playing, i even tried adding a "compileshaders"(cant remember exactly how its called) line into the mupen64plusnext.opt file in retroarch configs and still nothing.

**Comment by m4xw** [comment]
I dont support xbox officially at this point in time and the xbox capable builds are far behind.

**Comment by Nejsplitter** [comment]
understood thank you :)
