### ISSUE TITLE
Perfect dark pause screen error  mupen xbox series x

### ISSUE THREAD

**Issue by Nejsplitter** [libretro/mupen64plus-libretro-nx#379]
perfect dark on default mupen gles3 settings on the xbox series x retroarch, when the game is paused the background should turn into a blurry version of what the player was looking at as the start button was pressed, the issue is that this does not happen and instead the display just turns into a solid colour. This is the only issue so far that i have not been able to replicate on gles3 mupen android so i assume this may have something to do with the D3D to GL ANGLE calls.

**Comment by m4xw** [comment]
I dont support xbox officially at this point in time and the xbox capable builds are far behind.

**Comment by m4xw** [comment]
Lemme note tho, theres plan to support it, but just not for the time being ;)

**Comment by Nejsplitter** [comment]
its fine tbh im just nitpicking minor things, testing :) , everything works to a great level on xbox series consoles as far as iv seen now and everything works flawlessly on windows and android anyway which is optimal for most users so thank you @m4xw  for everything you guys do :) its a thing of beauty at this stage hehe , cheers
