### ISSUE TITLE
Android mupen gles 3: Mario Golf: Animated effects render in front of course

### ISSUE THREAD

**Issue by Nejsplitter** [libretro/mupen64plus-libretro-nx#382]
Edit: fixed in latest Gliden64

mupen64plus next gles3 with gliden64: start the game and select training mode and select hole 4, this issue happens in a few levels but thats the most visible one, they seem to have solved it here: https://github.com/gonetz/GLideN64/issues/312 but the issue persists on android gles 3 mupen retroarch

![5332f0ae-d10a-11e4-9eb4-1bbdad18cd82](https://user-images.githubusercontent.com/85600282/133654709-611657c4-702e-4125-af10-3dd9e40cf685.png)

**Comment by Nejsplitter** [comment]
@gonetz @fzurita how did you go about fixing this? and why do you think it does not work in this case

**Comment by m4xw** [comment]
Note: Some stuff in my core is a lot more complicated for GL(ES) because of the GL state machine that I use.

**Comment by Nejsplitter** [comment]
i think i have an isea what the issue is, il report back after testing

**Comment by fzurita** [comment]
I didn't do anything special in Android to fix it. The same fix that Gonetz did in PC fixed it for Android.

**Comment by Nejsplitter** [comment]
@fzurita  i just tested on your mupen ae latest and the issue is there too on default gliden64 very accurate, also tried to toggle depth buffer options and n64 depth compare but the issue persists on your build too

**Comment by fzurita** [comment]
Interesting, I wonder what the difference is.

**Comment by Nejsplitter** [comment]
maybe an unnoticed regression somewhere ?

**Comment by fzurita** [comment]
Or maybe it could be related to this: https://github.com/mupen64plus-ae/mupen64plus-ae/blob/bbd5dc15ee48a761087ff50baaa5b64c657bb2e2/app/src/main/assets/mupen64plus_data/GLideN64.custom.ini#L147

Depth to RDRAM is being forced to off, I wonder if that's right.

**Comment by Nejsplitter** [comment]
just tested on windows too, issue persists

**Comment by fzurita** [comment]
What about project 64?

**Comment by Nejsplitter** [comment]
i will try pj64 and report back

**Comment by Nejsplitter** [comment]
by the way gonetz mentioned that depth to rdram needs to be off for the in game transitions to work correctly : https://github.com/gonetz/GLideN64/issues/1293

**Comment by Nejsplitter** [comment]
@fzurita  @gonetz i just tested on project 64 and mupen64plus on windows, project 64 is a more recent one and mupen 64 plus is an older one, on project 64 the issue is there but on mupen64plus the issue is not there

**Comment by Nejsplitter** [comment]
do you use the most recent gliden64 in your mupen ae builds ?

**Comment by fzurita** [comment]
I do.

**Comment by Nejsplitter** [comment]
if you have time, maybe you can try replicate it on your phone too or computer

**Comment by Nejsplitter** [comment]
if you have time, maybe you can try replicate it on your phone too or computer, i made an issue on the gliden64 github main.

**Comment by fzurita** [comment]
To fix, the easiest path would probably be to find which revision broke it and go from there.

**Comment by Nejsplitter** [comment]
@fzurita  hmm something interesting just now, it seems enabling n64 depth compare solves the original issue but enabling it creates a new issue where the player model and water and other things are rendered/unrendered as you move the camera, its like the same problem just switches to affect other assets while fixing the original

**Comment by Nejsplitter** [comment]
This issue is being dealt with properly upstream so it can be closed here.

issue main:https://github.com/gonetz/GLideN64/issues/2577

**Comment by Nejsplitter** [comment]
Issue fixed in latest GlideN64

**Comment by m4xw** [comment]
Will close it when i rebased gliden code

**Comment by Nejsplitter** [comment]
understood, thank you, the latest gliden64 has very recently fixed some major issues :)

**Comment by Nejsplitter** [comment]
@m4xw awsome to see you on digital foundry recently 😀 are you on discord by any chance ?

**Comment by Nejsplitter** [comment]
@m4xw  yay finally fixed on the test angle updated build you sent me earlier
