### ISSUE TITLE
Less accurate blending set to off causes bugs

### ISSUE THREAD

**Issue by BParks21** [libretro/mupen64plus-libretro-nx#396]
When leaving the core option "less accurate blending" off using the GLideN64 RDP plugin certain cursors are not being displayed in Mario Kart 64. There are issues in other games as well. I used to leave this setting off and these bugs did not occur. When turning less accurate blending on the issues are fixed. You'd think having an option claiming to be "less accurate" on would cause issues, not the opposite. This doesn't seem right to me. The first image is with the option off and the second is with it on.

![Screenshot (14)](https://user-images.githubusercontent.com/12180630/139186716-dbe81a8c-5607-4892-8745-9f8e2f7822b2.png)
![Screenshot (15)](https://user-images.githubusercontent.com/12180630/139186723-da645a72-facd-4fe2-b45b-663edcfcd8ec.png)

.

**Comment by m4xw** [comment]
Upstream if any.
Could check one of my branches if its already fixed.
I recommend testing w/ standalone, if you can reproduce just open up a gliden issue.
If you can't reproduce, let me know and we re-open.

**Comment by TheEarthrise** [comment]
Same problem with the latest nightly build, I can't believe that this is still not fixed.

**Comment by roguen1** [comment]
2025, almost 2026 and this issue still exists, this is insane, I simply gave up and left the option enabled forever, so that at least there would be as few bugs as possible, because I tried many games with “less accurate blending” turned off, and they all had some kind of serious graphical bugs

**Comment by m4xw** [comment]
<img width="83" height="96" alt="Image" src="https://github.com/user-attachments/assets/3393e9b0-3c39-4061-bf08-d77a4855c7fc" />

**Comment by BParks21** [comment]
Unfortunate
