### ISSUE TITLE
paper-mario + glide64: works with mupen64plus, buggy with mupen64plus-libretro-nx

### ISSUE THREAD

**Issue by legluondunet** [libretro/mupen64plus-libretro-nx#400]
Hello,

paper-mario does not work correctly with libretro mupen64plus-libretro-nx and glide64 plugin:

![ArcoLinux_2021-11-12_22-08-58](https://user-images.githubusercontent.com/325405/141534789-ce1492cb-c02e-4c41-8e3d-999950d5fa2d.png)
no logo at start and white background on main menu

![ArcoLinux_2021-11-12_22-09-12](https://user-images.githubusercontent.com/325405/141534788-4777916a-a18c-4410-9482-dc38e7ab106a.png)
trees glitchy

![ArcoLinux_2021-11-12_22-09-24](https://user-images.githubusercontent.com/325405/141534784-222c8002-bb19-4406-ad29-be7dc9d35ce5.png)
glitchy sprites in the background

The same screenshots with mupen64plus and glide64 plugin compiled from git today (12 november 2021):

![ArcoLinux_2021-11-12_22-12-44](https://user-images.githubusercontent.com/325405/141535173-b53cd059-c87c-495a-a407-987f8c1df9a3.png)

![ArcoLinux_2021-11-12_22-13-03](https://user-images.githubusercontent.com/325405/141535172-8674b95a-7b2c-453e-b37f-83b16a8eb6e7.png)

![ArcoLinux_2021-11-12_22-13-15](https://user-images.githubusercontent.com/325405/141535168-3147b16f-d5ca-4259-a112-6c500ac4d204.png)

Glide64 plugin is the only graphic plugin that supports HD textures pack.
Could you update this module with latest mupen64plus sources?

**Comment by m4xw** [comment]
Glide is not supported yet, lol.
You mean gliden? then checkout rebase_gliden branch and let me know how it goes.

**Comment by legluondunet** [comment]
I just compiled gliden plugin and tested Paper Mario, I can not reproduce previous issues.
When this new branch will be available for retroarch users?

**Comment by m4xw** [comment]
Whenever i get to fix some small leftover issues, soon enough I hope

**Comment by m4xw** [comment]
Will be included soon.. wrapped up a new rebase on the "rebase" branch on gitlab thats scheduled for merge
