### ISSUE TITLE
glide64 plugin: black screen when alternate fullscreen/window

### ISSUE THREAD

**Issue by legluondunet** [libretro/mupen64plus-libretro-nx#401]
Hello,
when I launch a N64 rom with libretro mupen64plus-libretro-nx and glide64 graphic plugin, when I press F key to enter fullscreen or exit fullscreen, there is no more video emulation, screen is black, I can only hear audio.
If I press F1 I can see menu. 
But there is nothing I can do to obtain game screen again, I can only close game.
I can not reproduce this bug with latest mupen64plus emulator.
Thank you for your help.

**Comment by m4xw** [comment]
again i hope u mean gliden.
threaded video on?

**Comment by legluondunet** [comment]
if I set threaded video to on, the game does not start and it crashes retroarch.

**Comment by legluondunet** [comment]
option "threaded video" on or off, I tried both, same result, black screen and I can hear audio.
I can not reproduce this issue with parallell core.

**Comment by legluondunet** [comment]
I joined you fully retroarch log. But when I change fullscreen to window or window to fullscreen, no message appearing in terminal.
[retroarch.log](https://github.com/libretro/mupen64plus-libretro-nx/files/7531906/retroarch.log)

**Comment by gouchi** [comment]
Duplicate of #158

**Comment by legluondunet** [comment]
this issue is still present. I close my ticket because of duplicate.
