### ISSUE TITLE
Goemans great adventure issue!

### ISSUE THREAD

**Issue by 71knight** [libretro/mupen64plus-libretro-nx#402]
The underwater level has broken water rendering. The horizontal rendering has small gaps in the graphics.  Using angrylion RDP, pure interpreter, parallel rsp.  My phone is Android 10 using gles3 with Snapdragon 855+ adreno 640.

**Comment by m4xw** [comment]
That happens with a bunch of games if you upscale them. They simply have gaps but you never see them at low res.
Ideally still post a screenshot tho.
