### ISSUE TITLE
Starfox 64 (laylat wars EUR) slows to a crawl during planet screen

### ISSUE THREAD

**Issue by nopjne** [libretro/mupen64plus-libretro-nx#403]
The overworld menu screen where the laylat system is rendered, slows down over time. It starts out full speed then drops in speed. Happens on both EUR and US version. 

NX version.

**Comment by m4xw** [comment]
wontfix, driver / gliden bs.

**Comment by m4xw** [comment]
Luckily the whole game is flawless otherwise

**Comment by nopjne** [comment]
Could you give me a bit more context, would love to fix on my side.

**Comment by m4xw** [comment]
Smth gliden does is only a issue on noveau. Identical code / clocks is without issues under lakka switch with l4t drivers last time i checked, same with GLES on Android etc
