### ISSUE TITLE
No Frame Buffer Swap Mode Option 

### ISSUE THREAD

**Issue by Super-JoConnell** [libretro/mupen64plus-libretro-nx#407]
Was looking through options on retroarch of the core then went into the GlideN64 options, i couldn't see any options to tweak the frame buffer swap mode, would it be possible to have buffer swap mode options like (0=On VI update call, 1=On VI origin change, 2=On buffer update) ?

using win 10 64bit version

**Comment by m4xw** [comment]
Dupe of https://github.com/libretro/mupen64plus-libretro-nx/issues/72
