### ISSUE TITLE
iOS: No more audio after save state

### ISSUE THREAD

**Issue by Yqnn** [libretro/mupen64plus-libretro-nx#408]
Hello,

When using the "Save state" command for the first time after starting the core, there is a freeze for about 2 seconds, and then audio is definitively stopped.
Audio is broken for all cores, and the only way to have it back is to kill the Retroarch app, and start it again.

The issue is not systematic, I would say it occurs 90% of the time.
Apart from this audio issue, the "Save state" command works properly (and the 2 seconds freeze occurs only when audio actually crashes, after that it's instantaneous).

OS: iOS 15.1.1
Device: iPhone 12 mini
Mupen version: Freshly compiled from develop branch

I tried to capture logs using Xcode output, but there was no log coming from mupen core (only from retroarch).

Even without dynarec support, this core is running incredibly well on iPhone, thanks for this amazing work  :)

**Comment by m4xw** [comment]
Does it even work?

**Comment by m4xw** [comment]
I dont officially support it rn due to https://github.com/libretro/mupen64plus-libretro-nx/issues/219

**Comment by Yqnn** [comment]
Some games (like Super Mario 64) are not impacted, and runs really well.
And for some other games, deactivating LOD emulation mitigates the issue.

**Comment by m4xw** [comment]
Interesting
