### ISSUE TITLE
Cg shaders causing black screen

### ISSUE THREAD

**Issue by Ryunam** [libretro/mupen64plus-libretro-nx#41]
With the latest code from the GLideN64 branch, setting up any Cg shader preset causes the core to run with a black screen.
Content runs normally and audio can be heard without any issue, but the only way to get the video back is to switch to a GLSL / slang shader or disable them.

**Comment by Ryunam** [comment]
I am sorry, but can we please reopen this issue? It is still happening with the latest core: if someone is using the "gl" driver and sets any Cg shader, the screen goes entirely black while audio is still running.

This was blatantly ignored without providing any explanation. I understand your liberty to either fix or not fix whatever, but is it possible to at least apply a warning at startup (like the one that shows up when trying to use Runahead with an incompatible core) or disable Cg shaders entirely when using Mupen64Plus-Next?

**Comment by escalade** [comment]
@Ryunam

AFAIK, Cg (and GLSL) are on the way out in favor of slang. I suppose a warning would have to be implemented in RetroArch itself and cores would need to say which shaders they support. Possibly a lot of work for nothing. Seems like you are aware that Cg won't work, so just don't use them?

**Comment by Ryunam** [comment]
I am aware that using Cg shaders is discouraged right now. That being said, the average user has no way to understand that this is the case. Cg shaders are still available to be downloaded from the updater and when using the "gl" video driver they still work perfectly with pretty much all the other cores I have experimented with.

I brought this up because today I have experienced this inconvenience myself once again, while setting up someone else's RA configuration. This core was producing a black screen and only after a while I realized that "oh, it's because this is probably loading a Cg preset and there's that issue". I don't think it's unreasonable to prevent such a situation from happening.

**Comment by escalade** [comment]
If it means that much to you send a PR.

https://www.libretro.com/index.php/tag/cg/

**Comment by Ryunam** [comment]
It does not "_**mean that much to me**_", what does that even mean? It's not a personal qualm, I'm presenting an issue that is objectively occurring and that someone could inadvertently trigger such as in the example I have described above. Moreover, unfortunately at this point I am not nearly competent enough to send a PR for this.

Let's try to keep this pragmatic: is this something that would be better suited as a RetroArch issue, rather than a core thing?

**Comment by escalade** [comment]
You are the only one reporting it. Lakka itself does not support Cg shaders. They are deprecated and unsupported by nvidia since 2012. As far as I can tell, the RetroArch package in Ubuntu and Arch doesn't have Cg support compiled in. Doesn't really seem like the average user is likely to have this issue.

As stated, it would need to be implemented in RetroArch. This is simply an emulator core.
