### ISSUE TITLE
Crash when loading rom from archive

### ISSUE THREAD

**Issue by phcoder** [libretro/mupen64plus-libretro-nx#411]
When trying to load rom from archive I get sigsegv. I reacted it down to access to game->path without checking it for nullness at following 2 lines:

https://github.com/libretro/mupen64plus-libretro-nx/blob/018ee72b4fe247b38ed161033ad12a19bb936f00/libretro/libretro.c#L1758

https://github.com/libretro/mupen64plus-libretro-nx/blob/018ee72b4fe247b38ed161033ad12a19bb936f00/libretro/libretro.c#L1775

Adding "&& game->path" (without quotes) to the parent ifs fixes the issue

**Comment by m4xw** [comment]
Fixed in 732924e510eae95cd6a6848f628235441a10b438
