### ISSUE TITLE
[Feature Request] "Overclock Factor"

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#416]
PJ64 had this feature for some time now and Mupen64 FZ (the Android port of Mupen64) just added it a few days ago.

It simply overclocks the N64 CPU by a factor of your choosing (2x, 3x, 4x, etc). Combined with Counter Factor 1, it can run Goldeneye and PD, and probably other games with unlocked frame rate, at smooth 60fps (if you choose 2x or 3x on a capable enough system).

I tested both PJ64 on PC and Mupen64 FZ on my phone and it works as intended. This has nothing to do with other supposedly overclocking options like "VI Refresh", which, honestly, i don't think it was ever useful for anything. 

It would be nice if you could add this feature in the RetroArch core.

**Comment by m4xw** [comment]
already implemented lol

**Comment by m4xw** [comment]
also works different than pj, not the same.

**Comment by Tasosgemah** [comment]
I couldn't find the option in the Android core. Is it only for Windows?

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/libretro/libretro_core_options.h#L1494-L1497

**Comment by Tasosgemah** [comment]
Sorry, maybe i'm an idiot but i don't get it. I see the code you linked but what does it mean? I don't see anything different in the core options after updating the core to the latest version for android (can't use my PC to see if there's anything new for Windows version).

**Comment by Tasosgemah** [comment]
I finally managed to test the PC version and i saw the new counter option. It was the android version that doesn't have it.

The option does have an effect but, like you said, it's not like overclocking factor because the game (Goldeneye) still slows down in various parts no matter what number i choose. It's smoother than normal and runs at 60fps a lot of the time but it's not as reliable as the overclocking factor option in Mupen64 FZ/Pj64. Also, i couldn't figure out the different effect between the numbers, i used 2, 5 and more and the effect seems to be the exact same.

Maybe it must be used in combination with other options like the older counter factor option or the VI refresh? A few more details of how it works and how we can use it would be nice.

Thanks in advance.
