### ISSUE TITLE
Weird Issue with glcore/vulkan on AMD RX6900XT GPU

### ISSUE THREAD

**Issue by EmuAl** [libretro/mupen64plus-libretro-nx#420]
This could be a AMD issue as I've seen some other issues on here that are in a similar vein

When I load a n64 game through retroarch frontend it instantly crashes when I use a saved config set up for opengl but if I change video_driver line in the config from glcore to vulkan it loads fine (you can see the switch from vulkan to glcore as the vulkan screen  disappears then the gl screen reappears with the game loading fine. 

I tried making a video to show what's happening but the software doesn't record the game window but you still get the idea.

[https://streamable.com/7ix96s](url)

Both config files are identical except for the video_driver line

I am wondering why I can't get the game to load fine from the glcore config ? 
and what the actual problem is ?

here is a log from the crashing config
[retroarch__2022_02_22__19_21_31.log](https://github.com/libretro/mupen64plus-libretro-nx/files/8127914/retroarch__2022_02_22__19_21_31.log)

thanks for any help with this.

**Comment by m4xw** [comment]
dupe

**Comment by EmuAl** [comment]
dupe of what ?

can you show the issue you are referring to so i can see if there is any development on it as i can't seem to see it

thanks

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/issues/399

**Comment by EmuAl** [comment]
thanks
