### ISSUE TITLE
Majora's Mask clock panel dosen't show .

### ISSUE THREAD

**Issue by yzzyzz** [libretro/mupen64plus-libretro-nx#423]
i build latest master branch for ios , it worked well on zelda oot , but when i played zelda  Majora's Mask ,the clock panel dosent show correctly.

when there is no action  the clock panel is white as below show:
https://github.com/yzzyzz/mypicshow/blob/main/11647217937_.pic.jpg

when control the role to move ,the clock panel become transparent as below show:
https://github.com/yzzyzz/mypicshow/blob/main/31647217937_.pic.jpg

my rom is chinese version modified by jp version ,i test usa version ,the problem still exist.and i tried an old  retroarch 1.9.0 statble version release by  buildbot.libretro.com  ,the problem still exist too.

my device is m1 ipad pro ,ios 15.0 .

**Comment by m4xw** [comment]
ios is not supported.
