### ISSUE TITLE
N64dd game not work

### ISSUE THREAD

**Issue by isidoro-80** [libretro/mupen64plus-libretro-nx#424]
I have read the various instructions to make n64dd games work. I have retropie with rpi4. I put the Japanese version IPL.n64 file in the BIOS/Mupen64plus folder. I have game roms in this format gamename.ndd I created a copy of the file ipl.n64 and renamed gamename.ndd.n64.
the game doesn't start. where am i wrong?

**Comment by isidoro-80** [comment]
I post the log error

![20220316_125742](https://user-images.githubusercontent.com/75086284/158586522-9b4aa8b6-8b30-4c9f-8faf-970564059ad7.jpg)

**Comment by m4xw** [comment]
for fzero you need to use the base game, you cant just use IPL as gamename.ndd.n64 there

**Comment by isidoro-80** [comment]
> for fzero you need to use the base game, you cant just use IPL as gamename.ndd.n64 there

I tried to run the game file gamename.ndd but it doesn't work. i also tried to rename the game file gamename.ndd to gamename.ndd.n64 but it doesn't work

**Comment by m4xw** [comment]
its gamename.n64 & gamename.n64.ndd

**Comment by isidoro-80** [comment]
> its gamename.n64 & gamename.n64.ndd

it does not work. 
I did these tests:
1) I have the game rom  F-Zero X - Expansion Kit (Japan).ndd 
in the n64dd folder I put  2 files for the game: F-Zero X - Expansion Kit (Japan).ndd  and a pair of the  file  ipl.n64  file  renamed F-Zero X - Expansion Kit (Japan).ndd.n64 and not work. 
2) in the n64dd folder I put  2 files for the game: F-Zero X - Expansion Kit (Japan).ndd  and a pair of the  file  F-Zero X - Expansion Kit (Japan).ndd file  renamed F-Zero X - Expansion Kit (Japan).ndd.n64 and not work. 
where is the mistake?

**Comment by Jj0YzL5nvJ** [comment]
> where is the mistake?

You are missing `F-Zero X` itself, the "expansion kit" is useless without it.

**Comment by isidoro-80** [comment]
> > where is the mistake?
> 
> You are missing `F-Zero X` itself, the "expansion kit" is useless without it.

thanks, now i understand. I think the guide should be clearer. now i put the rom f-zero x.n64 renamed to f-zero x expansion kit.n64 and the expansion rom f-zero x expansion kit.ndd renamed to f-zero x expansion kit.n64.ndd in the n64dd folder. now the game starts and I read in the n64dd game screenshot. the game seems the same to me, maybe there is more to do?

**Comment by Jj0YzL5nvJ** [comment]
Renaming the ROMs is irrelevant to the emulator, it's just so the user doesn't confuse the files.

https://imgur.com/a/rs7nT00

> the game seems the same to me as f-zero, maybe there is more to do?

Personally I never played it back in the day, I just saw it, I still prefer Star Wars Episode I: Racer.
From what little I know, the main feature of this expansion is creating your own tracks and some other customizations.

> for the other games instead that do not have a rom in n.64 how should you do?

At the moment the emulator requires an N64 ROM to boot 64DD, even if the 64DD or disk doesn't require it... you can use any ROM. This behaviour could change in the future.
