### ISSUE TITLE
[Feature Request] Support for the raphnetraw input plugin

### ISSUE THREAD

**Issue by maxoblasto** [libretro/mupen64plus-libretro-nx#425]
Would it be possible to add this as an input option? The raphnet n64 adapters are easily the best out there and it would be nice to be able to have things like controller/transfer pak support in retroarch along with rumble since retroarch doesn't support rumble over dinput. I imagine it would also mean not having to go through retroarch's controller config which is dreadful to setup for n64.

https://www.raphnet-tech.com/products/raphnetraw/

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/pull/356
