### ISSUE TITLE
No other RDP options except GlideN64???

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/mupen64plus-libretro-nx#434]
I have the latest RetroArch (1.10.3) as well as the latest build of the Mupen64plus-next core, however weren't there going to be other RDP options like Angrylion or ParallelN64???  I go to the Core Options in the Quick Menu and in the option that says RDP Plugin, all that is there is GlideN64.  Is there a way to get the plugins back in to the core (or into RetroArch) or is GlideN64 the ONLY option???  I want to try other RDPs to see if they work with Yoshi's Story (which is STILL giving me issues!)

BY the by, I'm doing this on the Nintendo Switch (latest firmware AMS 1.3.2)

**Comment by m4xw** [comment]
For Switch it's the only option.
No Vulkan and too slow for angrylion.
