### ISSUE TITLE
how to launch a 64DD game?

### ISSUE THREAD

**Issue by AngelofMe** [libretro/mupen64plus-libretro-nx#443]
Mupen64Plus-Next GLES 3.0
Don't need to prepare this file?
64DD_IPL.bin
I select a ndd file in subsystem but nothing happens

mupen64plus_next_gles3_libretro.info
supported_extensions = "n64|v64|z64|bin|u1"
database = "Nintendo - Nintendo 64"
https://github.com/libretro/libretro-super/blob/master/dist/info/mupen64plus_next_gles3_libretro.info

parallel_n64_libretro.info
supported_extensions = "n64|v64|z64|bin|u1|ndd"
database = "Nintendo - Nintendo 64|Nintendo - Nintendo 64DD"
firmware0_desc = "64DD_IPL.bin (64DD IPL ROM)"
https://github.com/libretro/libretro-super/blob/master/dist/info/parallel_n64_libretro.info

What should I do if I want to play these games?
Super Mario 64 - Disk Version (Japan) (Proto)
SimCity 64 (Japan)
I can't find a detailed tutorial (YouTube & Libretro Docs)

RetroArch > Playlists > Nintendo - Nintendo 64DD > SimCity 64 (Japan) > Set Core Association > ParaLLEI N64
Where's Mupen64Plus-Next GLES 3.0?

**Comment by AngelofMe** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/issues/441
that's why i submitted that issue
I don't know if Mupen64Plus-Next GLES 3.0 is a Nintendo 64 Disk Drive emulator
.ndd files can't be opened directly

**Comment by AngelofMe** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/issues/441
that's why i submitted that issue
I don't know if Mupen64Plus-Next GLES 3.0 is a Nintendo 64 Disk Drive emulator
.ndd files can't be opened directly

**Comment by Jj0YzL5nvJ** [comment]
At the moment, booting the 64DD requires a N64 ROM. Even if the disk is not related to said ROM or the disk is empty.

Upstream examples:
[Booting from N64 to 64DD / 64DD to N64](https://imgur.com/a/rs7nT00)
[Booting 64DD "without disk"...](https://imgur.com/a/LkuOxHL)
