### ISSUE TITLE
Severe audio crackling in Rogue Squadron in mupen64plusNext core

### ISSUE THREAD

**Issue by MelvinSmiley** [libretro/mupen64plus-libretro-nx#444]
Video plugin: Parallei-RDP (same problem in Glide64)
Audio plugin: Parallei-RDP (same problem with HLE)

I have severe audio crackling every time when you hear shots or sth. explodes ingame. Retroach video driver is vulkan and audio driver is xaudio, tried changing it to opengl and wasapi, did nothing. I don't have any crazy settings on, just 4x native resolution, tried native resolution, still the same problem. Other n64 games work fine, it's just Rogue Squadron. System is : Windows 10 64bit with newest updates, Geforce 3080 12GB, Ryzen 5900x, 32gb Ram.

**Comment by m4xw** [comment]
There is no Glide64 so you must be refering to the wrong core.

**Comment by m4xw** [comment]
Fwiw i know rogue is fine, plays even fullspeed on switch. You probably arent running it fullspeed at 4x for some reason or your audio latency is all wrong. Or u have some hard sync shit going on
