### ISSUE TITLE
mupen64plus next core crashing when loading game

### ISSUE THREAD

**Issue by jeep0621** [libretro/mupen64plus-libretro-nx#447]
file:///home/jeep/snap/retroarch/538/.config/retroarch/logs/retroarch.log

**Comment by jeep0621** [comment]
hello i have a bug with mupen64plus next core
is it normal?
thanks

**Comment by mackal** [comment]
I was having similar crashes on my x86 based desktop, I had to enable opengl_core option or it would crash. Seems fine without that enabled as a build option in retroarch.

**Comment by jeep0621** [comment]
thanks but unfortunately changing driver  does not seem to help (i tried, glcore, gl1, vulkan) , maybe my pentium m processor is too weak for this emu, will stick with parallell64

**Comment by m4xw** [comment]
Sounds like you dont support the required GL version :/

**Comment by m4xw** [comment]
fwiw u probably can use the ANGLE / UWP version like xbox
