### ISSUE TITLE
Transfer Pak Pokemon Stadium / Pokemon Red Reading Issues

### ISSUE THREAD

**Issue by PhockYouGaming** [libretro/mupen64plus-libretro-nx#449]
Currently having the same issue as Nijaokim. I posted it on Reddit page as well. All above steps are complete, I even turned the SaveRam Compression off, and I'm still showing the image posted below.
![GBAnowork](https://user-images.githubusercontent.com/111177782/184478645-dfa97d54-39c9-4675-a116-6599516cb1da.png)

I'm running Retroarch from Steam.
Pokemon - Red Version (USA, Europe) (SGB Enhanced).GB and .SAV
Pokemon Stadium (U) (V1.1) [!].gb

Loaded into Transferpak as stated above per directions.

Things I've done:

Checked all files to ensure the hyperextensions are correct.
reloading PokeRed and ensured it was readable on GB Emulator
Reloaded PokeRed and Pokemon Stadium to ensure files were correct.
Consult/Revise all methods prior to reach this spot via Reddit and This page.
Some assistance greatly required, my childhood is hurting.

**Comment by PhockYouGaming** [comment]
Update 1.

Running Windows 10. Same issues.

Changed file names to Pokemon Red.gb and Pokemon Red.sav (Both files still work on Gambette.

Changed file name to Pokemon Stadium.z64 

Issues still concurrent with above photograph.

**Comment by m4xw** [comment]
Via subsystem?
Otherwise name N64 ROM "Pokemon Stadium.z64", GB ROM " Pokemon Stadium.z64.gb" and GB Save "Pokemon Stadium.z64.sav"
