### ISSUE TITLE
Crash on startup with MacOSX 12.6, Intel x64 CPU, compiled with MacOSXSDK 10.11

### ISSUE THREAD

**Issue by Sethur** [libretro/mupen64plus-libretro-nx#459]
Hi,

I tried to get this core running on MacOS X Monterey 12.6 using a manual Xcode Build with a manually installed MacOSXSDK 10.11. For the compile to work, I needed merged the changes in the kivular/fixosx2 brach to develop and additionally add `-mmacosx-version-min=10.11`to the compiler flags.

After the build went through, I installed the core both on the current release version of RetroArch. This unfortunately led to a crash to desktop immediately after loading any N64 rom. The logs did stop directly after initiating dynarec, but switching to cached_interpreter did not help. 

To get more debug output, I compiled the current RetroArch code with Xcode targeting SDK 10.11 and recompiled mugen64plus-next with debug mode enabled in the Makefile. Loading a rom then led to a crash in amd64.c, line 127:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/2142589/190995726-95b9d108-9a1f-449d-a38d-2de28cabc142.png">

Has anyone had success with getting this core run in Mac OS X lately and can give some insight?

**Comment by m4xw** [comment]
(The return from co_ can be valid tho, that condition should never happen tho as it should co_switch unless plugin is gliden + thr renderer).
Does it think its using gliden or smth, even tho AL is hardcoded?

**Comment by Sethur** [comment]
@m4xw Is there a way to find out if Gliden is used in the logs? I can't remember seeing any mugen-specific log messages before the crash occured.

Also: Was OSX support dropped because of issues with OpenGL compatibility?

**Comment by m4xw** [comment]
OSX support was never really a part of NX.
GL is bugged to hell (same with IOS), happy to support it otherwise.
It's working with AL but I refuse to merge it if the only plugin thats absolutely required due to how the core is structured, is defunct.

RE AL: just check the core option. if it says gliden then something is very wrong.
I dont remember if he added the force option to the PR tho now that I think about it..

**Comment by Sethur** [comment]
Core Options don't seem to be available in Retroarch if no ROM is currently running, and since I can't load any ROM at all, I don't seem to be able to access the options to check for AL vs GLiden. Is there a way around this?
