### ISSUE TITLE
Black Screen - Linux

### ISSUE THREAD

**Issue by lucasmr** [libretro/mupen64plus-libretro-nx#46]
I suspect that the GL version is not being detected correctly. Running retroarch, mupen64plus-libretro-nx (branch GLideN64) and Mario 64 I get blackscreen with sound and no errors in the terminal. It shows:

```
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Ivybridge Desktop .
[INFO] [GL]: Version: 3.0 Mesa 18.2.8.
```

Core was compiled with default flags, just with "make" and copying the core to /usr/lib64/libretro. Default mupen64plus-libretro detects the version correctly:

```
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Ivybridge Desktop .
[INFO] [GL]: Version: 4.2 (Core Profile) Mesa 18.2.8.
```

**Comment by m4xw** [comment]
First off, please use the META Issue https://github.com/libretro/mupen64plus-libretro-nx/issues/43
Second, try https://github.com/libretro/mupen64plus-libretro-nx/issues/43#issuecomment-477654295

**Comment by lucasmr** [comment]
Thanks. No problem, the issues are getting fixed.
