### ISSUE TITLE
Updating save/state files from mupen64plus

### ISSUE THREAD

**Issue by jallwine** [libretro/mupen64plus-libretro-nx#465]
I have RetroPie set up on one computer and another computer running RetroArch. RetroPie is using mupen64plus and RetroArch is using mupen64plus-next. I have a number of save/state files from RetroPie that I would like to copy over to RetroArch. I see .srm files and .state# files in RetroArch and .sra and .st# in RetroPie. Is there an easy way to convert these files so that I can load them on the RetroArch set up?

**Comment by m4xw** [comment]
This is not official supported at this point and time (transfering save*states* in particular won't be officially supported. They might work, they might not).
As for savefiles, take a look at this issue tracker and you will find your answers

**Comment by jallwine** [comment]
I’ve definitely search for answers yet don’t see anything helpful.
