### ISSUE TITLE
A and B - C Button Assignment

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#469]
Currently the C Button switch assigns the a button to c1 and the b button to c2.
It would be great to assign the c buttons independently to the a and b button. like c4 to A or even to unassign thr c bttons completely from a and b

**Comment by sonninnos** [comment]
Pretty sure all of that is already possible in the core options.

**Comment by Papermanzero** [comment]
You are right 🤦‍♂️ My fault
