### ISSUE TITLE
Blast Corps - Black Flashing Areas with standard settings

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#470]
I tried the ini and core settings but with both the game has flashing black areas. None of the settings is solving the issue. Sometimes the textures are missing or sometimes the black squares return.

**Comment by bslenul** [comment]
> None of the settings is solving the issue.

Changing "RSP Plugin" to either "CXD4" or "ParaLLEl" seems to fix it for me.

**Comment by Papermanzero** [comment]
thanks a lot that worked 👍
