### ISSUE TITLE
add another way to load NDD

### ISSUE THREAD

**Issue by soundsnow** [libretro/mupen64plus-libretro-nx#489]
n64|v64|z64|ndd|bin|u1
Most ndd files can be loaded without n64, z64, v64.  Only F-Zero X supports ROM Cartridge+Disk

1. Load NDD directly
RetroArch: Load Content - Kyojin no Doshin (Japan).ndd

2. Spend more time opening NDD and Z64
RetroArch: Load Core - Mupen64Plus Next GLES3 - Subsystems - Load N64 Disk Drive - F-Zero X - Expansion Kit (Japan).ndd - Subsystems - Load N64 Disk Drive - F-Zero X (Japan).z64 - Subsystems - Start N64 Disk Drive

**Comment by m4xw** [comment]
Not as of right now
