### ISSUE TITLE
[Request] Notify the fps change to the frontend

### ISSUE THREAD

**Issue by Immersion95** [libretro/mupen64plus-libretro-nx#503]
Flycast has that option, if a game is internally running at 30fps, the core reports the same fps. This allows smooth scrolling with VRR/Freesync.

mupen64plus always reports 60fps (console outputing 60fps) even with 30fps games, the option "frame duplicate" doesn't do anything.

The previous core ParaLLEl N64 was correctly reporting 30fps games fyi.

**Comment by m4xw** [comment]
Thats because I report VI/s which is the far more useful metric for N64
