### ISSUE TITLE
GLES2/GLES3 cores instantly crash on Android (Anbernic RG556)

### ISSUE THREAD

**Issue by Bent3ndo** [libretro/mupen64plus-libretro-nx#529]
Hi,

Having serious issues launching any games with the mupen64-plus cores in RetroArch on my Anbernic RG556.

The core for ParaLLEl runs perfect and upscales to 1080p with no issues whatsoever, but of course would rather use mupen64plus and apply texture packs and more settings if possible (along with using RetroAchievements which the standalone app doesn't like).

I've attempted both builds of the nightly RetroArch (standard and arch64) and both versions crash the second I attempt to launch a game.

What could be causing this yet not making other N64 cores or apps crash?

Thanks!

**Comment by m4xw** [comment]
Well i will need more infos than that. Got a logcat?
