### ISSUE TITLE
Any chance of including Jabos Direct3d plugin?

### ISSUE THREAD

**Issue by reignerdeustcher** [libretro/mupen64plus-libretro-nx#531]
It was always the only graphic plugin that works properly with nice graphics and best performance, gliden64 is a useless thing that works all stuttered in vulkan, angrylion looks like crap and doesn't have a tiny option to improve graphics and parallei crashes upscaling to 8x (so ridiculous)

**Comment by mudl0rd** [comment]
Never going to happen.

**Comment by m4xw** [comment]
Nope
