### ISSUE TITLE
Missing geometry and textures on appletv

### ISSUE THREAD

**Issue by Nioh8** [libretro/mupen64plus-libretro-nx#553]
Using gliden64 with HLE many games are missing menus, textures and geometry, the only fix is changing the RSP plugin to ParaLLEI. HLE seems to be causing the issue in many games, goldeneye, perfect dark, all have the same issues 

Banjo Kazooie
![image](https://github.com/user-attachments/assets/3d5bd68b-0816-4bca-9531-5254061bd1a9)

Goldeneye
![image](https://github.com/user-attachments/assets/e71456b8-d6a4-4346-91ba-2b1da2483627)

Perfect Dark
![image](https://github.com/user-attachments/assets/f2959f8b-8619-455e-a710-bba0b0f9a643)

I'm on the latest gen appletv 4K with tvOS 17.6

**Comment by m4xw** [comment]
Had it tested and seems resolved.
