### ISSUE TITLE
Resident EviL2, character becomes transparent

### ISSUE THREAD

**Issue by spielvan** [libretro/mupen64plus-libretro-nx#56]
In my Mx3-G Box android tv, android 5.1.1 32bits, S192, plus mali 450 with Open Gl 2.0 ES, the scenery gets normal, but the characters are invisible.

**Comment by m4xw** [comment]
Pretty sure it needs Shader depth write, which is not supported in GLES 2, so you are out of luck.

**Comment by m4xw** [comment]
However, you can try a GLES 3 build.

**Comment by spielvan** [comment]
Many thanks for the response, interesting that Star Wars - Rogue Squadron worked very well with Open Gl 2.0.

**Comment by m4xw** [comment]
RE2 is the only game that comes to my mind that needs it.
There might be others tho.
Does your device support GLES3?
I can consider adding a GLES3 build to the build bot.

**Comment by spielvan** [comment]
My MX3-G unfortunately does not support Open GL 3.0 only Open GL 2.0, but I'm going to stay as Open Gl 2.0 tester so it will help in the project.
