### ISSUE TITLE
Some games are not recognizing the Game Pad

### ISSUE THREAD

**Issue by spielvan** [libretro/mupen64plus-libretro-nx#57]
Some games when I load do not recognize the game pad do not know the reason and after the presentation close the retroarch, the ones I remember head:

Kirby 64
Star Soldier: Vanishing Earth
Super Smash Bros

**Comment by m4xw** [comment]
You need to be more specific.

**Comment by spielvan** [comment]
I load the rom, but in these games the commands do not work, no button and when it finishes running the game introduction the core closes itself.

**Comment by m4xw** [comment]
What Gamepad?
Other Games work?
Does touch still work?

**Comment by spielvan** [comment]
In original Playstation 2 controller, connected to an adapter from Leadership GAMER (converts from ps2 to xbox 360) and recognized by the Box android tv MX3-G as an x-input control.

yes including The Star Wars RS

I did not get to test the touth with the mouse, but could test, my tv would not have native touch screen

**Comment by m4xw** [comment]
You could try changing the poll behaviour setting to something else.

**Comment by spielvan** [comment]
It blocks the options of the game pad, not being able to go back to the retroarch menu, and in the control options there are only 1 option to choose, controller or none, I just saw Lamborgne Automovel has the same problem.

**Comment by IdiotBlueMage** [comment]
I've been having this issue with Mario Party 2.  The difference is that as I try to get it to recognize it (by pressing buttons etc), it does react.  Analog sticks tend to make it freeze for a split second, and if I move them around too much RetroArch will actually crash.

This is on Android, if it matters much.

**Comment by m4xw** [comment]
I think I know whats up...

**Comment by IdiotBlueMage** [comment]
I took a look a bit later and it works now.  One notable thing I did was change the poll behavior to "early" for latency purposes, and it looks like a happy side effect was fixing this issue.  I'm not sure if this will work for everyone or not but there you go.

**Comment by m4xw** [comment]
Yea this is a frontend bug.

**Comment by m4xw** [comment]
Theres 2 Issues here that cause it to missfunction, back when the issue was created we didn't call the poll_cb.
Thats been long fixed, now its a issue with polling from not the main thread, with video_threaded on I actually get like no input at all..
