### ISSUE TITLE
Controller Pak and Rumble Pak switching

### ISSUE THREAD

**Issue by PlagueWizard** [libretro/mupen64plus-libretro-nx#59]
The rumble pak had a [large number of supported games](https://nintendo.fandom.com/wiki/List_of_Nintendo_64_games_with_Rumble_Pak_support), and the controller pak likewise had an [extensive list of support](http://micro-64.com/database/gamesave.shtml), with not insignificant crossover.

Many of the games that supported both allowed you to switch them out as needed, such as San Francisco Rush 2049 and Beetle Adventure Racing, so that you could save your progress but also have rumble enabled during a game.

Mupen standalone has the ability to switch them out via button press, and every game I have tested with it so far works like I remember it working on real hardware.

I understand that exposing core options to be toggleable via a button in RetroArch isn't feasible currently, but it would be nice if, upon a game requesting you to insert a controller/rumble pak, that changing the core option would be recognized by the game consistently, especially since the standalone emulator can do so. Currently it isn't.

As a specific example, Beetle Adventure Racing checks for a controller pak after loading, and allows you to insert one both on real hardware and on standalone Mupen, upon doing so it reads the memory and proceeds as normal. Then, before starting a race, the game has a prompt to insert a rumble pak, and if you do then on real hardware and Mupen standalone you will have rumble in game.

This currently does not work in the RetroArch core or NEXT. I am unsure of how difficult this would be to implement, but I do know that, for comparison's sake the PCE Fast core and Beetle PSX both allow you to change controller settings from the core options menu (enabling turbo for PCE and analog for PSX), and in both cases it immediately works.

**Comment by BPaden** [comment]
So I've just so happen to have run into this issue for Beetle Adventure Racing on the parallel core. At least in that core, it actually works fine. **But** you need to switch to none first, unpause the emulator and wait a couple of seconds, and then switch back to memory (or rumble depending on the situation). Unless next does something differently, I think what's happening is the core instantly switches between the two, but obviously this isn't what happens on a real console.

**Comment by m4xw** [comment]
Would make sense, good comment.

**Comment by Papermanzero** [comment]
Just out of curiosity : would it be possible to enhance the emulator to support both at the same time. It is not accurate with the real hardware, but in theory the emulator could support “endless” controller interfaces at the same time. The game calls certain request to access either the memory pak or the rumble pak. So building a listener to those request and activate the dedicated pak would be a solution to support both at the same time.

**Comment by m4xw** [comment]
Fixed locally

**Comment by m4xw** [comment]
Funnily enough this was already supported but it was just never updated in mupen core

**Comment by m4xw** [comment]
> Just out of curiosity : would it be possible to enhance the emulator to support both at the same time? It is not accurate with the real hardware, but in theory the emulator could support “endless” controller interfaces in parallel. The game calls certain request to access either the memory pak or the rumble pak. So building a listener to those request and activate the dedicated pak would be a solution to support both at the same time.

Maybe with some game patches and lots of hackery

**Comment by Jj0YzL5nvJ** [comment]
[TremorPak](https://www.ign.com/articles/1999/03/04/tremorpak-plus)?

Not all the games support "hot plugging"... Perfect Dark does, Castlevania no.

**Comment by m4xw** [comment]
Closing since it will be merged in 2.2 (experimental branch), Scheduled later for today.
