### ISSUE TITLE
Adapt configuration logic for the libretro API (Core options)

### ISSUE THREAD

**Issue by m4xw** [libretro/mupen64plus-libretro-nx#6]
Currently incomplete.

**Comment by mudlord** [comment]
Is it possible to also copy over the key mappings as well, such as for independant C button setting?

**Comment by m4xw** [comment]
Care to elaborate a bit?

**Comment by m4xw** [comment]
This issue has been fixed, now it's about add new options, not yet exposed.

**Comment by mudlord** [comment]
Parallel-n64 had some input configuration options for allowing binding C buttons as independant RetroPad buttons, it would be nice if this functionality is transferred over.

**Comment by tony971** [comment]
> Parallel-n64 had some input configuration options for allowing binding C buttons as independant RetroPad buttons, it would be nice if this functionality is transferred over.

This is essential for using N64-style controllers in the core.

**Comment by mudlord** [comment]
Care to elaborate on this "setting"?

Not everyone uses RA for libretro cores.
