### ISSUE TITLE
[Android] Lots of titles crash with a gamepad attatched.

### ISSUE THREAD

**Issue by ghost** [libretro/mupen64plus-libretro-nx#60]
Most games I have crash, with the only common thread being that my controller is being used.  The only games I've been able to boot so far are Banjo-Kazooie and Super Mario 64. 

I'm running this on Android, and during this time I have a controller and keyboard recognized at once.  With only the keyboard all works fine.

**Comment by m4xw** [comment]
Crash dump/log/trace?

**Comment by shlomi-toren-sp** [comment]
Happened to me too.
Super Mario 64 and Mario Kart 64 work fine, but GoldenEye for example crashes when connecting a second controller.

**Comment by m4xw** [comment]
Can you try updating joypad autoconfigs via the core updater, also is Independent C buttons mode on or off?

**Comment by Chronosplit** [comment]
Sorry, stilll working on the log files.  First time doing this with Android.

Just updated autoconfig today, the problem still persists.  Independent C Buttons has always been false.

**Comment by m4xw** [comment]
@shlomi-toren-sp does the issue still exist?
If you cant tell me I will need to close it until someone can confirm.

**Comment by shlomi-toren-sp** [comment]
@m4xw Yes. The volume issue definitely still happens, but I haven't tested the multiple controllers thing in a while.

**Comment by m4xw** [comment]
Ok thanks.

**Comment by m4xw** [comment]
I will close this for now. If this issue still happens, someone please let me know.
#63 works for me on my device now so I am gonna cross my fingers.
