### ISSUE TITLE
Mario kart n64 emulation: emulate screen above the tunnel 1st stage on android shield tv

### ISSUE THREAD

**Issue by srk15372** [libretro/mupen64plus-libretro-nx#61]
Hi,
great work thanks.
I was thinking that the tunnel effect will be OK with the new updated glide plugin on latest mupen64next android core  but now I only see a static weird picture like this:

![8a6ff3e7775428d59a2f72f979ab978d8520db4e_1_666x500](https://user-images.githubusercontent.com/40340145/58367809-e53a7400-7ee3-11e9-8f94-006304322243.JPG)

Is it possible on android to make this effect works on shield tv with this new core pupen64 next ? Thanks

**Comment by m4xw** [comment]
If you have framebuffer emulation on and that doesn't work, then its a limitation of GLES2.
Copy Color to RDRAM isn't supported.

**Comment by m4xw** [comment]
I do consider adding a GLES3 build to the bot.

**Comment by srk15372** [comment]
hi thanks
I have framebuffer emulation set to true so hope you could add these effect with gles3  thanks again great work

**Comment by dankcushions** [comment]
I get the same issue with a GLES3 source build on pi4

> Copy Color to RDRAM isn't supported.

hmm, but there's a core option to enable it? maybe you have since supported it, as this issue is old?

in any case, that option seems important: https://github.com/gonetz/GLideN64/issues/1490

it works for me in standalone m64 + gliden64 with this option:
```
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=Double Buffer, 3=Triple B$
EnableCopyColorToRDRAM = 2
```

**Comment by dankcushions** [comment]
oh, looks like my nx build still says it's built for GLES2 in the library name... which means retroarch itself was built without support, despite being built with --enable-opengles3 :/ not an nx problem, in any case.
