### ISSUE TITLE
Custom Robo V2 blighter screen

### ISSUE THREAD

**Issue by waitingmoon** [libretro/mupen64plus-libretro-nx#62]
the screen of custom robo v2(japan) on mupen64plus-next is not correct color. probably the gamma value is wrong.

Version and OS
- RetroArch 1.7.7 stable
- Mupen64Plus-Next 96608ba
- Windows 10 Pro 64bit 1809

Comparison 
-Mupen64Plus-Next (Not Correct)
![Custom Robo V2 (Japan)-190526-034154](https://user-images.githubusercontent.com/16256443/58373396-9edb2880-7f68-11e9-9c9a-fa609397f09d.png)
![Custom Robo V2 (Japan)-190526-034003](https://user-images.githubusercontent.com/16256443/58373406-c631f580-7f68-11e9-8823-1337ba6fb654.png)

-ParaLLEl (Correct)
![Custom Robo V2 (Japan)-190526-034225](https://user-images.githubusercontent.com/16256443/58373405-c16d4180-7f68-11e9-9ea7-4636f2f04b38.png)
![Custom Robo V2 (Japan)-190526-034057](https://user-images.githubusercontent.com/16256443/58373407-c9c57c80-7f68-11e9-9dd2-f9540800ca0d.png)

**Comment by m4xw** [comment]
Does it happen with standalone GLideN64?
If so I will close this and you need to report the bug there.

**Comment by Jj0YzL5nvJ** [comment]
How strange, the same effect happens in angrylion-plus on standalone.

**Comment by m4xw** [comment]
Will label it as invalid for now.

**Comment by m4xw** [comment]
Will close it for now, I must believe that AL standalone is accurate.
If the behaviour changes, feel free to re-open the issue.
