### ISSUE TITLE
[Android] Crash when using the volume buttons early

### ISSUE THREAD

**Issue by shlomi-toren-sp** [libretro/mupen64plus-libretro-nx#63]
Retroarch x64 on Samsung Galaxy Note 9.
I updated the core today, and the game seems to work fine, but when you press one of the volume buttons Retroarch crashes. Doesn't happen on other cores.
I can send logs if someone tells me how to create them.

**Comment by m4xw** [comment]
This is a general issue that occurs on android (at least for me).
Using volume buttons while the game is starting, causes a abort.

**Comment by Chronosplit** [comment]
This has happened to me on any Mupen64Plus core in RetroArch and nowhere else.  Indeed, it's with any game and it has happened to me at any time in the game as opposed to just while booting.

It's not just the volume buttons themselves either, changing the volume of the device in general does it (changing the volume of RetroArch is fine however).

**Comment by m4xw** [comment]
> any time in the game as opposed to just while booting.

fwiw I am only able to replicate it while booting

**Comment by shlomi-toren-sp** [comment]
Yeah, happens to me too anywhere in the game.

**Comment by m4xw** [comment]
Same as the other Issue #60

**Comment by m4xw** [comment]
I wasnt able to reproduce this anymore on my device.
Gonna close this, if this still happens with latest RA let me know.
