### ISSUE TITLE
[RPI] Can see through walls in Zelda OoT

### ISSUE THREAD

**Issue by alessandropaggi** [libretro/mupen64plus-libretro-nx#65]
RetroArch 1.7.6
Mupen64Plus-Next 96608ba
RetroPie 3B
I'm playing Zelda OoT, and I've noticed that some texture elements (water, roads, vines, etc.) are visible through walls and floors, and they actually appear on top of everything, Link included.
Is this a bug, or there is a specific setting that can fix this?
Thanks.

**Comment by m4xw** [comment]
Screenshot?

**Comment by alessandropaggi** [comment]
![Legend of Zelda, The - Ocarina of Time (USA)-190608-193724](https://user-images.githubusercontent.com/34541143/59150547-b369f700-8a25-11e9-96c1-0e82de6ca97d.png)
![Legend of Zelda, The - Ocarina of Time (USA)-190608-194048](https://user-images.githubusercontent.com/34541143/59150548-b369f700-8a25-11e9-9b95-9a4ac201bd81.png)
![Legend of Zelda, The - Ocarina of Time (USA)-190608-194209](https://user-images.githubusercontent.com/34541143/59150549-b369f700-8a25-11e9-8b20-a43c63bfc0e3.png)

**Comment by m4xw** [comment]
Looks like some depth problems.
Might be a GLES2 Issue, can you upload your core options?

**Comment by alessandropaggi** [comment]
https://pastebin.com/2s7Xah7Z

**Comment by m4xw** [comment]
Turn fbemu off, this is just experimental for rpi.

**Comment by m4xw** [comment]
Also you will have issues with mupen64plus-next-MaxTxCacheSize = "8000" on rpi.
You should just use defaults.

**Comment by alessandropaggi** [comment]
Turning framebuffer emulation off solved the issue, thank you.
This messed up a bit the status menu, but apart from that the game is playable.
![Legend of Zelda, The - Ocarina of Time (USA)-190608-233144](https://user-images.githubusercontent.com/34541143/59152515-cdb3cd00-8a45-11e9-9285-363867a05ab1.png)

**Comment by m4xw** [comment]
Yea that feature is not possible to emulate without fbemu.
GLES2 limitation.
