### ISSUE TITLE
Controllers buttons doesn't work in core

### ISSUE THREAD

**Issue by MrMarukesu** [libretro/mupen64plus-libretro-nx#67]
When load a game, only the analogs works, all the rest simply doesn't work, but when in retroarch menu, it's work perfectly

**Comment by m4xw** [comment]
Not enough informations supplied.
Works fine here.

**Comment by MrMarukesu** [comment]
The core works fine if I use the overlay for commands, but when I try use a controller it only works the analogs. And it is happening ever with others cores.

I can attach the retroarch log, but the buttons works in her, only in the emulator that his doesn't work.
