### ISSUE TITLE
Option to disable filtering

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#69]
Games like yoshis story or mischief makers are 2D games.
Unfortunately those games are affected by the bilinear or 3-point filtering.
With the filtering, upscale shaders like scalefx looks very blurry.
Therefore the possibility to deactivate the filtering to have the pixel graphics would be beneficial to use shaders without limitations

**Comment by m4xw** [comment]
Not sure how feasible that is, as it might be required for certain aspects of the emu.

**Comment by Papermanzero** [comment]
Yes, I assume the same.
However to apply scalefx or other shaders the bilinear or 3point must be deactivated.

In general I think gonetz has to rewrite the filtering.

**Comment by Papermanzero** [comment]
Has to be implemented in gliden64
