### ISSUE TITLE
Add LLE RSP

### ISSUE THREAD

**Issue by m4xw** [libretro/mupen64plus-libretro-nx#7]

**Comment by m4xw** [comment]
@mudlord is there a threaded LLE RDP plugin that I am not aware of?

**Comment by mudlord** [comment]
parallel-n64 has a multithreaded Angrylion fork.

**Comment by Mikau28** [comment]
Parallel uses a much older version of angrylion does it not? You need a 4.6ghz proc to run it smoothly.

**Comment by m4xw** [comment]
@Mikau28 I could update it, but this core isn't really supposed to become "the next parallel" core.

Also i missread RDP with RSP (4am things), I don't think this core should support AL, but I am open for consideration.

**Comment by mudlord** [comment]
Thanks for the clarification. Considering GlideN64 supports *all* graphics microcodes now and the HLE RSP supports *all* audio ucodes, might not have any need for low level RSP.

**Comment by m4xw** [comment]
@mudlord We decided to add angrylion after all (given the nice perf boost on x64)
I exported all relevant commits from the parallel repository to https://github.com/libretro/mupen64plus-video-angrylion
If you want to help (at best parallel and mupen both use that AL repo), be my guest
