### ISSUE TITLE
Lots of compilation errors on musl

### ISSUE THREAD

**Issue by PureTryOut** [libretro/mupen64plus-libretro-nx#70]
This currently fails to compile hard on Musl systems like Alpine Linux.

[build-error.log](https://github.com/libretro/mupen64plus-libretro-nx/files/3372813/build-error.log)

**Comment by m4xw** [comment]
Not supported.

**Comment by PureTryOut** [comment]
Seriously? Isn't libretro striving for high portability? Will this core never be supported on any other platforms that Linux with glibc? Why close this rather than leaving it open for someone with the knowledge and will to fix it?

**Comment by m4xw** [comment]
I won't provide support for anything else than glibc.
Also this is not a mupen64plus-next issue to begin with.

**Comment by m4xw** [comment]
For reference, upstream doesn't support it.
https://github.com/mupen64plus/mupen64plus-core/issues/642

**Comment by PureTryOut** [comment]
Now that's something I can work with, please consider giving reasons for closing issues next time. Just saying "not supported" is not enough and will just cause people to ask again.
