### ISSUE TITLE
Pokemon puzzle league (Pal) does not boot

### ISSUE THREAD

**Issue by Papermanzero** [libretro/mupen64plus-libretro-nx#71]
Tried to start pokemon puzzle league, but it always results in a black screen during boot

**Comment by m4xw** [comment]
Did you check standalone?

**Comment by Papermanzero** [comment]
Will do

**Comment by Papermanzero** [comment]
Yes, it is working with mupen64plus-gui with standard settings.
Used the official 4.0 release from gliden64.

**Comment by m4xw** [comment]
Still a issue with this build?
[mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3666004/mupen64plus_next_libretro.zip)

**Comment by Papermanzero** [comment]
No it does not fix the issue.
Moreover in other games like yohsis story graphical issues were inroduced.

**Comment by m4xw** [comment]
@Papermanzero There is a  new core option related to accuracy.
Try stripped background mode, might cause issues in yoshis if you run 240 Hz tho :P

**Comment by Cee123** [comment]
I can confirm this also. On Odroid XU4 and Odroid N2, this game will not run. Along with games - Glover and Glover 2. Neither of those will boot also.

**Comment by Papermanzero** [comment]
For me it is not working in windows :(

**Comment by m4xw** [comment]
@Cee123 Glover is a dynarec issue

**Comment by Cee123** [comment]
@m4xw Oh OK. How do we fix it? Is it possible Pokemon Puzzle league is also dynarec related?

**Comment by m4xw** [comment]
@Cee123 Dunno about puzzle league but theres no fix.
You can get past the crashing area with interpreter, take a savestate, switch to dynarec and load it.
https://github.com/mupen64plus/mupen64plus-core/issues/171
Puzzle league might be a HLE RSP Issue? https://github.com/mupen64plus/mupen64plus-core/issues/546

**Comment by m4xw** [comment]
@Papermanzero 
[cxd4_mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3707270/cxd4_mupen64plus_next_libretro.zip)

**Comment by m4xw** [comment]
Got confirmation it boots with LLE RSP, closing this.
![image](https://user-images.githubusercontent.com/13141469/66481446-3cab3c00-eaa1-11e9-954c-c2d7c2245e38.png)

**Comment by m4xw** [comment]
I won't provide builds with cxd4 tho, you will need to wait until LLE stuff is merged & configurable via core options.
Sorry.

**Comment by Cee123** [comment]
@m4rw That's a good idea I hadn't thought to try that. That's one solution.

**Comment by m4xw** [comment]
7630fe3b95d67e2b5ed6a5ea99c276ed05c06e80 fixed this Issue.

**Comment by m4xw** [comment]
![image](https://user-images.githubusercontent.com/13141469/73741212-12fddb00-474a-11ea-8b81-6e2d2f4bd9bf.png)

**Comment by Cee123** [comment]
@m4xw That's fantastic. Excellent work!
