### ISSUE TITLE
Issue with rom native resolution switch

### ISSUE THREAD

**Issue by cbc12345** [libretro/mupen64plus-libretro-nx#73]
If the video resolution is changed to high, the game is not shown in full screen, leaving black borders on the right and below

**Comment by m4xw** [comment]
Picture?
Doesn't sound like a bug.

**Comment by cbc12345** [comment]
![lores](https://user-images.githubusercontent.com/49755019/61141378-c0b74d00-a4cd-11e9-9799-75533e7ec19d.png)
![hires](https://user-images.githubusercontent.com/49755019/61141384-c319a700-a4cd-11e9-976d-425c64c7fe46.png)

in a previous version downloaded through your twitter account, it worked without issues

**Comment by m4xw** [comment]
Try GLideN64 standalone.
I dont think this is a mupen next bug.

**Comment by cbc12345** [comment]
I have tested the game with gliden64 4.0 and project64 and everything works correctly

Low resolution picture:
![lores](https://user-images.githubusercontent.com/49755019/61144612-97022400-a4d5-11e9-8c58-39b873df32d8.png)

High resolution picture:
![hires](https://user-images.githubusercontent.com/49755019/61144618-9b2e4180-a4d5-11e9-9ebd-e76197c74dc3.png)

**Comment by m4xw** [comment]
What is your aspect ratio set to in retroarch video settings?

**Comment by cbc12345** [comment]
in retroarch "core provided", in mupen64plus_next "16:9 adjusted", but it also happens with 16:9 and 4:3

**Comment by m4xw** [comment]
I shall investigate

**Comment by mudlord** [comment]
Investigated, works with my einweg code. 
![Capture](https://user-images.githubusercontent.com/42057628/64418610-aae59300-d0de-11e9-91f1-6f3aab581bb8.PNG)

**Comment by m4xw** [comment]
Ok this actually gets interesting now.

**Comment by m4xw** [comment]
@cbc12345 still a issue?

**Comment by cbc12345** [comment]
Yes, the issue keeps happening. Tested with version 1.0 e79667f

**Comment by cbc12345** [comment]
I have upgraded all cores and Retroarch to version 1.8.7 and the issue is no longer producing. It is now displayed in full screen in both low and high resolution. The problem is solved
