### ISSUE TITLE
PSA: Change of branching model

### ISSUE THREAD

**Issue by m4xw** [libretro/mupen64plus-libretro-nx#76]
It's time to cleanup some branches within the next weeks:
-`mupen_next` will be the archived snapshot before the GLideN64 update
-`rebase` -> `experimental` (will probably keep such branches around more often)
-`GLideN64` -> split in `master`, `develop`

`develop` will be the new default branch, while the actual `master` branch will only have periodic stable changes and hotfixes.

**Comment by m4xw** [comment]
@mudlord Once the updates to the soon-ish core option ehancements are finalized I will rebase the `lle` branch and start integrating it.
Probably mid next months

**Comment by mudlord** [comment]
Sounds good, I have gone back to demoscene/security stuff anyway, so for me, emulation is kinda on the back foot these days thanks to.....things.

**Comment by m4xw** [comment]
Created master, develop (new default branch), tagged old mupen_next branch here https://github.com/libretro/mupen64plus-libretro-nx/tree/mupen_next_old_gliden
The GLideN64 branch will stay for a few weeks, anyone please target PR's to develop!

**Comment by mudlord** [comment]
So that includes the LLE stuff, got it.

**Comment by m4xw** [comment]
Gliden branch is now gone.
