### ISSUE TITLE
[Unix] Fix libpng linkage

### ISSUE THREAD

**Issue by autofire372** [libretro/mupen64plus-libretro-nx#78]
This was actually an [issue in the old repo](https://github.com/libretro/mupen64plus-libretro/issues/60); for reference, [here's](https://github.com/libretro/mupen64plus-libretro/pull/75) how it was fixed.

**Comment by m4xw** [comment]
Eh I would probably not accept a solution like u work on rn (doing some peeks).
People are already on it and I have strict guidelines for the handling of future changes in regards to dependencies.
This is not a Issue someone from outside should tackle right now, unless u want it only for you.
I don't want to discourage you, but this was internally throughougly discussed.
I will leave the Issue open until it's fixed and you can open a PR for reference if you want, but I can't promise you I will accept it in the end.

**Comment by autofire372** [comment]
Never mind, then.

**Comment by m4xw** [comment]
I can tell you tho, this will be fixed in the foreseeable future ;)

**Comment by autofire372** [comment]
I'm guessing this needs to fixed upstream, or something?

**Comment by m4xw** [comment]
Nah, I just want this integrated via git subrepo, the libretro-deps sources need to be diffed against upstream sources and propery history needs to be created, so I can actually maintain these dependencies.
Then there is the question about android, which if i remember right, had some issues if it doesnt use the bundled static libs (really wanna get rid of those...)
Also new deps will reside in `custom/dependencies/<dep name>`

**Comment by m4xw** [comment]
Also for me this is a low prio Issue, since it never really worked for the -nx core, so I don't feel the need to do some dirty band-aid and rather just do it how I want it to.

**Comment by twinaphex** [comment]
I have a solution for this - it will only need consulting with @m4xw on Discord in terms of how we are going to use the subrepo. I can add the changes to Makefile.common and Makefile afterwards. I tested it works on Windows and Linux.

**Comment by MojoJojoDojo** [comment]
On Ubuntu I Installed this deb file and the core worked fine :
https://www.dropbox.com/s/79x3imq73tcqyw4/libpng12-0_1.2.54-1ubuntu1b_amd64.deb?dl=0

**Comment by m4xw** [comment]
This has been mitigated on the ios branch btw, still need some time before i merge it.

>  they're supposed to be compiled into the core itself.
This is true for platforms that support shared libraries, this does not apply (or rather applies limited) to static platforms (which mupen next is primarily written for).

**Comment by autofire372** [comment]
> This has been mitigated on the ios branch btw, still need some time before i merge it to develop.
> 
> > they're supposed to be compiled into the core itself.
> 
> This is true for platforms that support shared libraries, this does not apply (or rather applies limited) to static platforms (which mupen next is primarily written for).

Would "embedded" have been a better word choice?
