### ISSUE TITLE
Ability to dump textures to HTC format from within Libretro core

### ISSUE THREAD

**Issue by twinaphex** [libretro/mupen64plus-libretro-nx#81]
It's terrible to rely on Project64 for this with its constant nag screens and whatnot. There should be a core option for this if possible.

**Comment by m4xw** [comment]
Already works.

**Comment by twinaphex** [comment]
Can we talk on Discord BTW? I'd like to resolve things.

**Comment by twinaphex** [comment]
You say this works - how?

I put the textures in <system dir>/Mupen64plus/hires_texture/<name of game>.

The way it works in Project 64 is that it's supposed to create a .htc file inside the 'cache' dir (that would be in this case <system dir>/Mupen64plus/cache' once it's finished. But it doesn't do this at all.
