### ISSUE TITLE
FXAA Corruption

### ISSUE THREAD

**Issue by cobhc2019** [libretro/mupen64plus-libretro-nx#83]
Hi, could the 2D sprite corruption caused by the built in FXAA be looked into? The way this option works seems to quite well mimic the type of AA used on the actual N64, but the corruption makes it pretty unusable. Using a higher internal resolution and then scaling it back down to 640x480 seems to help, but it's still not perfect.

**Comment by m4xw** [comment]
Not enough information provided

**Comment by cobhc2019** [comment]
No problem, I'll provide screenshots when I'm home in a few hours. Thank you.

**Comment by mudlord** [comment]
So you are suggesting to not filter the 2D elements? That would be a request best suited to GLideN64 upstream.

**Comment by cobhc2019** [comment]
I hadn't thought of that specifically, but I guess that would work.

I've been chasing the Angrylion VI look without the performance hit, and being able to apply FXAA without compromising the 2D elements is the thing that always kills this for me.

I hadn't thought that this would be part of the renderer rather than part of Mupen, so yeah I'm probably barking up the wrong tree here.

Thank you for the response anyway @mudlord.
