### ISSUE TITLE
Expose 2D bgMode as core option

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/mupen64plus-libretro-nx#86]
GlideN64 Public Release 4 is supposed to have this fix:

https://4.bp.blogspot.com/-ko8yAAW6_4M/XHkMpWs8soI/AAAAAAAABJQ/jqbCIt4CsUkQY99rJD1Xrj-o9cByrLiIgCLcBGAs/s1600/Neon.jpg

In the standalone, the background is fixed and stable. In the core, the background is OK when zoomed out but breaks when zoomed in. Though, the standalone does have other issues that the core doesn't, like the text at the bottom right being broken.

**Comment by m4xw** [comment]
The fix is there, but its disabled/set to less accurate mode due to perf reasons on low end devices.
This should simply be exposed as core options
https://github.com/libretro/mupen64plus-libretro-nx/blob/develop/GLideN64/src/Config.cpp#L54

**Comment by m4xw** [comment]
Attached a Win64 build with bgStripped instead of bgOnePiece.
@Tasosgemah Confirm if thats the wanted behaviour please

[bgStripped_mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3524901/bgStripped_mupen64plus_next_libretro.zip)

**Comment by Tasosgemah** [comment]
Yes, this build fixes the issue.

This got me thinking, are there any other intended accuracy regressions like this in the core for the sake of performance? Could the core be split to two, one performance and one accuracy? Kinda like other cores like bsnes_performance and bsnes_accuracy? 

Users with fast machines and PCs would rather use a more accurate core. I thought that was the point of Mupen-next over the old, regular mupen core, that is to have all the latest fixes of GlideN64 ported to RetroArch.

**Comment by Tasosgemah** [comment]
Closed the issue by accident, should i leave it open?

**Comment by m4xw** [comment]
Why split the core?
This only needs to be a core option. I just never added it.
There are no other accuracy tradeoffs that I am aware of.
Leave this Issue open for now.

**Comment by m4xw** [comment]
//TODO :P

**Comment by Tasosgemah** [comment]
> This only needs to be a core option. I just never added it.
> There are no other accuracy tradeoffs that I am aware of.

Ok, that's great then.

Are there any issues in other games by using the more accurate "bgStripped" line? Or i can enable that option (when is available) globally and forget about it?

Thanks for the custom build, will use that until the option is implemented.

**Comment by dankcushions** [comment]
flycast uses a low_end define that changes the core option defaults when using a low end device: https://github.com/libretro/flycast/pull/475

adds some busy work to the makefile, though, as you have to define each low end platform

**Comment by m4xw** [comment]
@dankcushions I try to avoid that. Settings are too dependent on the games, low spec or not.

**Comment by BParks21** [comment]
Really looking forward to this option being added to the core!

**Comment by m4xw** [comment]
@BParks21 if you scroll up (https://github.com/libretro/mupen64plus-libretro-nx/issues/86#issuecomment-523400863) you will have a older ver with that option forced on.

**Comment by BParks21** [comment]
Yeah i saw that, thanks though I'm pretty patient. 😁

**Comment by Tasosgemah** [comment]
Yeah, i'd also like to wait for the proper version that doesn't have the 10 seconds loading bug.

**Comment by m4xw** [comment]
@Tasosgemah @BParks21 Tell me if the added core option works as expected ("Background Mode")
[win64_mupen64plus_next_libretro.zip](https://github.com/libretro/mupen64plus-libretro-nx/files/3609674/win64_mupen64plus_next_libretro.zip)

**Comment by Tasosgemah** [comment]
Tested Neon Genesis Evangelion. It loads fine and the backgrounds are correct.

However now there are some new bugs. In between mission text is corrupted and there is a bug at the right bottom of the screen

![Neon Genesis Evangelion (Japan)-190913-135609](https://user-images.githubusercontent.com/12124465/64857913-90577080-d62e-11e9-8897-a55aaa6570ab.png)

![Neon Genesis Evangelion (Japan)-190913-135941](https://user-images.githubusercontent.com/12124465/64858025-e88e7280-d62e-11e9-8415-256318717eb0.png)

**Comment by m4xw** [comment]
@Tasosgemah Theres no "new bug", thats the same you used prior lol.
None of the changes should cause that.

**Comment by Tasosgemah** [comment]
But these weren't in the previous version fixed version that you posted here.

There weren't in the version before that either.

**Comment by m4xw** [comment]
@Tasosgemah changed some other settings?

**Comment by Tasosgemah** [comment]
I'm using it with the same core.opt file as before. Let me delete it completely to see if a fresh one makes a difference.

**Comment by m4xw** [comment]
Also try correctTexrectCoords and enableNativeResTexrects, they might help.

**Comment by Tasosgemah** [comment]
Fresh, default opt file (with the background option default or changed) didn't help.

CorrectTexrectCoords and enableNativeResTexrects options don't seem to have any effect either.

**Comment by Tasosgemah** [comment]
If the opt file is fresh with the background option also on default, it fixes the bugs but then the backgrounds get broken since the new option is off.

**Comment by m4xw** [comment]
@Tasosgemah try standalone, might be a new upstream bug.

**Comment by m4xw** [comment]
Also try noise emulation off, just because.

**Comment by Tasosgemah** [comment]
Ah, sorry, i stopped following the standalone WIP pages and haven't downloaded a new version for a while now.

Tried disabling noise, didn't help.

**Comment by m4xw** [comment]
Okay then my first guess is a new upstream bug.
None of the recent changes explain it otherwise :/

**Comment by Tasosgemah** [comment]
Alright, thanks a lot anyway, hope it gets sorted

**Comment by m4xw** [comment]
Can you check & confirm that for me tho?

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-libretro-nx/commit/16d96924d8a31483bfd0b2d1bc39dc6e319d4352

**Comment by Tasosgemah** [comment]
You mean the standalone?

I don't know where to get a new version with this new change.

**Comment by m4xw** [comment]
https://ci.appveyor.com/project/gonetz/gliden64/builds/27203101/job/a77ook94ye2r6mlr/artifacts

**Comment by Tasosgemah** [comment]
Welp. Same thing on the standalone as well.

Though, for some reason when i try to open the video options it doesn't show anything (GUI bug?)

**Comment by m4xw** [comment]
@gonetz Are you aware of any regression?

**Comment by m4xw** [comment]
gonetz: fwiw these are all your upstream changes that got pulled in when the issue started appearing
https://github.com/libretro/mupen64plus-libretro-nx/commit/b2eb80efdfe1031a5135bf28d33bda4034b8e27b

**Comment by BParks21** [comment]
I'll test this as well.

**Comment by BParks21** [comment]
@m4xw  Well this core option didn't fix either of the two issues i opened for Yoshis Story.
 https://github.com/libretro/mupen64plus-libretro-nx/issues/97
https://github.com/libretro/mupen64plus-libretro-nx/issues/96

**Comment by m4xw** [comment]
Do you have widescreen enabled for yoshi? If so disable it.

**Comment by BParks21** [comment]
No.

**Comment by m4xw** [comment]
There might be more going on here, this seems very related to me.

**Comment by BParks21** [comment]
Are you sure, I thought this was happening in upstream as well?

**Comment by m4xw** [comment]
No i meant the yoshi issues.
Dunno if that one happen upstream as I didn't try with them.

**Comment by BParks21** [comment]
Well turning off per pixel lighting fixes the multi color blocks but does not fix the background issue for Yoshi. No settings seem to fix the backgrounds in levels.

**Comment by Tasosgemah** [comment]
Some pictures in case they help

**Background mode - "Per Piece"**

Boot screen (bad):
![Neon Genesis Evangelion (Japan)-190914-060327](https://user-images.githubusercontent.com/12124465/64902746-aceabb80-d6b5-11e9-84c8-e51f424105f3.png)

Select data (good):
![Neon Genesis Evangelion (Japan)-190914-060408](https://user-images.githubusercontent.com/12124465/64902750-b8d67d80-d6b5-11e9-8eae-e378361c16a3.png)

Next screen (good):
![Neon Genesis Evangelion (Japan)-190914-060418](https://user-images.githubusercontent.com/12124465/64902759-d277c500-d6b5-11e9-9733-e42f5419f063.png)

Ingame, the mountains in the background are broken but the GUI is fine.


Background mode - "Per Piece"

Boot screen (good):
![Neon Genesis Evangelion (Japan)-190914-060812](https://user-images.githubusercontent.com/12124465/64902776-21255f00-d6b6-11e9-9416-c9bee9cfec4c.png)

Select data (bad):
![Neon Genesis Evangelion (Japan)-190914-060823](https://user-images.githubusercontent.com/12124465/64902783-38fce300-d6b6-11e9-9481-579715636432.png)

Next screen (bad):
![Neon Genesis Evangelion (Japan)-190914-060833](https://user-images.githubusercontent.com/12124465/64902785-4dd97680-d6b6-11e9-9a82-42442d68b4e4.png)

Ingame, the mountains in the background are fixed but the GUI has than bug in the bottom right corner.


Seems like there are a few 2D elements that behave differently than others and when one batch gets fixed the other breaks.

**Comment by Tasosgemah** [comment]
This bug is still present, though this particular issue about the added option is closed. 

Should i open a new one about Neon Genesis Evangelion?

**Comment by m4xw** [comment]
@Tasosgemah No, I don't track upstream issues.
