### ISSUE TITLE
[Ghost] Investigate broken support with older RA ver / libretro spec on embedded platforms

### ISSUE THREAD

**Issue by Cee123** [libretro/mupen64plus-libretro-nx#87]
Ok, so I just thought I'd mention this. When Mupen64plus-nx is built from source on the Odroid XU4 (and possibly other SBCs as I haven't tested any others), almost all games will crash before they're loaded. This will occur after making ANY changes to the retroarch configuration. Not quite sure why that would be the case. Any ideas?

**Comment by m4xw** [comment]
Afaik it works on odroid just fine.

**Comment by m4xw** [comment]
You should provide a backtrace

**Comment by Cee123** [comment]
Not sure what you mean backtrace? How do I do that?

**Comment by m4xw** [comment]
You will need to use gdb.
"It crashes" isn't helpful in any way :/

**Comment by Cee123** [comment]
The binary version of Mupenplux-nx works fine. But there are crashes when it is built from source.

**Comment by m4xw** [comment]
"Binary version"?

**Comment by Cee123** [comment]
Ok nevermind, I'll just try to find a log file for retroarch. It seems to happen whenever any changes are made within retroarch and saved to configuration.

**Comment by m4xw** [comment]
That doesnt sound like a core issue to me.
What setting are u trying to change?

**Comment by Cee123** [comment]
I've not only tried changing settings. I've also tried saving the configuration as it is without making any changes. Still crashes.

**Comment by m4xw** [comment]
> What setting are u trying to change?

**Comment by Cee123** [comment]
Well, OK, I tried changing resolution, I've tried adding a bezel under overlay, I've tried changing the screen size. I've even tried just enabling advanced settings under retroarch. Doesn't seem to be related to any one setting. :(

**Comment by Cee123** [comment]
I'll try to find a log file for it if I can find one.

**Comment by m4xw** [comment]
ok

**Comment by Cee123** [comment]
I'm really sorry about this but I can't even prove this because I can't get a log file as it won't generate one because retroarch crashes before it even loads a game.

I'm running retroarch 1.7.6 on The Retro Arena

**Comment by m4xw** [comment]
Can you try latest RA?

**Comment by Cee123** [comment]
So I'm not sure if the issue is with the core, with the Retro arena or the retroarch version.

Nevermind it's hopeless

**Comment by m4xw** [comment]
@Cee123 I actually got a Idea, but you will need to try updated RA.

**Comment by Cee123** [comment]
As far as I know it's not supported on there yet -_-

**Comment by m4xw** [comment]
Why did you close the issue?
If support between retroarch versions is broken, this should be investigated!

**Comment by Cee123** [comment]
Oh ok, thank you so much! I wasn't really sure it'd be worth investigating as I really had no log file to prove it.

**Comment by Cee123** [comment]
Interestingly, some games are working on another SD card. Even though most of them crash. But this game has a totally different issue - the controls will not respond.

![thumbnail_IMAG0353](https://user-images.githubusercontent.com/43462099/63590145-992fc600-c5dd-11e9-844a-3458cda7e66c.jpg)

![thumbnail_IMAG0352](https://user-images.githubusercontent.com/43462099/63590154-9fbe3d80-c5dd-11e9-8dc4-5c40fbd29acc.jpg)

Any ideas what would be causing this?

**Comment by Cee123** [comment]
@m4xw 

Ok, after reading what some very helpful people on discord have written, I found the issue itself was with the **shaders**. These are the steps to take for anyone else with this issue of Mupen64plus-NX constantly crashing upon loading a game. And these are the steps I also took to fix this problem.

1. Go into your retroarch-core-options.cfg and edit the line "mupen64plus-EnableShadersStorage" and set it to "False". Or simply turn this option to **False** if you can find it under the menu.
2. Go into the BIOS folder in either RetroPie or RetroArena, find the mupen64plus folder and go into the folder "shaders", delete EVERYTHING.

Now the games should boot. And things should be running fine. Thank you to the users on discord who figured this out and provided this solution. Wish I had've known this earlier, would've saved me hours of frustration.

**Comment by m4xw** [comment]
I mean... There's also already a issue for that :P

**Comment by Cee123** [comment]
Is there? Should've told me haha. I didn't know the shaders were to blame for the crashing. :|
