### ISSUE TITLE
Zelda OoT - Pause Screen glitch

### ISSUE THREAD

**Issue by JHorbach** [libretro/mupen64plus-libretro-nx#91]
When I start the game, and pause inside Link's house it works, but when I leave the house and try to pause the core freezes (retroarch also).

**Comment by m4xw** [comment]
Platform?
More details?

**Comment by m4xw** [comment]
This sounds to me that you either have fbemu off or that u use it on a not supported platform (GLES2, thats android and rpi and some other boards)

**Comment by JHorbach** [comment]
You could close it, the problem was the fullspeed option. Thank You!

**Comment by m4xw** [comment]
Oh yea, that option can cause Issues in a bunch of game.
Enforces CountPerOp
